// Code generated by ent, DO NOT EDIT.

package quotanetpayoutitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the quotanetpayoutitem type in the database.
	Label = "quota_net_payout_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldItemKey holds the string denoting the item_key field in the database.
	FieldItemKey = "item_key"
	// FieldBatchID holds the string denoting the batch_id field in the database.
	FieldBatchID = "batch_id"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldWalletAddress holds the string denoting the wallet_address field in the database.
	FieldWalletAddress = "wallet_address"
	// FieldTokenFlow holds the string denoting the token_flow field in the database.
	FieldTokenFlow = "token_flow"
	// FieldAmountCxs holds the string denoting the amount_cxs field in the database.
	FieldAmountCxs = "amount_cxs"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTxHash holds the string denoting the tx_hash field in the database.
	FieldTxHash = "tx_hash"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldFinalizedAt holds the string denoting the finalized_at field in the database.
	FieldFinalizedAt = "finalized_at"
	// Table holds the table name of the quotanetpayoutitem in the database.
	Table = "quotanet_payout_items"
)

// Columns holds all SQL columns for quotanetpayoutitem fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldItemKey,
	FieldBatchID,
	FieldNodeID,
	FieldWalletAddress,
	FieldTokenFlow,
	FieldAmountCxs,
	FieldStatus,
	FieldTxHash,
	FieldErrorMessage,
	FieldFinalizedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ItemKeyValidator is a validator for the "item_key" field. It is called by the builders before save.
	ItemKeyValidator func(string) error
	// WalletAddressValidator is a validator for the "wallet_address" field. It is called by the builders before save.
	WalletAddressValidator func(string) error
	// DefaultTokenFlow holds the default value on creation for the "token_flow" field.
	DefaultTokenFlow int64
	// DefaultAmountCxs holds the default value on creation for the "amount_cxs" field.
	DefaultAmountCxs float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// TxHashValidator is a validator for the "tx_hash" field. It is called by the builders before save.
	TxHashValidator func(string) error
)

// OrderOption defines the ordering options for the QuotaNetPayoutItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByItemKey orders the results by the item_key field.
func ByItemKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemKey, opts...).ToFunc()
}

// ByBatchID orders the results by the batch_id field.
func ByBatchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchID, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByWalletAddress orders the results by the wallet_address field.
func ByWalletAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWalletAddress, opts...).ToFunc()
}

// ByTokenFlow orders the results by the token_flow field.
func ByTokenFlow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenFlow, opts...).ToFunc()
}

// ByAmountCxs orders the results by the amount_cxs field.
func ByAmountCxs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCxs, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTxHash orders the results by the tx_hash field.
func ByTxHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTxHash, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByFinalizedAt orders the results by the finalized_at field.
func ByFinalizedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinalizedAt, opts...).ToFunc()
}
