// Code generated by ent, DO NOT EDIT.

package quotanetpayoutitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// ItemKey applies equality check predicate on the "item_key" field. It's identical to ItemKeyEQ.
func ItemKey(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldItemKey, v))
}

// BatchID applies equality check predicate on the "batch_id" field. It's identical to BatchIDEQ.
func BatchID(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldBatchID, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldNodeID, v))
}

// WalletAddress applies equality check predicate on the "wallet_address" field. It's identical to WalletAddressEQ.
func WalletAddress(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldWalletAddress, v))
}

// TokenFlow applies equality check predicate on the "token_flow" field. It's identical to TokenFlowEQ.
func TokenFlow(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldTokenFlow, v))
}

// ContributionUsd applies equality check predicate on the "contribution_usd" field. It's identical to ContributionUsdEQ.
func ContributionUsd(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldContributionUsd, v))
}

// AmountCxs applies equality check predicate on the "amount_cxs" field. It's identical to AmountCxsEQ.
func AmountCxs(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldAmountCxs, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldStatus, v))
}

// TxHash applies equality check predicate on the "tx_hash" field. It's identical to TxHashEQ.
func TxHash(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldTxHash, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldErrorMessage, v))
}

// FinalizedAt applies equality check predicate on the "finalized_at" field. It's identical to FinalizedAtEQ.
func FinalizedAt(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldFinalizedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// ItemKeyEQ applies the EQ predicate on the "item_key" field.
func ItemKeyEQ(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldItemKey, v))
}

// ItemKeyNEQ applies the NEQ predicate on the "item_key" field.
func ItemKeyNEQ(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldItemKey, v))
}

// ItemKeyIn applies the In predicate on the "item_key" field.
func ItemKeyIn(vs ...string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldItemKey, vs...))
}

// ItemKeyNotIn applies the NotIn predicate on the "item_key" field.
func ItemKeyNotIn(vs ...string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldItemKey, vs...))
}

// ItemKeyGT applies the GT predicate on the "item_key" field.
func ItemKeyGT(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldItemKey, v))
}

// ItemKeyGTE applies the GTE predicate on the "item_key" field.
func ItemKeyGTE(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldItemKey, v))
}

// ItemKeyLT applies the LT predicate on the "item_key" field.
func ItemKeyLT(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldItemKey, v))
}

// ItemKeyLTE applies the LTE predicate on the "item_key" field.
func ItemKeyLTE(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldItemKey, v))
}

// ItemKeyContains applies the Contains predicate on the "item_key" field.
func ItemKeyContains(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldContains(FieldItemKey, v))
}

// ItemKeyHasPrefix applies the HasPrefix predicate on the "item_key" field.
func ItemKeyHasPrefix(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldHasPrefix(FieldItemKey, v))
}

// ItemKeyHasSuffix applies the HasSuffix predicate on the "item_key" field.
func ItemKeyHasSuffix(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldHasSuffix(FieldItemKey, v))
}

// ItemKeyEqualFold applies the EqualFold predicate on the "item_key" field.
func ItemKeyEqualFold(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEqualFold(FieldItemKey, v))
}

// ItemKeyContainsFold applies the ContainsFold predicate on the "item_key" field.
func ItemKeyContainsFold(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldContainsFold(FieldItemKey, v))
}

// BatchIDEQ applies the EQ predicate on the "batch_id" field.
func BatchIDEQ(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldBatchID, v))
}

// BatchIDNEQ applies the NEQ predicate on the "batch_id" field.
func BatchIDNEQ(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldBatchID, v))
}

// BatchIDIn applies the In predicate on the "batch_id" field.
func BatchIDIn(vs ...int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldBatchID, vs...))
}

// BatchIDNotIn applies the NotIn predicate on the "batch_id" field.
func BatchIDNotIn(vs ...int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldBatchID, vs...))
}

// BatchIDGT applies the GT predicate on the "batch_id" field.
func BatchIDGT(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldBatchID, v))
}

// BatchIDGTE applies the GTE predicate on the "batch_id" field.
func BatchIDGTE(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldBatchID, v))
}

// BatchIDLT applies the LT predicate on the "batch_id" field.
func BatchIDLT(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldBatchID, v))
}

// BatchIDLTE applies the LTE predicate on the "batch_id" field.
func BatchIDLTE(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldBatchID, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDIsNil applies the IsNil predicate on the "node_id" field.
func NodeIDIsNil() predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIsNull(FieldNodeID))
}

// NodeIDNotNil applies the NotNil predicate on the "node_id" field.
func NodeIDNotNil() predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotNull(FieldNodeID))
}

// WalletAddressEQ applies the EQ predicate on the "wallet_address" field.
func WalletAddressEQ(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldWalletAddress, v))
}

// WalletAddressNEQ applies the NEQ predicate on the "wallet_address" field.
func WalletAddressNEQ(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldWalletAddress, v))
}

// WalletAddressIn applies the In predicate on the "wallet_address" field.
func WalletAddressIn(vs ...string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldWalletAddress, vs...))
}

// WalletAddressNotIn applies the NotIn predicate on the "wallet_address" field.
func WalletAddressNotIn(vs ...string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldWalletAddress, vs...))
}

// WalletAddressGT applies the GT predicate on the "wallet_address" field.
func WalletAddressGT(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldWalletAddress, v))
}

// WalletAddressGTE applies the GTE predicate on the "wallet_address" field.
func WalletAddressGTE(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldWalletAddress, v))
}

// WalletAddressLT applies the LT predicate on the "wallet_address" field.
func WalletAddressLT(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldWalletAddress, v))
}

// WalletAddressLTE applies the LTE predicate on the "wallet_address" field.
func WalletAddressLTE(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldWalletAddress, v))
}

// WalletAddressContains applies the Contains predicate on the "wallet_address" field.
func WalletAddressContains(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldContains(FieldWalletAddress, v))
}

// WalletAddressHasPrefix applies the HasPrefix predicate on the "wallet_address" field.
func WalletAddressHasPrefix(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldHasPrefix(FieldWalletAddress, v))
}

// WalletAddressHasSuffix applies the HasSuffix predicate on the "wallet_address" field.
func WalletAddressHasSuffix(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldHasSuffix(FieldWalletAddress, v))
}

// WalletAddressEqualFold applies the EqualFold predicate on the "wallet_address" field.
func WalletAddressEqualFold(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEqualFold(FieldWalletAddress, v))
}

// WalletAddressContainsFold applies the ContainsFold predicate on the "wallet_address" field.
func WalletAddressContainsFold(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldContainsFold(FieldWalletAddress, v))
}

// TokenFlowEQ applies the EQ predicate on the "token_flow" field.
func TokenFlowEQ(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldTokenFlow, v))
}

// TokenFlowNEQ applies the NEQ predicate on the "token_flow" field.
func TokenFlowNEQ(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldTokenFlow, v))
}

// TokenFlowIn applies the In predicate on the "token_flow" field.
func TokenFlowIn(vs ...int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldTokenFlow, vs...))
}

// TokenFlowNotIn applies the NotIn predicate on the "token_flow" field.
func TokenFlowNotIn(vs ...int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldTokenFlow, vs...))
}

// TokenFlowGT applies the GT predicate on the "token_flow" field.
func TokenFlowGT(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldTokenFlow, v))
}

// TokenFlowGTE applies the GTE predicate on the "token_flow" field.
func TokenFlowGTE(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldTokenFlow, v))
}

// TokenFlowLT applies the LT predicate on the "token_flow" field.
func TokenFlowLT(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldTokenFlow, v))
}

// TokenFlowLTE applies the LTE predicate on the "token_flow" field.
func TokenFlowLTE(v int64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldTokenFlow, v))
}

// ContributionUsdEQ applies the EQ predicate on the "contribution_usd" field.
func ContributionUsdEQ(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldContributionUsd, v))
}

// ContributionUsdNEQ applies the NEQ predicate on the "contribution_usd" field.
func ContributionUsdNEQ(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldContributionUsd, v))
}

// ContributionUsdIn applies the In predicate on the "contribution_usd" field.
func ContributionUsdIn(vs ...float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldContributionUsd, vs...))
}

// ContributionUsdNotIn applies the NotIn predicate on the "contribution_usd" field.
func ContributionUsdNotIn(vs ...float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldContributionUsd, vs...))
}

// ContributionUsdGT applies the GT predicate on the "contribution_usd" field.
func ContributionUsdGT(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldContributionUsd, v))
}

// ContributionUsdGTE applies the GTE predicate on the "contribution_usd" field.
func ContributionUsdGTE(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldContributionUsd, v))
}

// ContributionUsdLT applies the LT predicate on the "contribution_usd" field.
func ContributionUsdLT(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldContributionUsd, v))
}

// ContributionUsdLTE applies the LTE predicate on the "contribution_usd" field.
func ContributionUsdLTE(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldContributionUsd, v))
}

// AmountCxsEQ applies the EQ predicate on the "amount_cxs" field.
func AmountCxsEQ(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldAmountCxs, v))
}

// AmountCxsNEQ applies the NEQ predicate on the "amount_cxs" field.
func AmountCxsNEQ(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldAmountCxs, v))
}

// AmountCxsIn applies the In predicate on the "amount_cxs" field.
func AmountCxsIn(vs ...float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldAmountCxs, vs...))
}

// AmountCxsNotIn applies the NotIn predicate on the "amount_cxs" field.
func AmountCxsNotIn(vs ...float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldAmountCxs, vs...))
}

// AmountCxsGT applies the GT predicate on the "amount_cxs" field.
func AmountCxsGT(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldAmountCxs, v))
}

// AmountCxsGTE applies the GTE predicate on the "amount_cxs" field.
func AmountCxsGTE(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldAmountCxs, v))
}

// AmountCxsLT applies the LT predicate on the "amount_cxs" field.
func AmountCxsLT(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldAmountCxs, v))
}

// AmountCxsLTE applies the LTE predicate on the "amount_cxs" field.
func AmountCxsLTE(v float64) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldAmountCxs, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldContainsFold(FieldStatus, v))
}

// TxHashEQ applies the EQ predicate on the "tx_hash" field.
func TxHashEQ(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldTxHash, v))
}

// TxHashNEQ applies the NEQ predicate on the "tx_hash" field.
func TxHashNEQ(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldTxHash, v))
}

// TxHashIn applies the In predicate on the "tx_hash" field.
func TxHashIn(vs ...string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldTxHash, vs...))
}

// TxHashNotIn applies the NotIn predicate on the "tx_hash" field.
func TxHashNotIn(vs ...string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldTxHash, vs...))
}

// TxHashGT applies the GT predicate on the "tx_hash" field.
func TxHashGT(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldTxHash, v))
}

// TxHashGTE applies the GTE predicate on the "tx_hash" field.
func TxHashGTE(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldTxHash, v))
}

// TxHashLT applies the LT predicate on the "tx_hash" field.
func TxHashLT(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldTxHash, v))
}

// TxHashLTE applies the LTE predicate on the "tx_hash" field.
func TxHashLTE(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldTxHash, v))
}

// TxHashContains applies the Contains predicate on the "tx_hash" field.
func TxHashContains(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldContains(FieldTxHash, v))
}

// TxHashHasPrefix applies the HasPrefix predicate on the "tx_hash" field.
func TxHashHasPrefix(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldHasPrefix(FieldTxHash, v))
}

// TxHashHasSuffix applies the HasSuffix predicate on the "tx_hash" field.
func TxHashHasSuffix(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldHasSuffix(FieldTxHash, v))
}

// TxHashIsNil applies the IsNil predicate on the "tx_hash" field.
func TxHashIsNil() predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIsNull(FieldTxHash))
}

// TxHashNotNil applies the NotNil predicate on the "tx_hash" field.
func TxHashNotNil() predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotNull(FieldTxHash))
}

// TxHashEqualFold applies the EqualFold predicate on the "tx_hash" field.
func TxHashEqualFold(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEqualFold(FieldTxHash, v))
}

// TxHashContainsFold applies the ContainsFold predicate on the "tx_hash" field.
func TxHashContainsFold(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldContainsFold(FieldTxHash, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldContainsFold(FieldErrorMessage, v))
}

// FinalizedAtEQ applies the EQ predicate on the "finalized_at" field.
func FinalizedAtEQ(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldEQ(FieldFinalizedAt, v))
}

// FinalizedAtNEQ applies the NEQ predicate on the "finalized_at" field.
func FinalizedAtNEQ(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNEQ(FieldFinalizedAt, v))
}

// FinalizedAtIn applies the In predicate on the "finalized_at" field.
func FinalizedAtIn(vs ...time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIn(FieldFinalizedAt, vs...))
}

// FinalizedAtNotIn applies the NotIn predicate on the "finalized_at" field.
func FinalizedAtNotIn(vs ...time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotIn(FieldFinalizedAt, vs...))
}

// FinalizedAtGT applies the GT predicate on the "finalized_at" field.
func FinalizedAtGT(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGT(FieldFinalizedAt, v))
}

// FinalizedAtGTE applies the GTE predicate on the "finalized_at" field.
func FinalizedAtGTE(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldGTE(FieldFinalizedAt, v))
}

// FinalizedAtLT applies the LT predicate on the "finalized_at" field.
func FinalizedAtLT(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLT(FieldFinalizedAt, v))
}

// FinalizedAtLTE applies the LTE predicate on the "finalized_at" field.
func FinalizedAtLTE(v time.Time) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldLTE(FieldFinalizedAt, v))
}

// FinalizedAtIsNil applies the IsNil predicate on the "finalized_at" field.
func FinalizedAtIsNil() predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldIsNull(FieldFinalizedAt))
}

// FinalizedAtNotNil applies the NotNil predicate on the "finalized_at" field.
func FinalizedAtNotNil() predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.FieldNotNull(FieldFinalizedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuotaNetPayoutItem) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuotaNetPayoutItem) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuotaNetPayoutItem) predicate.QuotaNetPayoutItem {
	return predicate.QuotaNetPayoutItem(sql.NotPredicates(p))
}
