// Code generated by ent, DO NOT EDIT.

package quotanetnode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldDeletedAt, v))
}

// NodeKey applies equality check predicate on the "node_key" field. It's identical to NodeKeyEQ.
func NodeKey(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldNodeKey, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldName, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldOwnerUserID, v))
}

// WalletAddress applies equality check predicate on the "wallet_address" field. It's identical to WalletAddressEQ.
func WalletAddress(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldWalletAddress, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldTokenHash, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldStatus, v))
}

// ProtocolVersion applies equality check predicate on the "protocol_version" field. It's identical to ProtocolVersionEQ.
func ProtocolVersion(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldProtocolVersion, v))
}

// ClientVersion applies equality check predicate on the "client_version" field. It's identical to ClientVersionEQ.
func ClientVersion(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldClientVersion, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotNull(FieldDeletedAt))
}

// NodeKeyEQ applies the EQ predicate on the "node_key" field.
func NodeKeyEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldNodeKey, v))
}

// NodeKeyNEQ applies the NEQ predicate on the "node_key" field.
func NodeKeyNEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldNodeKey, v))
}

// NodeKeyIn applies the In predicate on the "node_key" field.
func NodeKeyIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldNodeKey, vs...))
}

// NodeKeyNotIn applies the NotIn predicate on the "node_key" field.
func NodeKeyNotIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldNodeKey, vs...))
}

// NodeKeyGT applies the GT predicate on the "node_key" field.
func NodeKeyGT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldNodeKey, v))
}

// NodeKeyGTE applies the GTE predicate on the "node_key" field.
func NodeKeyGTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldNodeKey, v))
}

// NodeKeyLT applies the LT predicate on the "node_key" field.
func NodeKeyLT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldNodeKey, v))
}

// NodeKeyLTE applies the LTE predicate on the "node_key" field.
func NodeKeyLTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldNodeKey, v))
}

// NodeKeyContains applies the Contains predicate on the "node_key" field.
func NodeKeyContains(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContains(FieldNodeKey, v))
}

// NodeKeyHasPrefix applies the HasPrefix predicate on the "node_key" field.
func NodeKeyHasPrefix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasPrefix(FieldNodeKey, v))
}

// NodeKeyHasSuffix applies the HasSuffix predicate on the "node_key" field.
func NodeKeyHasSuffix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasSuffix(FieldNodeKey, v))
}

// NodeKeyEqualFold applies the EqualFold predicate on the "node_key" field.
func NodeKeyEqualFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEqualFold(FieldNodeKey, v))
}

// NodeKeyContainsFold applies the ContainsFold predicate on the "node_key" field.
func NodeKeyContainsFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContainsFold(FieldNodeKey, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContainsFold(FieldName, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v int64) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldOwnerUserID, v))
}

// OwnerUserIDIsNil applies the IsNil predicate on the "owner_user_id" field.
func OwnerUserIDIsNil() predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIsNull(FieldOwnerUserID))
}

// OwnerUserIDNotNil applies the NotNil predicate on the "owner_user_id" field.
func OwnerUserIDNotNil() predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotNull(FieldOwnerUserID))
}

// WalletAddressEQ applies the EQ predicate on the "wallet_address" field.
func WalletAddressEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldWalletAddress, v))
}

// WalletAddressNEQ applies the NEQ predicate on the "wallet_address" field.
func WalletAddressNEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldWalletAddress, v))
}

// WalletAddressIn applies the In predicate on the "wallet_address" field.
func WalletAddressIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldWalletAddress, vs...))
}

// WalletAddressNotIn applies the NotIn predicate on the "wallet_address" field.
func WalletAddressNotIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldWalletAddress, vs...))
}

// WalletAddressGT applies the GT predicate on the "wallet_address" field.
func WalletAddressGT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldWalletAddress, v))
}

// WalletAddressGTE applies the GTE predicate on the "wallet_address" field.
func WalletAddressGTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldWalletAddress, v))
}

// WalletAddressLT applies the LT predicate on the "wallet_address" field.
func WalletAddressLT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldWalletAddress, v))
}

// WalletAddressLTE applies the LTE predicate on the "wallet_address" field.
func WalletAddressLTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldWalletAddress, v))
}

// WalletAddressContains applies the Contains predicate on the "wallet_address" field.
func WalletAddressContains(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContains(FieldWalletAddress, v))
}

// WalletAddressHasPrefix applies the HasPrefix predicate on the "wallet_address" field.
func WalletAddressHasPrefix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasPrefix(FieldWalletAddress, v))
}

// WalletAddressHasSuffix applies the HasSuffix predicate on the "wallet_address" field.
func WalletAddressHasSuffix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasSuffix(FieldWalletAddress, v))
}

// WalletAddressEqualFold applies the EqualFold predicate on the "wallet_address" field.
func WalletAddressEqualFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEqualFold(FieldWalletAddress, v))
}

// WalletAddressContainsFold applies the ContainsFold predicate on the "wallet_address" field.
func WalletAddressContainsFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContainsFold(FieldWalletAddress, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContainsFold(FieldTokenHash, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContainsFold(FieldStatus, v))
}

// ProtocolVersionEQ applies the EQ predicate on the "protocol_version" field.
func ProtocolVersionEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldProtocolVersion, v))
}

// ProtocolVersionNEQ applies the NEQ predicate on the "protocol_version" field.
func ProtocolVersionNEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldProtocolVersion, v))
}

// ProtocolVersionIn applies the In predicate on the "protocol_version" field.
func ProtocolVersionIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldProtocolVersion, vs...))
}

// ProtocolVersionNotIn applies the NotIn predicate on the "protocol_version" field.
func ProtocolVersionNotIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldProtocolVersion, vs...))
}

// ProtocolVersionGT applies the GT predicate on the "protocol_version" field.
func ProtocolVersionGT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldProtocolVersion, v))
}

// ProtocolVersionGTE applies the GTE predicate on the "protocol_version" field.
func ProtocolVersionGTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldProtocolVersion, v))
}

// ProtocolVersionLT applies the LT predicate on the "protocol_version" field.
func ProtocolVersionLT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldProtocolVersion, v))
}

// ProtocolVersionLTE applies the LTE predicate on the "protocol_version" field.
func ProtocolVersionLTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldProtocolVersion, v))
}

// ProtocolVersionContains applies the Contains predicate on the "protocol_version" field.
func ProtocolVersionContains(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContains(FieldProtocolVersion, v))
}

// ProtocolVersionHasPrefix applies the HasPrefix predicate on the "protocol_version" field.
func ProtocolVersionHasPrefix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasPrefix(FieldProtocolVersion, v))
}

// ProtocolVersionHasSuffix applies the HasSuffix predicate on the "protocol_version" field.
func ProtocolVersionHasSuffix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasSuffix(FieldProtocolVersion, v))
}

// ProtocolVersionIsNil applies the IsNil predicate on the "protocol_version" field.
func ProtocolVersionIsNil() predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIsNull(FieldProtocolVersion))
}

// ProtocolVersionNotNil applies the NotNil predicate on the "protocol_version" field.
func ProtocolVersionNotNil() predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotNull(FieldProtocolVersion))
}

// ProtocolVersionEqualFold applies the EqualFold predicate on the "protocol_version" field.
func ProtocolVersionEqualFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEqualFold(FieldProtocolVersion, v))
}

// ProtocolVersionContainsFold applies the ContainsFold predicate on the "protocol_version" field.
func ProtocolVersionContainsFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContainsFold(FieldProtocolVersion, v))
}

// ClientVersionEQ applies the EQ predicate on the "client_version" field.
func ClientVersionEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldClientVersion, v))
}

// ClientVersionNEQ applies the NEQ predicate on the "client_version" field.
func ClientVersionNEQ(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldClientVersion, v))
}

// ClientVersionIn applies the In predicate on the "client_version" field.
func ClientVersionIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldClientVersion, vs...))
}

// ClientVersionNotIn applies the NotIn predicate on the "client_version" field.
func ClientVersionNotIn(vs ...string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldClientVersion, vs...))
}

// ClientVersionGT applies the GT predicate on the "client_version" field.
func ClientVersionGT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldClientVersion, v))
}

// ClientVersionGTE applies the GTE predicate on the "client_version" field.
func ClientVersionGTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldClientVersion, v))
}

// ClientVersionLT applies the LT predicate on the "client_version" field.
func ClientVersionLT(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldClientVersion, v))
}

// ClientVersionLTE applies the LTE predicate on the "client_version" field.
func ClientVersionLTE(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldClientVersion, v))
}

// ClientVersionContains applies the Contains predicate on the "client_version" field.
func ClientVersionContains(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContains(FieldClientVersion, v))
}

// ClientVersionHasPrefix applies the HasPrefix predicate on the "client_version" field.
func ClientVersionHasPrefix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasPrefix(FieldClientVersion, v))
}

// ClientVersionHasSuffix applies the HasSuffix predicate on the "client_version" field.
func ClientVersionHasSuffix(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldHasSuffix(FieldClientVersion, v))
}

// ClientVersionIsNil applies the IsNil predicate on the "client_version" field.
func ClientVersionIsNil() predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIsNull(FieldClientVersion))
}

// ClientVersionNotNil applies the NotNil predicate on the "client_version" field.
func ClientVersionNotNil() predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotNull(FieldClientVersion))
}

// ClientVersionEqualFold applies the EqualFold predicate on the "client_version" field.
func ClientVersionEqualFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEqualFold(FieldClientVersion, v))
}

// ClientVersionContainsFold applies the ContainsFold predicate on the "client_version" field.
func ClientVersionContainsFold(v string) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldContainsFold(FieldClientVersion, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.FieldNotNull(FieldLastSeenAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuotaNetNode) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuotaNetNode) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuotaNetNode) predicate.QuotaNetNode {
	return predicate.QuotaNetNode(sql.NotPredicates(p))
}
