// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/quotanetpayoutbatch"
)

// QuotaNetPayoutBatch is the model entity for the QuotaNetPayoutBatch schema.
type QuotaNetPayoutBatch struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// BatchKey holds the value of the "batch_key" field.
	BatchKey string `json:"batch_key,omitempty"`
	// WindowStart holds the value of the "window_start" field.
	WindowStart time.Time `json:"window_start,omitempty"`
	// WindowEnd holds the value of the "window_end" field.
	WindowEnd time.Time `json:"window_end,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Network holds the value of the "network" field.
	Network string `json:"network,omitempty"`
	// TotalTokenFlow holds the value of the "total_token_flow" field.
	TotalTokenFlow int64 `json:"total_token_flow,omitempty"`
	// TotalAmountCxs holds the value of the "total_amount_cxs" field.
	TotalAmountCxs float64 `json:"total_amount_cxs,omitempty"`
	// ItemCount holds the value of the "item_count" field.
	ItemCount int `json:"item_count,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *int64 `json:"created_by,omitempty"`
	// ApprovedBy holds the value of the "approved_by" field.
	ApprovedBy   *int64 `json:"approved_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QuotaNetPayoutBatch) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quotanetpayoutbatch.FieldTotalAmountCxs:
			values[i] = new(sql.NullFloat64)
		case quotanetpayoutbatch.FieldID, quotanetpayoutbatch.FieldTotalTokenFlow, quotanetpayoutbatch.FieldItemCount, quotanetpayoutbatch.FieldCreatedBy, quotanetpayoutbatch.FieldApprovedBy:
			values[i] = new(sql.NullInt64)
		case quotanetpayoutbatch.FieldBatchKey, quotanetpayoutbatch.FieldStatus, quotanetpayoutbatch.FieldNetwork:
			values[i] = new(sql.NullString)
		case quotanetpayoutbatch.FieldCreatedAt, quotanetpayoutbatch.FieldUpdatedAt, quotanetpayoutbatch.FieldWindowStart, quotanetpayoutbatch.FieldWindowEnd:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QuotaNetPayoutBatch fields.
func (_m *QuotaNetPayoutBatch) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quotanetpayoutbatch.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case quotanetpayoutbatch.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case quotanetpayoutbatch.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case quotanetpayoutbatch.FieldBatchKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field batch_key", values[i])
			} else if value.Valid {
				_m.BatchKey = value.String
			}
		case quotanetpayoutbatch.FieldWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_start", values[i])
			} else if value.Valid {
				_m.WindowStart = value.Time
			}
		case quotanetpayoutbatch.FieldWindowEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_end", values[i])
			} else if value.Valid {
				_m.WindowEnd = value.Time
			}
		case quotanetpayoutbatch.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case quotanetpayoutbatch.FieldNetwork:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network", values[i])
			} else if value.Valid {
				_m.Network = value.String
			}
		case quotanetpayoutbatch.FieldTotalTokenFlow:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_token_flow", values[i])
			} else if value.Valid {
				_m.TotalTokenFlow = value.Int64
			}
		case quotanetpayoutbatch.FieldTotalAmountCxs:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount_cxs", values[i])
			} else if value.Valid {
				_m.TotalAmountCxs = value.Float64
			}
		case quotanetpayoutbatch.FieldItemCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field item_count", values[i])
			} else if value.Valid {
				_m.ItemCount = int(value.Int64)
			}
		case quotanetpayoutbatch.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case quotanetpayoutbatch.FieldApprovedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field approved_by", values[i])
			} else if value.Valid {
				_m.ApprovedBy = new(int64)
				*_m.ApprovedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QuotaNetPayoutBatch.
// This includes values selected through modifiers, order, etc.
func (_m *QuotaNetPayoutBatch) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this QuotaNetPayoutBatch.
// Note that you need to call QuotaNetPayoutBatch.Unwrap() before calling this method if this QuotaNetPayoutBatch
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *QuotaNetPayoutBatch) Update() *QuotaNetPayoutBatchUpdateOne {
	return NewQuotaNetPayoutBatchClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the QuotaNetPayoutBatch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *QuotaNetPayoutBatch) Unwrap() *QuotaNetPayoutBatch {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: QuotaNetPayoutBatch is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *QuotaNetPayoutBatch) String() string {
	var builder strings.Builder
	builder.WriteString("QuotaNetPayoutBatch(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("batch_key=")
	builder.WriteString(_m.BatchKey)
	builder.WriteString(", ")
	builder.WriteString("window_start=")
	builder.WriteString(_m.WindowStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("window_end=")
	builder.WriteString(_m.WindowEnd.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("network=")
	builder.WriteString(_m.Network)
	builder.WriteString(", ")
	builder.WriteString("total_token_flow=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTokenFlow))
	builder.WriteString(", ")
	builder.WriteString("total_amount_cxs=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalAmountCxs))
	builder.WriteString(", ")
	builder.WriteString("item_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ItemCount))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ApprovedBy; v != nil {
		builder.WriteString("approved_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// QuotaNetPayoutBatches is a parsable slice of QuotaNetPayoutBatch.
type QuotaNetPayoutBatches []*QuotaNetPayoutBatch
