// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/quotanetpayoutbatch"
)

// QuotaNetPayoutBatchUpdate is the builder for updating QuotaNetPayoutBatch entities.
type QuotaNetPayoutBatchUpdate struct {
	config
	hooks    []Hook
	mutation *QuotaNetPayoutBatchMutation
}

// Where appends a list predicates to the QuotaNetPayoutBatchUpdate builder.
func (_u *QuotaNetPayoutBatchUpdate) Where(ps ...predicate.QuotaNetPayoutBatch) *QuotaNetPayoutBatchUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaNetPayoutBatchUpdate) SetUpdatedAt(v time.Time) *QuotaNetPayoutBatchUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBatchKey sets the "batch_key" field.
func (_u *QuotaNetPayoutBatchUpdate) SetBatchKey(v string) *QuotaNetPayoutBatchUpdate {
	_u.mutation.SetBatchKey(v)
	return _u
}

// SetNillableBatchKey sets the "batch_key" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdate) SetNillableBatchKey(v *string) *QuotaNetPayoutBatchUpdate {
	if v != nil {
		_u.SetBatchKey(*v)
	}
	return _u
}

// SetWindowStart sets the "window_start" field.
func (_u *QuotaNetPayoutBatchUpdate) SetWindowStart(v time.Time) *QuotaNetPayoutBatchUpdate {
	_u.mutation.SetWindowStart(v)
	return _u
}

// SetNillableWindowStart sets the "window_start" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdate) SetNillableWindowStart(v *time.Time) *QuotaNetPayoutBatchUpdate {
	if v != nil {
		_u.SetWindowStart(*v)
	}
	return _u
}

// SetWindowEnd sets the "window_end" field.
func (_u *QuotaNetPayoutBatchUpdate) SetWindowEnd(v time.Time) *QuotaNetPayoutBatchUpdate {
	_u.mutation.SetWindowEnd(v)
	return _u
}

// SetNillableWindowEnd sets the "window_end" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdate) SetNillableWindowEnd(v *time.Time) *QuotaNetPayoutBatchUpdate {
	if v != nil {
		_u.SetWindowEnd(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaNetPayoutBatchUpdate) SetStatus(v string) *QuotaNetPayoutBatchUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdate) SetNillableStatus(v *string) *QuotaNetPayoutBatchUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNetwork sets the "network" field.
func (_u *QuotaNetPayoutBatchUpdate) SetNetwork(v string) *QuotaNetPayoutBatchUpdate {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdate) SetNillableNetwork(v *string) *QuotaNetPayoutBatchUpdate {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetTotalTokenFlow sets the "total_token_flow" field.
func (_u *QuotaNetPayoutBatchUpdate) SetTotalTokenFlow(v int64) *QuotaNetPayoutBatchUpdate {
	_u.mutation.ResetTotalTokenFlow()
	_u.mutation.SetTotalTokenFlow(v)
	return _u
}

// SetNillableTotalTokenFlow sets the "total_token_flow" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdate) SetNillableTotalTokenFlow(v *int64) *QuotaNetPayoutBatchUpdate {
	if v != nil {
		_u.SetTotalTokenFlow(*v)
	}
	return _u
}

// AddTotalTokenFlow adds value to the "total_token_flow" field.
func (_u *QuotaNetPayoutBatchUpdate) AddTotalTokenFlow(v int64) *QuotaNetPayoutBatchUpdate {
	_u.mutation.AddTotalTokenFlow(v)
	return _u
}

// SetTotalContributionUsd sets the "total_contribution_usd" field.
func (_u *QuotaNetPayoutBatchUpdate) SetTotalContributionUsd(v float64) *QuotaNetPayoutBatchUpdate {
	_u.mutation.ResetTotalContributionUsd()
	_u.mutation.SetTotalContributionUsd(v)
	return _u
}

// SetNillableTotalContributionUsd sets the "total_contribution_usd" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdate) SetNillableTotalContributionUsd(v *float64) *QuotaNetPayoutBatchUpdate {
	if v != nil {
		_u.SetTotalContributionUsd(*v)
	}
	return _u
}

// AddTotalContributionUsd adds value to the "total_contribution_usd" field.
func (_u *QuotaNetPayoutBatchUpdate) AddTotalContributionUsd(v float64) *QuotaNetPayoutBatchUpdate {
	_u.mutation.AddTotalContributionUsd(v)
	return _u
}

// SetTotalAmountCxs sets the "total_amount_cxs" field.
func (_u *QuotaNetPayoutBatchUpdate) SetTotalAmountCxs(v float64) *QuotaNetPayoutBatchUpdate {
	_u.mutation.ResetTotalAmountCxs()
	_u.mutation.SetTotalAmountCxs(v)
	return _u
}

// SetNillableTotalAmountCxs sets the "total_amount_cxs" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdate) SetNillableTotalAmountCxs(v *float64) *QuotaNetPayoutBatchUpdate {
	if v != nil {
		_u.SetTotalAmountCxs(*v)
	}
	return _u
}

// AddTotalAmountCxs adds value to the "total_amount_cxs" field.
func (_u *QuotaNetPayoutBatchUpdate) AddTotalAmountCxs(v float64) *QuotaNetPayoutBatchUpdate {
	_u.mutation.AddTotalAmountCxs(v)
	return _u
}

// SetItemCount sets the "item_count" field.
func (_u *QuotaNetPayoutBatchUpdate) SetItemCount(v int) *QuotaNetPayoutBatchUpdate {
	_u.mutation.ResetItemCount()
	_u.mutation.SetItemCount(v)
	return _u
}

// SetNillableItemCount sets the "item_count" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdate) SetNillableItemCount(v *int) *QuotaNetPayoutBatchUpdate {
	if v != nil {
		_u.SetItemCount(*v)
	}
	return _u
}

// AddItemCount adds value to the "item_count" field.
func (_u *QuotaNetPayoutBatchUpdate) AddItemCount(v int) *QuotaNetPayoutBatchUpdate {
	_u.mutation.AddItemCount(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *QuotaNetPayoutBatchUpdate) SetCreatedBy(v int64) *QuotaNetPayoutBatchUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdate) SetNillableCreatedBy(v *int64) *QuotaNetPayoutBatchUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *QuotaNetPayoutBatchUpdate) AddCreatedBy(v int64) *QuotaNetPayoutBatchUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *QuotaNetPayoutBatchUpdate) ClearCreatedBy() *QuotaNetPayoutBatchUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetApprovedBy sets the "approved_by" field.
func (_u *QuotaNetPayoutBatchUpdate) SetApprovedBy(v int64) *QuotaNetPayoutBatchUpdate {
	_u.mutation.ResetApprovedBy()
	_u.mutation.SetApprovedBy(v)
	return _u
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdate) SetNillableApprovedBy(v *int64) *QuotaNetPayoutBatchUpdate {
	if v != nil {
		_u.SetApprovedBy(*v)
	}
	return _u
}

// AddApprovedBy adds value to the "approved_by" field.
func (_u *QuotaNetPayoutBatchUpdate) AddApprovedBy(v int64) *QuotaNetPayoutBatchUpdate {
	_u.mutation.AddApprovedBy(v)
	return _u
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (_u *QuotaNetPayoutBatchUpdate) ClearApprovedBy() *QuotaNetPayoutBatchUpdate {
	_u.mutation.ClearApprovedBy()
	return _u
}

// Mutation returns the QuotaNetPayoutBatchMutation object of the builder.
func (_u *QuotaNetPayoutBatchUpdate) Mutation() *QuotaNetPayoutBatchMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuotaNetPayoutBatchUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaNetPayoutBatchUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuotaNetPayoutBatchUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaNetPayoutBatchUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaNetPayoutBatchUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotanetpayoutbatch.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaNetPayoutBatchUpdate) check() error {
	if v, ok := _u.mutation.BatchKey(); ok {
		if err := quotanetpayoutbatch.BatchKeyValidator(v); err != nil {
			return &ValidationError{Name: "batch_key", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutBatch.batch_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotanetpayoutbatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutBatch.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Network(); ok {
		if err := quotanetpayoutbatch.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutBatch.network": %w`, err)}
		}
	}
	return nil
}

func (_u *QuotaNetPayoutBatchUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotanetpayoutbatch.Table, quotanetpayoutbatch.Columns, sqlgraph.NewFieldSpec(quotanetpayoutbatch.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BatchKey(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldBatchKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.WindowStart(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldWindowStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WindowEnd(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldWindowEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalTokenFlow(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldTotalTokenFlow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokenFlow(); ok {
		_spec.AddField(quotanetpayoutbatch.FieldTotalTokenFlow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalContributionUsd(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldTotalContributionUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalContributionUsd(); ok {
		_spec.AddField(quotanetpayoutbatch.FieldTotalContributionUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalAmountCxs(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldTotalAmountCxs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmountCxs(); ok {
		_spec.AddField(quotanetpayoutbatch.FieldTotalAmountCxs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ItemCount(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldItemCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedItemCount(); ok {
		_spec.AddField(quotanetpayoutbatch.FieldItemCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(quotanetpayoutbatch.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(quotanetpayoutbatch.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ApprovedBy(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldApprovedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedApprovedBy(); ok {
		_spec.AddField(quotanetpayoutbatch.FieldApprovedBy, field.TypeInt64, value)
	}
	if _u.mutation.ApprovedByCleared() {
		_spec.ClearField(quotanetpayoutbatch.FieldApprovedBy, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotanetpayoutbatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuotaNetPayoutBatchUpdateOne is the builder for updating a single QuotaNetPayoutBatch entity.
type QuotaNetPayoutBatchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuotaNetPayoutBatchMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaNetPayoutBatchUpdateOne) SetUpdatedAt(v time.Time) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBatchKey sets the "batch_key" field.
func (_u *QuotaNetPayoutBatchUpdateOne) SetBatchKey(v string) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.SetBatchKey(v)
	return _u
}

// SetNillableBatchKey sets the "batch_key" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdateOne) SetNillableBatchKey(v *string) *QuotaNetPayoutBatchUpdateOne {
	if v != nil {
		_u.SetBatchKey(*v)
	}
	return _u
}

// SetWindowStart sets the "window_start" field.
func (_u *QuotaNetPayoutBatchUpdateOne) SetWindowStart(v time.Time) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.SetWindowStart(v)
	return _u
}

// SetNillableWindowStart sets the "window_start" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdateOne) SetNillableWindowStart(v *time.Time) *QuotaNetPayoutBatchUpdateOne {
	if v != nil {
		_u.SetWindowStart(*v)
	}
	return _u
}

// SetWindowEnd sets the "window_end" field.
func (_u *QuotaNetPayoutBatchUpdateOne) SetWindowEnd(v time.Time) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.SetWindowEnd(v)
	return _u
}

// SetNillableWindowEnd sets the "window_end" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdateOne) SetNillableWindowEnd(v *time.Time) *QuotaNetPayoutBatchUpdateOne {
	if v != nil {
		_u.SetWindowEnd(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaNetPayoutBatchUpdateOne) SetStatus(v string) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdateOne) SetNillableStatus(v *string) *QuotaNetPayoutBatchUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNetwork sets the "network" field.
func (_u *QuotaNetPayoutBatchUpdateOne) SetNetwork(v string) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdateOne) SetNillableNetwork(v *string) *QuotaNetPayoutBatchUpdateOne {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetTotalTokenFlow sets the "total_token_flow" field.
func (_u *QuotaNetPayoutBatchUpdateOne) SetTotalTokenFlow(v int64) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.ResetTotalTokenFlow()
	_u.mutation.SetTotalTokenFlow(v)
	return _u
}

// SetNillableTotalTokenFlow sets the "total_token_flow" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdateOne) SetNillableTotalTokenFlow(v *int64) *QuotaNetPayoutBatchUpdateOne {
	if v != nil {
		_u.SetTotalTokenFlow(*v)
	}
	return _u
}

// AddTotalTokenFlow adds value to the "total_token_flow" field.
func (_u *QuotaNetPayoutBatchUpdateOne) AddTotalTokenFlow(v int64) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.AddTotalTokenFlow(v)
	return _u
}

// SetTotalContributionUsd sets the "total_contribution_usd" field.
func (_u *QuotaNetPayoutBatchUpdateOne) SetTotalContributionUsd(v float64) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.ResetTotalContributionUsd()
	_u.mutation.SetTotalContributionUsd(v)
	return _u
}

// SetNillableTotalContributionUsd sets the "total_contribution_usd" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdateOne) SetNillableTotalContributionUsd(v *float64) *QuotaNetPayoutBatchUpdateOne {
	if v != nil {
		_u.SetTotalContributionUsd(*v)
	}
	return _u
}

// AddTotalContributionUsd adds value to the "total_contribution_usd" field.
func (_u *QuotaNetPayoutBatchUpdateOne) AddTotalContributionUsd(v float64) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.AddTotalContributionUsd(v)
	return _u
}

// SetTotalAmountCxs sets the "total_amount_cxs" field.
func (_u *QuotaNetPayoutBatchUpdateOne) SetTotalAmountCxs(v float64) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.ResetTotalAmountCxs()
	_u.mutation.SetTotalAmountCxs(v)
	return _u
}

// SetNillableTotalAmountCxs sets the "total_amount_cxs" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdateOne) SetNillableTotalAmountCxs(v *float64) *QuotaNetPayoutBatchUpdateOne {
	if v != nil {
		_u.SetTotalAmountCxs(*v)
	}
	return _u
}

// AddTotalAmountCxs adds value to the "total_amount_cxs" field.
func (_u *QuotaNetPayoutBatchUpdateOne) AddTotalAmountCxs(v float64) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.AddTotalAmountCxs(v)
	return _u
}

// SetItemCount sets the "item_count" field.
func (_u *QuotaNetPayoutBatchUpdateOne) SetItemCount(v int) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.ResetItemCount()
	_u.mutation.SetItemCount(v)
	return _u
}

// SetNillableItemCount sets the "item_count" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdateOne) SetNillableItemCount(v *int) *QuotaNetPayoutBatchUpdateOne {
	if v != nil {
		_u.SetItemCount(*v)
	}
	return _u
}

// AddItemCount adds value to the "item_count" field.
func (_u *QuotaNetPayoutBatchUpdateOne) AddItemCount(v int) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.AddItemCount(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *QuotaNetPayoutBatchUpdateOne) SetCreatedBy(v int64) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdateOne) SetNillableCreatedBy(v *int64) *QuotaNetPayoutBatchUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *QuotaNetPayoutBatchUpdateOne) AddCreatedBy(v int64) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *QuotaNetPayoutBatchUpdateOne) ClearCreatedBy() *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetApprovedBy sets the "approved_by" field.
func (_u *QuotaNetPayoutBatchUpdateOne) SetApprovedBy(v int64) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.ResetApprovedBy()
	_u.mutation.SetApprovedBy(v)
	return _u
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_u *QuotaNetPayoutBatchUpdateOne) SetNillableApprovedBy(v *int64) *QuotaNetPayoutBatchUpdateOne {
	if v != nil {
		_u.SetApprovedBy(*v)
	}
	return _u
}

// AddApprovedBy adds value to the "approved_by" field.
func (_u *QuotaNetPayoutBatchUpdateOne) AddApprovedBy(v int64) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.AddApprovedBy(v)
	return _u
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (_u *QuotaNetPayoutBatchUpdateOne) ClearApprovedBy() *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.ClearApprovedBy()
	return _u
}

// Mutation returns the QuotaNetPayoutBatchMutation object of the builder.
func (_u *QuotaNetPayoutBatchUpdateOne) Mutation() *QuotaNetPayoutBatchMutation {
	return _u.mutation
}

// Where appends a list predicates to the QuotaNetPayoutBatchUpdate builder.
func (_u *QuotaNetPayoutBatchUpdateOne) Where(ps ...predicate.QuotaNetPayoutBatch) *QuotaNetPayoutBatchUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuotaNetPayoutBatchUpdateOne) Select(field string, fields ...string) *QuotaNetPayoutBatchUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuotaNetPayoutBatch entity.
func (_u *QuotaNetPayoutBatchUpdateOne) Save(ctx context.Context) (*QuotaNetPayoutBatch, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaNetPayoutBatchUpdateOne) SaveX(ctx context.Context) *QuotaNetPayoutBatch {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuotaNetPayoutBatchUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaNetPayoutBatchUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaNetPayoutBatchUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotanetpayoutbatch.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaNetPayoutBatchUpdateOne) check() error {
	if v, ok := _u.mutation.BatchKey(); ok {
		if err := quotanetpayoutbatch.BatchKeyValidator(v); err != nil {
			return &ValidationError{Name: "batch_key", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutBatch.batch_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotanetpayoutbatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutBatch.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Network(); ok {
		if err := quotanetpayoutbatch.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutBatch.network": %w`, err)}
		}
	}
	return nil
}

func (_u *QuotaNetPayoutBatchUpdateOne) sqlSave(ctx context.Context) (_node *QuotaNetPayoutBatch, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotanetpayoutbatch.Table, quotanetpayoutbatch.Columns, sqlgraph.NewFieldSpec(quotanetpayoutbatch.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuotaNetPayoutBatch.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quotanetpayoutbatch.FieldID)
		for _, f := range fields {
			if !quotanetpayoutbatch.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quotanetpayoutbatch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BatchKey(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldBatchKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.WindowStart(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldWindowStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WindowEnd(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldWindowEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalTokenFlow(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldTotalTokenFlow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokenFlow(); ok {
		_spec.AddField(quotanetpayoutbatch.FieldTotalTokenFlow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalContributionUsd(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldTotalContributionUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalContributionUsd(); ok {
		_spec.AddField(quotanetpayoutbatch.FieldTotalContributionUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalAmountCxs(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldTotalAmountCxs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmountCxs(); ok {
		_spec.AddField(quotanetpayoutbatch.FieldTotalAmountCxs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ItemCount(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldItemCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedItemCount(); ok {
		_spec.AddField(quotanetpayoutbatch.FieldItemCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(quotanetpayoutbatch.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(quotanetpayoutbatch.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ApprovedBy(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldApprovedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedApprovedBy(); ok {
		_spec.AddField(quotanetpayoutbatch.FieldApprovedBy, field.TypeInt64, value)
	}
	if _u.mutation.ApprovedByCleared() {
		_spec.ClearField(quotanetpayoutbatch.FieldApprovedBy, field.TypeInt64)
	}
	_node = &QuotaNetPayoutBatch{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotanetpayoutbatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
