// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/quotanetpayoutitem"
)

// QuotaNetPayoutItemUpdate is the builder for updating QuotaNetPayoutItem entities.
type QuotaNetPayoutItemUpdate struct {
	config
	hooks    []Hook
	mutation *QuotaNetPayoutItemMutation
}

// Where appends a list predicates to the QuotaNetPayoutItemUpdate builder.
func (_u *QuotaNetPayoutItemUpdate) Where(ps ...predicate.QuotaNetPayoutItem) *QuotaNetPayoutItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaNetPayoutItemUpdate) SetUpdatedAt(v time.Time) *QuotaNetPayoutItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetItemKey sets the "item_key" field.
func (_u *QuotaNetPayoutItemUpdate) SetItemKey(v string) *QuotaNetPayoutItemUpdate {
	_u.mutation.SetItemKey(v)
	return _u
}

// SetNillableItemKey sets the "item_key" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdate) SetNillableItemKey(v *string) *QuotaNetPayoutItemUpdate {
	if v != nil {
		_u.SetItemKey(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *QuotaNetPayoutItemUpdate) SetBatchID(v int64) *QuotaNetPayoutItemUpdate {
	_u.mutation.ResetBatchID()
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdate) SetNillableBatchID(v *int64) *QuotaNetPayoutItemUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// AddBatchID adds value to the "batch_id" field.
func (_u *QuotaNetPayoutItemUpdate) AddBatchID(v int64) *QuotaNetPayoutItemUpdate {
	_u.mutation.AddBatchID(v)
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *QuotaNetPayoutItemUpdate) SetNodeID(v int64) *QuotaNetPayoutItemUpdate {
	_u.mutation.ResetNodeID()
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdate) SetNillableNodeID(v *int64) *QuotaNetPayoutItemUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// AddNodeID adds value to the "node_id" field.
func (_u *QuotaNetPayoutItemUpdate) AddNodeID(v int64) *QuotaNetPayoutItemUpdate {
	_u.mutation.AddNodeID(v)
	return _u
}

// ClearNodeID clears the value of the "node_id" field.
func (_u *QuotaNetPayoutItemUpdate) ClearNodeID() *QuotaNetPayoutItemUpdate {
	_u.mutation.ClearNodeID()
	return _u
}

// SetWalletAddress sets the "wallet_address" field.
func (_u *QuotaNetPayoutItemUpdate) SetWalletAddress(v string) *QuotaNetPayoutItemUpdate {
	_u.mutation.SetWalletAddress(v)
	return _u
}

// SetNillableWalletAddress sets the "wallet_address" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdate) SetNillableWalletAddress(v *string) *QuotaNetPayoutItemUpdate {
	if v != nil {
		_u.SetWalletAddress(*v)
	}
	return _u
}

// SetTokenFlow sets the "token_flow" field.
func (_u *QuotaNetPayoutItemUpdate) SetTokenFlow(v int64) *QuotaNetPayoutItemUpdate {
	_u.mutation.ResetTokenFlow()
	_u.mutation.SetTokenFlow(v)
	return _u
}

// SetNillableTokenFlow sets the "token_flow" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdate) SetNillableTokenFlow(v *int64) *QuotaNetPayoutItemUpdate {
	if v != nil {
		_u.SetTokenFlow(*v)
	}
	return _u
}

// AddTokenFlow adds value to the "token_flow" field.
func (_u *QuotaNetPayoutItemUpdate) AddTokenFlow(v int64) *QuotaNetPayoutItemUpdate {
	_u.mutation.AddTokenFlow(v)
	return _u
}

// SetContributionUsd sets the "contribution_usd" field.
func (_u *QuotaNetPayoutItemUpdate) SetContributionUsd(v float64) *QuotaNetPayoutItemUpdate {
	_u.mutation.ResetContributionUsd()
	_u.mutation.SetContributionUsd(v)
	return _u
}

// SetNillableContributionUsd sets the "contribution_usd" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdate) SetNillableContributionUsd(v *float64) *QuotaNetPayoutItemUpdate {
	if v != nil {
		_u.SetContributionUsd(*v)
	}
	return _u
}

// AddContributionUsd adds value to the "contribution_usd" field.
func (_u *QuotaNetPayoutItemUpdate) AddContributionUsd(v float64) *QuotaNetPayoutItemUpdate {
	_u.mutation.AddContributionUsd(v)
	return _u
}

// SetAmountCxs sets the "amount_cxs" field.
func (_u *QuotaNetPayoutItemUpdate) SetAmountCxs(v float64) *QuotaNetPayoutItemUpdate {
	_u.mutation.ResetAmountCxs()
	_u.mutation.SetAmountCxs(v)
	return _u
}

// SetNillableAmountCxs sets the "amount_cxs" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdate) SetNillableAmountCxs(v *float64) *QuotaNetPayoutItemUpdate {
	if v != nil {
		_u.SetAmountCxs(*v)
	}
	return _u
}

// AddAmountCxs adds value to the "amount_cxs" field.
func (_u *QuotaNetPayoutItemUpdate) AddAmountCxs(v float64) *QuotaNetPayoutItemUpdate {
	_u.mutation.AddAmountCxs(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaNetPayoutItemUpdate) SetStatus(v string) *QuotaNetPayoutItemUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdate) SetNillableStatus(v *string) *QuotaNetPayoutItemUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *QuotaNetPayoutItemUpdate) SetTxHash(v string) *QuotaNetPayoutItemUpdate {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdate) SetNillableTxHash(v *string) *QuotaNetPayoutItemUpdate {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// ClearTxHash clears the value of the "tx_hash" field.
func (_u *QuotaNetPayoutItemUpdate) ClearTxHash() *QuotaNetPayoutItemUpdate {
	_u.mutation.ClearTxHash()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *QuotaNetPayoutItemUpdate) SetErrorMessage(v string) *QuotaNetPayoutItemUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdate) SetNillableErrorMessage(v *string) *QuotaNetPayoutItemUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *QuotaNetPayoutItemUpdate) ClearErrorMessage() *QuotaNetPayoutItemUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetFinalizedAt sets the "finalized_at" field.
func (_u *QuotaNetPayoutItemUpdate) SetFinalizedAt(v time.Time) *QuotaNetPayoutItemUpdate {
	_u.mutation.SetFinalizedAt(v)
	return _u
}

// SetNillableFinalizedAt sets the "finalized_at" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdate) SetNillableFinalizedAt(v *time.Time) *QuotaNetPayoutItemUpdate {
	if v != nil {
		_u.SetFinalizedAt(*v)
	}
	return _u
}

// ClearFinalizedAt clears the value of the "finalized_at" field.
func (_u *QuotaNetPayoutItemUpdate) ClearFinalizedAt() *QuotaNetPayoutItemUpdate {
	_u.mutation.ClearFinalizedAt()
	return _u
}

// Mutation returns the QuotaNetPayoutItemMutation object of the builder.
func (_u *QuotaNetPayoutItemUpdate) Mutation() *QuotaNetPayoutItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuotaNetPayoutItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaNetPayoutItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuotaNetPayoutItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaNetPayoutItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaNetPayoutItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotanetpayoutitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaNetPayoutItemUpdate) check() error {
	if v, ok := _u.mutation.ItemKey(); ok {
		if err := quotanetpayoutitem.ItemKeyValidator(v); err != nil {
			return &ValidationError{Name: "item_key", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutItem.item_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WalletAddress(); ok {
		if err := quotanetpayoutitem.WalletAddressValidator(v); err != nil {
			return &ValidationError{Name: "wallet_address", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutItem.wallet_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotanetpayoutitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutItem.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TxHash(); ok {
		if err := quotanetpayoutitem.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutItem.tx_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *QuotaNetPayoutItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotanetpayoutitem.Table, quotanetpayoutitem.Columns, sqlgraph.NewFieldSpec(quotanetpayoutitem.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotanetpayoutitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ItemKey(); ok {
		_spec.SetField(quotanetpayoutitem.FieldItemKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(quotanetpayoutitem.FieldBatchID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBatchID(); ok {
		_spec.AddField(quotanetpayoutitem.FieldBatchID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(quotanetpayoutitem.FieldNodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNodeID(); ok {
		_spec.AddField(quotanetpayoutitem.FieldNodeID, field.TypeInt64, value)
	}
	if _u.mutation.NodeIDCleared() {
		_spec.ClearField(quotanetpayoutitem.FieldNodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.WalletAddress(); ok {
		_spec.SetField(quotanetpayoutitem.FieldWalletAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenFlow(); ok {
		_spec.SetField(quotanetpayoutitem.FieldTokenFlow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokenFlow(); ok {
		_spec.AddField(quotanetpayoutitem.FieldTokenFlow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ContributionUsd(); ok {
		_spec.SetField(quotanetpayoutitem.FieldContributionUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedContributionUsd(); ok {
		_spec.AddField(quotanetpayoutitem.FieldContributionUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountCxs(); ok {
		_spec.SetField(quotanetpayoutitem.FieldAmountCxs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCxs(); ok {
		_spec.AddField(quotanetpayoutitem.FieldAmountCxs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotanetpayoutitem.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(quotanetpayoutitem.FieldTxHash, field.TypeString, value)
	}
	if _u.mutation.TxHashCleared() {
		_spec.ClearField(quotanetpayoutitem.FieldTxHash, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(quotanetpayoutitem.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(quotanetpayoutitem.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.FinalizedAt(); ok {
		_spec.SetField(quotanetpayoutitem.FieldFinalizedAt, field.TypeTime, value)
	}
	if _u.mutation.FinalizedAtCleared() {
		_spec.ClearField(quotanetpayoutitem.FieldFinalizedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotanetpayoutitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuotaNetPayoutItemUpdateOne is the builder for updating a single QuotaNetPayoutItem entity.
type QuotaNetPayoutItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuotaNetPayoutItemMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaNetPayoutItemUpdateOne) SetUpdatedAt(v time.Time) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetItemKey sets the "item_key" field.
func (_u *QuotaNetPayoutItemUpdateOne) SetItemKey(v string) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.SetItemKey(v)
	return _u
}

// SetNillableItemKey sets the "item_key" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdateOne) SetNillableItemKey(v *string) *QuotaNetPayoutItemUpdateOne {
	if v != nil {
		_u.SetItemKey(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *QuotaNetPayoutItemUpdateOne) SetBatchID(v int64) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.ResetBatchID()
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdateOne) SetNillableBatchID(v *int64) *QuotaNetPayoutItemUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// AddBatchID adds value to the "batch_id" field.
func (_u *QuotaNetPayoutItemUpdateOne) AddBatchID(v int64) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.AddBatchID(v)
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *QuotaNetPayoutItemUpdateOne) SetNodeID(v int64) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.ResetNodeID()
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdateOne) SetNillableNodeID(v *int64) *QuotaNetPayoutItemUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// AddNodeID adds value to the "node_id" field.
func (_u *QuotaNetPayoutItemUpdateOne) AddNodeID(v int64) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.AddNodeID(v)
	return _u
}

// ClearNodeID clears the value of the "node_id" field.
func (_u *QuotaNetPayoutItemUpdateOne) ClearNodeID() *QuotaNetPayoutItemUpdateOne {
	_u.mutation.ClearNodeID()
	return _u
}

// SetWalletAddress sets the "wallet_address" field.
func (_u *QuotaNetPayoutItemUpdateOne) SetWalletAddress(v string) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.SetWalletAddress(v)
	return _u
}

// SetNillableWalletAddress sets the "wallet_address" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdateOne) SetNillableWalletAddress(v *string) *QuotaNetPayoutItemUpdateOne {
	if v != nil {
		_u.SetWalletAddress(*v)
	}
	return _u
}

// SetTokenFlow sets the "token_flow" field.
func (_u *QuotaNetPayoutItemUpdateOne) SetTokenFlow(v int64) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.ResetTokenFlow()
	_u.mutation.SetTokenFlow(v)
	return _u
}

// SetNillableTokenFlow sets the "token_flow" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdateOne) SetNillableTokenFlow(v *int64) *QuotaNetPayoutItemUpdateOne {
	if v != nil {
		_u.SetTokenFlow(*v)
	}
	return _u
}

// AddTokenFlow adds value to the "token_flow" field.
func (_u *QuotaNetPayoutItemUpdateOne) AddTokenFlow(v int64) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.AddTokenFlow(v)
	return _u
}

// SetContributionUsd sets the "contribution_usd" field.
func (_u *QuotaNetPayoutItemUpdateOne) SetContributionUsd(v float64) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.ResetContributionUsd()
	_u.mutation.SetContributionUsd(v)
	return _u
}

// SetNillableContributionUsd sets the "contribution_usd" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdateOne) SetNillableContributionUsd(v *float64) *QuotaNetPayoutItemUpdateOne {
	if v != nil {
		_u.SetContributionUsd(*v)
	}
	return _u
}

// AddContributionUsd adds value to the "contribution_usd" field.
func (_u *QuotaNetPayoutItemUpdateOne) AddContributionUsd(v float64) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.AddContributionUsd(v)
	return _u
}

// SetAmountCxs sets the "amount_cxs" field.
func (_u *QuotaNetPayoutItemUpdateOne) SetAmountCxs(v float64) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.ResetAmountCxs()
	_u.mutation.SetAmountCxs(v)
	return _u
}

// SetNillableAmountCxs sets the "amount_cxs" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdateOne) SetNillableAmountCxs(v *float64) *QuotaNetPayoutItemUpdateOne {
	if v != nil {
		_u.SetAmountCxs(*v)
	}
	return _u
}

// AddAmountCxs adds value to the "amount_cxs" field.
func (_u *QuotaNetPayoutItemUpdateOne) AddAmountCxs(v float64) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.AddAmountCxs(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaNetPayoutItemUpdateOne) SetStatus(v string) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdateOne) SetNillableStatus(v *string) *QuotaNetPayoutItemUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *QuotaNetPayoutItemUpdateOne) SetTxHash(v string) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdateOne) SetNillableTxHash(v *string) *QuotaNetPayoutItemUpdateOne {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// ClearTxHash clears the value of the "tx_hash" field.
func (_u *QuotaNetPayoutItemUpdateOne) ClearTxHash() *QuotaNetPayoutItemUpdateOne {
	_u.mutation.ClearTxHash()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *QuotaNetPayoutItemUpdateOne) SetErrorMessage(v string) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdateOne) SetNillableErrorMessage(v *string) *QuotaNetPayoutItemUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *QuotaNetPayoutItemUpdateOne) ClearErrorMessage() *QuotaNetPayoutItemUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetFinalizedAt sets the "finalized_at" field.
func (_u *QuotaNetPayoutItemUpdateOne) SetFinalizedAt(v time.Time) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.SetFinalizedAt(v)
	return _u
}

// SetNillableFinalizedAt sets the "finalized_at" field if the given value is not nil.
func (_u *QuotaNetPayoutItemUpdateOne) SetNillableFinalizedAt(v *time.Time) *QuotaNetPayoutItemUpdateOne {
	if v != nil {
		_u.SetFinalizedAt(*v)
	}
	return _u
}

// ClearFinalizedAt clears the value of the "finalized_at" field.
func (_u *QuotaNetPayoutItemUpdateOne) ClearFinalizedAt() *QuotaNetPayoutItemUpdateOne {
	_u.mutation.ClearFinalizedAt()
	return _u
}

// Mutation returns the QuotaNetPayoutItemMutation object of the builder.
func (_u *QuotaNetPayoutItemUpdateOne) Mutation() *QuotaNetPayoutItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the QuotaNetPayoutItemUpdate builder.
func (_u *QuotaNetPayoutItemUpdateOne) Where(ps ...predicate.QuotaNetPayoutItem) *QuotaNetPayoutItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuotaNetPayoutItemUpdateOne) Select(field string, fields ...string) *QuotaNetPayoutItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuotaNetPayoutItem entity.
func (_u *QuotaNetPayoutItemUpdateOne) Save(ctx context.Context) (*QuotaNetPayoutItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaNetPayoutItemUpdateOne) SaveX(ctx context.Context) *QuotaNetPayoutItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuotaNetPayoutItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaNetPayoutItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaNetPayoutItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotanetpayoutitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaNetPayoutItemUpdateOne) check() error {
	if v, ok := _u.mutation.ItemKey(); ok {
		if err := quotanetpayoutitem.ItemKeyValidator(v); err != nil {
			return &ValidationError{Name: "item_key", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutItem.item_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WalletAddress(); ok {
		if err := quotanetpayoutitem.WalletAddressValidator(v); err != nil {
			return &ValidationError{Name: "wallet_address", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutItem.wallet_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotanetpayoutitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutItem.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TxHash(); ok {
		if err := quotanetpayoutitem.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutItem.tx_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *QuotaNetPayoutItemUpdateOne) sqlSave(ctx context.Context) (_node *QuotaNetPayoutItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotanetpayoutitem.Table, quotanetpayoutitem.Columns, sqlgraph.NewFieldSpec(quotanetpayoutitem.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuotaNetPayoutItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quotanetpayoutitem.FieldID)
		for _, f := range fields {
			if !quotanetpayoutitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quotanetpayoutitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotanetpayoutitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ItemKey(); ok {
		_spec.SetField(quotanetpayoutitem.FieldItemKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(quotanetpayoutitem.FieldBatchID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBatchID(); ok {
		_spec.AddField(quotanetpayoutitem.FieldBatchID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(quotanetpayoutitem.FieldNodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNodeID(); ok {
		_spec.AddField(quotanetpayoutitem.FieldNodeID, field.TypeInt64, value)
	}
	if _u.mutation.NodeIDCleared() {
		_spec.ClearField(quotanetpayoutitem.FieldNodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.WalletAddress(); ok {
		_spec.SetField(quotanetpayoutitem.FieldWalletAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenFlow(); ok {
		_spec.SetField(quotanetpayoutitem.FieldTokenFlow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokenFlow(); ok {
		_spec.AddField(quotanetpayoutitem.FieldTokenFlow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ContributionUsd(); ok {
		_spec.SetField(quotanetpayoutitem.FieldContributionUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedContributionUsd(); ok {
		_spec.AddField(quotanetpayoutitem.FieldContributionUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountCxs(); ok {
		_spec.SetField(quotanetpayoutitem.FieldAmountCxs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCxs(); ok {
		_spec.AddField(quotanetpayoutitem.FieldAmountCxs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotanetpayoutitem.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(quotanetpayoutitem.FieldTxHash, field.TypeString, value)
	}
	if _u.mutation.TxHashCleared() {
		_spec.ClearField(quotanetpayoutitem.FieldTxHash, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(quotanetpayoutitem.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(quotanetpayoutitem.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.FinalizedAt(); ok {
		_spec.SetField(quotanetpayoutitem.FieldFinalizedAt, field.TypeTime, value)
	}
	if _u.mutation.FinalizedAtCleared() {
		_spec.ClearField(quotanetpayoutitem.FieldFinalizedAt, field.TypeTime)
	}
	_node = &QuotaNetPayoutItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotanetpayoutitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
