// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/quotanetpayoutbatch"
)

// QuotaNetPayoutBatchCreate is the builder for creating a QuotaNetPayoutBatch entity.
type QuotaNetPayoutBatchCreate struct {
	config
	mutation *QuotaNetPayoutBatchMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuotaNetPayoutBatchCreate) SetCreatedAt(v time.Time) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuotaNetPayoutBatchCreate) SetNillableCreatedAt(v *time.Time) *QuotaNetPayoutBatchCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QuotaNetPayoutBatchCreate) SetUpdatedAt(v time.Time) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QuotaNetPayoutBatchCreate) SetNillableUpdatedAt(v *time.Time) *QuotaNetPayoutBatchCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetBatchKey sets the "batch_key" field.
func (_c *QuotaNetPayoutBatchCreate) SetBatchKey(v string) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetBatchKey(v)
	return _c
}

// SetWindowStart sets the "window_start" field.
func (_c *QuotaNetPayoutBatchCreate) SetWindowStart(v time.Time) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetWindowStart(v)
	return _c
}

// SetWindowEnd sets the "window_end" field.
func (_c *QuotaNetPayoutBatchCreate) SetWindowEnd(v time.Time) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetWindowEnd(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *QuotaNetPayoutBatchCreate) SetStatus(v string) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *QuotaNetPayoutBatchCreate) SetNillableStatus(v *string) *QuotaNetPayoutBatchCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNetwork sets the "network" field.
func (_c *QuotaNetPayoutBatchCreate) SetNetwork(v string) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetNetwork(v)
	return _c
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_c *QuotaNetPayoutBatchCreate) SetNillableNetwork(v *string) *QuotaNetPayoutBatchCreate {
	if v != nil {
		_c.SetNetwork(*v)
	}
	return _c
}

// SetTotalTokenFlow sets the "total_token_flow" field.
func (_c *QuotaNetPayoutBatchCreate) SetTotalTokenFlow(v int64) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetTotalTokenFlow(v)
	return _c
}

// SetNillableTotalTokenFlow sets the "total_token_flow" field if the given value is not nil.
func (_c *QuotaNetPayoutBatchCreate) SetNillableTotalTokenFlow(v *int64) *QuotaNetPayoutBatchCreate {
	if v != nil {
		_c.SetTotalTokenFlow(*v)
	}
	return _c
}

// SetTotalContributionUsd sets the "total_contribution_usd" field.
func (_c *QuotaNetPayoutBatchCreate) SetTotalContributionUsd(v float64) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetTotalContributionUsd(v)
	return _c
}

// SetNillableTotalContributionUsd sets the "total_contribution_usd" field if the given value is not nil.
func (_c *QuotaNetPayoutBatchCreate) SetNillableTotalContributionUsd(v *float64) *QuotaNetPayoutBatchCreate {
	if v != nil {
		_c.SetTotalContributionUsd(*v)
	}
	return _c
}

// SetTotalAmountCxs sets the "total_amount_cxs" field.
func (_c *QuotaNetPayoutBatchCreate) SetTotalAmountCxs(v float64) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetTotalAmountCxs(v)
	return _c
}

// SetNillableTotalAmountCxs sets the "total_amount_cxs" field if the given value is not nil.
func (_c *QuotaNetPayoutBatchCreate) SetNillableTotalAmountCxs(v *float64) *QuotaNetPayoutBatchCreate {
	if v != nil {
		_c.SetTotalAmountCxs(*v)
	}
	return _c
}

// SetItemCount sets the "item_count" field.
func (_c *QuotaNetPayoutBatchCreate) SetItemCount(v int) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetItemCount(v)
	return _c
}

// SetNillableItemCount sets the "item_count" field if the given value is not nil.
func (_c *QuotaNetPayoutBatchCreate) SetNillableItemCount(v *int) *QuotaNetPayoutBatchCreate {
	if v != nil {
		_c.SetItemCount(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *QuotaNetPayoutBatchCreate) SetCreatedBy(v int64) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *QuotaNetPayoutBatchCreate) SetNillableCreatedBy(v *int64) *QuotaNetPayoutBatchCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetApprovedBy sets the "approved_by" field.
func (_c *QuotaNetPayoutBatchCreate) SetApprovedBy(v int64) *QuotaNetPayoutBatchCreate {
	_c.mutation.SetApprovedBy(v)
	return _c
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_c *QuotaNetPayoutBatchCreate) SetNillableApprovedBy(v *int64) *QuotaNetPayoutBatchCreate {
	if v != nil {
		_c.SetApprovedBy(*v)
	}
	return _c
}

// Mutation returns the QuotaNetPayoutBatchMutation object of the builder.
func (_c *QuotaNetPayoutBatchCreate) Mutation() *QuotaNetPayoutBatchMutation {
	return _c.mutation
}

// Save creates the QuotaNetPayoutBatch in the database.
func (_c *QuotaNetPayoutBatchCreate) Save(ctx context.Context) (*QuotaNetPayoutBatch, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuotaNetPayoutBatchCreate) SaveX(ctx context.Context) *QuotaNetPayoutBatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuotaNetPayoutBatchCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuotaNetPayoutBatchCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuotaNetPayoutBatchCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quotanetpayoutbatch.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := quotanetpayoutbatch.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := quotanetpayoutbatch.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Network(); !ok {
		v := quotanetpayoutbatch.DefaultNetwork
		_c.mutation.SetNetwork(v)
	}
	if _, ok := _c.mutation.TotalTokenFlow(); !ok {
		v := quotanetpayoutbatch.DefaultTotalTokenFlow
		_c.mutation.SetTotalTokenFlow(v)
	}
	if _, ok := _c.mutation.TotalContributionUsd(); !ok {
		v := quotanetpayoutbatch.DefaultTotalContributionUsd
		_c.mutation.SetTotalContributionUsd(v)
	}
	if _, ok := _c.mutation.TotalAmountCxs(); !ok {
		v := quotanetpayoutbatch.DefaultTotalAmountCxs
		_c.mutation.SetTotalAmountCxs(v)
	}
	if _, ok := _c.mutation.ItemCount(); !ok {
		v := quotanetpayoutbatch.DefaultItemCount
		_c.mutation.SetItemCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuotaNetPayoutBatchCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QuotaNetPayoutBatch.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "QuotaNetPayoutBatch.updated_at"`)}
	}
	if _, ok := _c.mutation.BatchKey(); !ok {
		return &ValidationError{Name: "batch_key", err: errors.New(`ent: missing required field "QuotaNetPayoutBatch.batch_key"`)}
	}
	if v, ok := _c.mutation.BatchKey(); ok {
		if err := quotanetpayoutbatch.BatchKeyValidator(v); err != nil {
			return &ValidationError{Name: "batch_key", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutBatch.batch_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WindowStart(); !ok {
		return &ValidationError{Name: "window_start", err: errors.New(`ent: missing required field "QuotaNetPayoutBatch.window_start"`)}
	}
	if _, ok := _c.mutation.WindowEnd(); !ok {
		return &ValidationError{Name: "window_end", err: errors.New(`ent: missing required field "QuotaNetPayoutBatch.window_end"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "QuotaNetPayoutBatch.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := quotanetpayoutbatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutBatch.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "QuotaNetPayoutBatch.network"`)}
	}
	if v, ok := _c.mutation.Network(); ok {
		if err := quotanetpayoutbatch.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutBatch.network": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalTokenFlow(); !ok {
		return &ValidationError{Name: "total_token_flow", err: errors.New(`ent: missing required field "QuotaNetPayoutBatch.total_token_flow"`)}
	}
	if _, ok := _c.mutation.TotalContributionUsd(); !ok {
		return &ValidationError{Name: "total_contribution_usd", err: errors.New(`ent: missing required field "QuotaNetPayoutBatch.total_contribution_usd"`)}
	}
	if _, ok := _c.mutation.TotalAmountCxs(); !ok {
		return &ValidationError{Name: "total_amount_cxs", err: errors.New(`ent: missing required field "QuotaNetPayoutBatch.total_amount_cxs"`)}
	}
	if _, ok := _c.mutation.ItemCount(); !ok {
		return &ValidationError{Name: "item_count", err: errors.New(`ent: missing required field "QuotaNetPayoutBatch.item_count"`)}
	}
	return nil
}

func (_c *QuotaNetPayoutBatchCreate) sqlSave(ctx context.Context) (*QuotaNetPayoutBatch, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuotaNetPayoutBatchCreate) createSpec() (*QuotaNetPayoutBatch, *sqlgraph.CreateSpec) {
	var (
		_node = &QuotaNetPayoutBatch{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quotanetpayoutbatch.Table, sqlgraph.NewFieldSpec(quotanetpayoutbatch.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.BatchKey(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldBatchKey, field.TypeString, value)
		_node.BatchKey = value
	}
	if value, ok := _c.mutation.WindowStart(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldWindowStart, field.TypeTime, value)
		_node.WindowStart = value
	}
	if value, ok := _c.mutation.WindowEnd(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldWindowEnd, field.TypeTime, value)
		_node.WindowEnd = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Network(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldNetwork, field.TypeString, value)
		_node.Network = value
	}
	if value, ok := _c.mutation.TotalTokenFlow(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldTotalTokenFlow, field.TypeInt64, value)
		_node.TotalTokenFlow = value
	}
	if value, ok := _c.mutation.TotalContributionUsd(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldTotalContributionUsd, field.TypeFloat64, value)
		_node.TotalContributionUsd = value
	}
	if value, ok := _c.mutation.TotalAmountCxs(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldTotalAmountCxs, field.TypeFloat64, value)
		_node.TotalAmountCxs = value
	}
	if value, ok := _c.mutation.ItemCount(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldItemCount, field.TypeInt, value)
		_node.ItemCount = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.ApprovedBy(); ok {
		_spec.SetField(quotanetpayoutbatch.FieldApprovedBy, field.TypeInt64, value)
		_node.ApprovedBy = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QuotaNetPayoutBatch.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuotaNetPayoutBatchUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *QuotaNetPayoutBatchCreate) OnConflict(opts ...sql.ConflictOption) *QuotaNetPayoutBatchUpsertOne {
	_c.conflict = opts
	return &QuotaNetPayoutBatchUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QuotaNetPayoutBatch.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuotaNetPayoutBatchCreate) OnConflictColumns(columns ...string) *QuotaNetPayoutBatchUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuotaNetPayoutBatchUpsertOne{
		create: _c,
	}
}

type (
	// QuotaNetPayoutBatchUpsertOne is the builder for "upsert"-ing
	//  one QuotaNetPayoutBatch node.
	QuotaNetPayoutBatchUpsertOne struct {
		create *QuotaNetPayoutBatchCreate
	}

	// QuotaNetPayoutBatchUpsert is the "OnConflict" setter.
	QuotaNetPayoutBatchUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *QuotaNetPayoutBatchUpsert) SetUpdatedAt(v time.Time) *QuotaNetPayoutBatchUpsert {
	u.Set(quotanetpayoutbatch.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsert) UpdateUpdatedAt() *QuotaNetPayoutBatchUpsert {
	u.SetExcluded(quotanetpayoutbatch.FieldUpdatedAt)
	return u
}

// SetBatchKey sets the "batch_key" field.
func (u *QuotaNetPayoutBatchUpsert) SetBatchKey(v string) *QuotaNetPayoutBatchUpsert {
	u.Set(quotanetpayoutbatch.FieldBatchKey, v)
	return u
}

// UpdateBatchKey sets the "batch_key" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsert) UpdateBatchKey() *QuotaNetPayoutBatchUpsert {
	u.SetExcluded(quotanetpayoutbatch.FieldBatchKey)
	return u
}

// SetWindowStart sets the "window_start" field.
func (u *QuotaNetPayoutBatchUpsert) SetWindowStart(v time.Time) *QuotaNetPayoutBatchUpsert {
	u.Set(quotanetpayoutbatch.FieldWindowStart, v)
	return u
}

// UpdateWindowStart sets the "window_start" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsert) UpdateWindowStart() *QuotaNetPayoutBatchUpsert {
	u.SetExcluded(quotanetpayoutbatch.FieldWindowStart)
	return u
}

// SetWindowEnd sets the "window_end" field.
func (u *QuotaNetPayoutBatchUpsert) SetWindowEnd(v time.Time) *QuotaNetPayoutBatchUpsert {
	u.Set(quotanetpayoutbatch.FieldWindowEnd, v)
	return u
}

// UpdateWindowEnd sets the "window_end" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsert) UpdateWindowEnd() *QuotaNetPayoutBatchUpsert {
	u.SetExcluded(quotanetpayoutbatch.FieldWindowEnd)
	return u
}

// SetStatus sets the "status" field.
func (u *QuotaNetPayoutBatchUpsert) SetStatus(v string) *QuotaNetPayoutBatchUpsert {
	u.Set(quotanetpayoutbatch.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsert) UpdateStatus() *QuotaNetPayoutBatchUpsert {
	u.SetExcluded(quotanetpayoutbatch.FieldStatus)
	return u
}

// SetNetwork sets the "network" field.
func (u *QuotaNetPayoutBatchUpsert) SetNetwork(v string) *QuotaNetPayoutBatchUpsert {
	u.Set(quotanetpayoutbatch.FieldNetwork, v)
	return u
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsert) UpdateNetwork() *QuotaNetPayoutBatchUpsert {
	u.SetExcluded(quotanetpayoutbatch.FieldNetwork)
	return u
}

// SetTotalTokenFlow sets the "total_token_flow" field.
func (u *QuotaNetPayoutBatchUpsert) SetTotalTokenFlow(v int64) *QuotaNetPayoutBatchUpsert {
	u.Set(quotanetpayoutbatch.FieldTotalTokenFlow, v)
	return u
}

// UpdateTotalTokenFlow sets the "total_token_flow" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsert) UpdateTotalTokenFlow() *QuotaNetPayoutBatchUpsert {
	u.SetExcluded(quotanetpayoutbatch.FieldTotalTokenFlow)
	return u
}

// AddTotalTokenFlow adds v to the "total_token_flow" field.
func (u *QuotaNetPayoutBatchUpsert) AddTotalTokenFlow(v int64) *QuotaNetPayoutBatchUpsert {
	u.Add(quotanetpayoutbatch.FieldTotalTokenFlow, v)
	return u
}

// SetTotalContributionUsd sets the "total_contribution_usd" field.
func (u *QuotaNetPayoutBatchUpsert) SetTotalContributionUsd(v float64) *QuotaNetPayoutBatchUpsert {
	u.Set(quotanetpayoutbatch.FieldTotalContributionUsd, v)
	return u
}

// UpdateTotalContributionUsd sets the "total_contribution_usd" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsert) UpdateTotalContributionUsd() *QuotaNetPayoutBatchUpsert {
	u.SetExcluded(quotanetpayoutbatch.FieldTotalContributionUsd)
	return u
}

// AddTotalContributionUsd adds v to the "total_contribution_usd" field.
func (u *QuotaNetPayoutBatchUpsert) AddTotalContributionUsd(v float64) *QuotaNetPayoutBatchUpsert {
	u.Add(quotanetpayoutbatch.FieldTotalContributionUsd, v)
	return u
}

// SetTotalAmountCxs sets the "total_amount_cxs" field.
func (u *QuotaNetPayoutBatchUpsert) SetTotalAmountCxs(v float64) *QuotaNetPayoutBatchUpsert {
	u.Set(quotanetpayoutbatch.FieldTotalAmountCxs, v)
	return u
}

// UpdateTotalAmountCxs sets the "total_amount_cxs" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsert) UpdateTotalAmountCxs() *QuotaNetPayoutBatchUpsert {
	u.SetExcluded(quotanetpayoutbatch.FieldTotalAmountCxs)
	return u
}

// AddTotalAmountCxs adds v to the "total_amount_cxs" field.
func (u *QuotaNetPayoutBatchUpsert) AddTotalAmountCxs(v float64) *QuotaNetPayoutBatchUpsert {
	u.Add(quotanetpayoutbatch.FieldTotalAmountCxs, v)
	return u
}

// SetItemCount sets the "item_count" field.
func (u *QuotaNetPayoutBatchUpsert) SetItemCount(v int) *QuotaNetPayoutBatchUpsert {
	u.Set(quotanetpayoutbatch.FieldItemCount, v)
	return u
}

// UpdateItemCount sets the "item_count" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsert) UpdateItemCount() *QuotaNetPayoutBatchUpsert {
	u.SetExcluded(quotanetpayoutbatch.FieldItemCount)
	return u
}

// AddItemCount adds v to the "item_count" field.
func (u *QuotaNetPayoutBatchUpsert) AddItemCount(v int) *QuotaNetPayoutBatchUpsert {
	u.Add(quotanetpayoutbatch.FieldItemCount, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *QuotaNetPayoutBatchUpsert) SetCreatedBy(v int64) *QuotaNetPayoutBatchUpsert {
	u.Set(quotanetpayoutbatch.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsert) UpdateCreatedBy() *QuotaNetPayoutBatchUpsert {
	u.SetExcluded(quotanetpayoutbatch.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *QuotaNetPayoutBatchUpsert) AddCreatedBy(v int64) *QuotaNetPayoutBatchUpsert {
	u.Add(quotanetpayoutbatch.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *QuotaNetPayoutBatchUpsert) ClearCreatedBy() *QuotaNetPayoutBatchUpsert {
	u.SetNull(quotanetpayoutbatch.FieldCreatedBy)
	return u
}

// SetApprovedBy sets the "approved_by" field.
func (u *QuotaNetPayoutBatchUpsert) SetApprovedBy(v int64) *QuotaNetPayoutBatchUpsert {
	u.Set(quotanetpayoutbatch.FieldApprovedBy, v)
	return u
}

// UpdateApprovedBy sets the "approved_by" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsert) UpdateApprovedBy() *QuotaNetPayoutBatchUpsert {
	u.SetExcluded(quotanetpayoutbatch.FieldApprovedBy)
	return u
}

// AddApprovedBy adds v to the "approved_by" field.
func (u *QuotaNetPayoutBatchUpsert) AddApprovedBy(v int64) *QuotaNetPayoutBatchUpsert {
	u.Add(quotanetpayoutbatch.FieldApprovedBy, v)
	return u
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (u *QuotaNetPayoutBatchUpsert) ClearApprovedBy() *QuotaNetPayoutBatchUpsert {
	u.SetNull(quotanetpayoutbatch.FieldApprovedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.QuotaNetPayoutBatch.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *QuotaNetPayoutBatchUpsertOne) UpdateNewValues() *QuotaNetPayoutBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(quotanetpayoutbatch.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QuotaNetPayoutBatch.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *QuotaNetPayoutBatchUpsertOne) Ignore() *QuotaNetPayoutBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuotaNetPayoutBatchUpsertOne) DoNothing() *QuotaNetPayoutBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuotaNetPayoutBatchCreate.OnConflict
// documentation for more info.
func (u *QuotaNetPayoutBatchUpsertOne) Update(set func(*QuotaNetPayoutBatchUpsert)) *QuotaNetPayoutBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuotaNetPayoutBatchUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuotaNetPayoutBatchUpsertOne) SetUpdatedAt(v time.Time) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertOne) UpdateUpdatedAt() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBatchKey sets the "batch_key" field.
func (u *QuotaNetPayoutBatchUpsertOne) SetBatchKey(v string) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetBatchKey(v)
	})
}

// UpdateBatchKey sets the "batch_key" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertOne) UpdateBatchKey() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateBatchKey()
	})
}

// SetWindowStart sets the "window_start" field.
func (u *QuotaNetPayoutBatchUpsertOne) SetWindowStart(v time.Time) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetWindowStart(v)
	})
}

// UpdateWindowStart sets the "window_start" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertOne) UpdateWindowStart() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateWindowStart()
	})
}

// SetWindowEnd sets the "window_end" field.
func (u *QuotaNetPayoutBatchUpsertOne) SetWindowEnd(v time.Time) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetWindowEnd(v)
	})
}

// UpdateWindowEnd sets the "window_end" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertOne) UpdateWindowEnd() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateWindowEnd()
	})
}

// SetStatus sets the "status" field.
func (u *QuotaNetPayoutBatchUpsertOne) SetStatus(v string) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertOne) UpdateStatus() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateStatus()
	})
}

// SetNetwork sets the "network" field.
func (u *QuotaNetPayoutBatchUpsertOne) SetNetwork(v string) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertOne) UpdateNetwork() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateNetwork()
	})
}

// SetTotalTokenFlow sets the "total_token_flow" field.
func (u *QuotaNetPayoutBatchUpsertOne) SetTotalTokenFlow(v int64) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetTotalTokenFlow(v)
	})
}

// AddTotalTokenFlow adds v to the "total_token_flow" field.
func (u *QuotaNetPayoutBatchUpsertOne) AddTotalTokenFlow(v int64) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.AddTotalTokenFlow(v)
	})
}

// UpdateTotalTokenFlow sets the "total_token_flow" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertOne) UpdateTotalTokenFlow() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateTotalTokenFlow()
	})
}

// SetTotalContributionUsd sets the "total_contribution_usd" field.
func (u *QuotaNetPayoutBatchUpsertOne) SetTotalContributionUsd(v float64) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetTotalContributionUsd(v)
	})
}

// AddTotalContributionUsd adds v to the "total_contribution_usd" field.
func (u *QuotaNetPayoutBatchUpsertOne) AddTotalContributionUsd(v float64) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.AddTotalContributionUsd(v)
	})
}

// UpdateTotalContributionUsd sets the "total_contribution_usd" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertOne) UpdateTotalContributionUsd() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateTotalContributionUsd()
	})
}

// SetTotalAmountCxs sets the "total_amount_cxs" field.
func (u *QuotaNetPayoutBatchUpsertOne) SetTotalAmountCxs(v float64) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetTotalAmountCxs(v)
	})
}

// AddTotalAmountCxs adds v to the "total_amount_cxs" field.
func (u *QuotaNetPayoutBatchUpsertOne) AddTotalAmountCxs(v float64) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.AddTotalAmountCxs(v)
	})
}

// UpdateTotalAmountCxs sets the "total_amount_cxs" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertOne) UpdateTotalAmountCxs() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateTotalAmountCxs()
	})
}

// SetItemCount sets the "item_count" field.
func (u *QuotaNetPayoutBatchUpsertOne) SetItemCount(v int) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetItemCount(v)
	})
}

// AddItemCount adds v to the "item_count" field.
func (u *QuotaNetPayoutBatchUpsertOne) AddItemCount(v int) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.AddItemCount(v)
	})
}

// UpdateItemCount sets the "item_count" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertOne) UpdateItemCount() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateItemCount()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *QuotaNetPayoutBatchUpsertOne) SetCreatedBy(v int64) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *QuotaNetPayoutBatchUpsertOne) AddCreatedBy(v int64) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertOne) UpdateCreatedBy() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *QuotaNetPayoutBatchUpsertOne) ClearCreatedBy() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.ClearCreatedBy()
	})
}

// SetApprovedBy sets the "approved_by" field.
func (u *QuotaNetPayoutBatchUpsertOne) SetApprovedBy(v int64) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetApprovedBy(v)
	})
}

// AddApprovedBy adds v to the "approved_by" field.
func (u *QuotaNetPayoutBatchUpsertOne) AddApprovedBy(v int64) *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.AddApprovedBy(v)
	})
}

// UpdateApprovedBy sets the "approved_by" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertOne) UpdateApprovedBy() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateApprovedBy()
	})
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (u *QuotaNetPayoutBatchUpsertOne) ClearApprovedBy() *QuotaNetPayoutBatchUpsertOne {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.ClearApprovedBy()
	})
}

// Exec executes the query.
func (u *QuotaNetPayoutBatchUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuotaNetPayoutBatchCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuotaNetPayoutBatchUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *QuotaNetPayoutBatchUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *QuotaNetPayoutBatchUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// QuotaNetPayoutBatchCreateBulk is the builder for creating many QuotaNetPayoutBatch entities in bulk.
type QuotaNetPayoutBatchCreateBulk struct {
	config
	err      error
	builders []*QuotaNetPayoutBatchCreate
	conflict []sql.ConflictOption
}

// Save creates the QuotaNetPayoutBatch entities in the database.
func (_c *QuotaNetPayoutBatchCreateBulk) Save(ctx context.Context) ([]*QuotaNetPayoutBatch, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*QuotaNetPayoutBatch, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuotaNetPayoutBatchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuotaNetPayoutBatchCreateBulk) SaveX(ctx context.Context) []*QuotaNetPayoutBatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuotaNetPayoutBatchCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuotaNetPayoutBatchCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QuotaNetPayoutBatch.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuotaNetPayoutBatchUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *QuotaNetPayoutBatchCreateBulk) OnConflict(opts ...sql.ConflictOption) *QuotaNetPayoutBatchUpsertBulk {
	_c.conflict = opts
	return &QuotaNetPayoutBatchUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QuotaNetPayoutBatch.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuotaNetPayoutBatchCreateBulk) OnConflictColumns(columns ...string) *QuotaNetPayoutBatchUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuotaNetPayoutBatchUpsertBulk{
		create: _c,
	}
}

// QuotaNetPayoutBatchUpsertBulk is the builder for "upsert"-ing
// a bulk of QuotaNetPayoutBatch nodes.
type QuotaNetPayoutBatchUpsertBulk struct {
	create *QuotaNetPayoutBatchCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.QuotaNetPayoutBatch.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateNewValues() *QuotaNetPayoutBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(quotanetpayoutbatch.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QuotaNetPayoutBatch.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *QuotaNetPayoutBatchUpsertBulk) Ignore() *QuotaNetPayoutBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuotaNetPayoutBatchUpsertBulk) DoNothing() *QuotaNetPayoutBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuotaNetPayoutBatchCreateBulk.OnConflict
// documentation for more info.
func (u *QuotaNetPayoutBatchUpsertBulk) Update(set func(*QuotaNetPayoutBatchUpsert)) *QuotaNetPayoutBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuotaNetPayoutBatchUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuotaNetPayoutBatchUpsertBulk) SetUpdatedAt(v time.Time) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateUpdatedAt() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBatchKey sets the "batch_key" field.
func (u *QuotaNetPayoutBatchUpsertBulk) SetBatchKey(v string) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetBatchKey(v)
	})
}

// UpdateBatchKey sets the "batch_key" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateBatchKey() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateBatchKey()
	})
}

// SetWindowStart sets the "window_start" field.
func (u *QuotaNetPayoutBatchUpsertBulk) SetWindowStart(v time.Time) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetWindowStart(v)
	})
}

// UpdateWindowStart sets the "window_start" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateWindowStart() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateWindowStart()
	})
}

// SetWindowEnd sets the "window_end" field.
func (u *QuotaNetPayoutBatchUpsertBulk) SetWindowEnd(v time.Time) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetWindowEnd(v)
	})
}

// UpdateWindowEnd sets the "window_end" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateWindowEnd() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateWindowEnd()
	})
}

// SetStatus sets the "status" field.
func (u *QuotaNetPayoutBatchUpsertBulk) SetStatus(v string) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateStatus() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateStatus()
	})
}

// SetNetwork sets the "network" field.
func (u *QuotaNetPayoutBatchUpsertBulk) SetNetwork(v string) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateNetwork() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateNetwork()
	})
}

// SetTotalTokenFlow sets the "total_token_flow" field.
func (u *QuotaNetPayoutBatchUpsertBulk) SetTotalTokenFlow(v int64) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetTotalTokenFlow(v)
	})
}

// AddTotalTokenFlow adds v to the "total_token_flow" field.
func (u *QuotaNetPayoutBatchUpsertBulk) AddTotalTokenFlow(v int64) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.AddTotalTokenFlow(v)
	})
}

// UpdateTotalTokenFlow sets the "total_token_flow" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateTotalTokenFlow() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateTotalTokenFlow()
	})
}

// SetTotalContributionUsd sets the "total_contribution_usd" field.
func (u *QuotaNetPayoutBatchUpsertBulk) SetTotalContributionUsd(v float64) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetTotalContributionUsd(v)
	})
}

// AddTotalContributionUsd adds v to the "total_contribution_usd" field.
func (u *QuotaNetPayoutBatchUpsertBulk) AddTotalContributionUsd(v float64) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.AddTotalContributionUsd(v)
	})
}

// UpdateTotalContributionUsd sets the "total_contribution_usd" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateTotalContributionUsd() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateTotalContributionUsd()
	})
}

// SetTotalAmountCxs sets the "total_amount_cxs" field.
func (u *QuotaNetPayoutBatchUpsertBulk) SetTotalAmountCxs(v float64) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetTotalAmountCxs(v)
	})
}

// AddTotalAmountCxs adds v to the "total_amount_cxs" field.
func (u *QuotaNetPayoutBatchUpsertBulk) AddTotalAmountCxs(v float64) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.AddTotalAmountCxs(v)
	})
}

// UpdateTotalAmountCxs sets the "total_amount_cxs" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateTotalAmountCxs() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateTotalAmountCxs()
	})
}

// SetItemCount sets the "item_count" field.
func (u *QuotaNetPayoutBatchUpsertBulk) SetItemCount(v int) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetItemCount(v)
	})
}

// AddItemCount adds v to the "item_count" field.
func (u *QuotaNetPayoutBatchUpsertBulk) AddItemCount(v int) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.AddItemCount(v)
	})
}

// UpdateItemCount sets the "item_count" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateItemCount() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateItemCount()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *QuotaNetPayoutBatchUpsertBulk) SetCreatedBy(v int64) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *QuotaNetPayoutBatchUpsertBulk) AddCreatedBy(v int64) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateCreatedBy() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *QuotaNetPayoutBatchUpsertBulk) ClearCreatedBy() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.ClearCreatedBy()
	})
}

// SetApprovedBy sets the "approved_by" field.
func (u *QuotaNetPayoutBatchUpsertBulk) SetApprovedBy(v int64) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.SetApprovedBy(v)
	})
}

// AddApprovedBy adds v to the "approved_by" field.
func (u *QuotaNetPayoutBatchUpsertBulk) AddApprovedBy(v int64) *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.AddApprovedBy(v)
	})
}

// UpdateApprovedBy sets the "approved_by" field to the value that was provided on create.
func (u *QuotaNetPayoutBatchUpsertBulk) UpdateApprovedBy() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.UpdateApprovedBy()
	})
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (u *QuotaNetPayoutBatchUpsertBulk) ClearApprovedBy() *QuotaNetPayoutBatchUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutBatchUpsert) {
		s.ClearApprovedBy()
	})
}

// Exec executes the query.
func (u *QuotaNetPayoutBatchUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the QuotaNetPayoutBatchCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuotaNetPayoutBatchCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuotaNetPayoutBatchUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
