// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/quotanetnode"
)

// QuotaNetNodeCreate is the builder for creating a QuotaNetNode entity.
type QuotaNetNodeCreate struct {
	config
	mutation *QuotaNetNodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuotaNetNodeCreate) SetCreatedAt(v time.Time) *QuotaNetNodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuotaNetNodeCreate) SetNillableCreatedAt(v *time.Time) *QuotaNetNodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QuotaNetNodeCreate) SetUpdatedAt(v time.Time) *QuotaNetNodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QuotaNetNodeCreate) SetNillableUpdatedAt(v *time.Time) *QuotaNetNodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *QuotaNetNodeCreate) SetDeletedAt(v time.Time) *QuotaNetNodeCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *QuotaNetNodeCreate) SetNillableDeletedAt(v *time.Time) *QuotaNetNodeCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetNodeKey sets the "node_key" field.
func (_c *QuotaNetNodeCreate) SetNodeKey(v string) *QuotaNetNodeCreate {
	_c.mutation.SetNodeKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *QuotaNetNodeCreate) SetName(v string) *QuotaNetNodeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *QuotaNetNodeCreate) SetNillableName(v *string) *QuotaNetNodeCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *QuotaNetNodeCreate) SetOwnerUserID(v int64) *QuotaNetNodeCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_c *QuotaNetNodeCreate) SetNillableOwnerUserID(v *int64) *QuotaNetNodeCreate {
	if v != nil {
		_c.SetOwnerUserID(*v)
	}
	return _c
}

// SetWalletAddress sets the "wallet_address" field.
func (_c *QuotaNetNodeCreate) SetWalletAddress(v string) *QuotaNetNodeCreate {
	_c.mutation.SetWalletAddress(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *QuotaNetNodeCreate) SetTokenHash(v string) *QuotaNetNodeCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *QuotaNetNodeCreate) SetStatus(v string) *QuotaNetNodeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *QuotaNetNodeCreate) SetNillableStatus(v *string) *QuotaNetNodeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProtocolVersion sets the "protocol_version" field.
func (_c *QuotaNetNodeCreate) SetProtocolVersion(v string) *QuotaNetNodeCreate {
	_c.mutation.SetProtocolVersion(v)
	return _c
}

// SetNillableProtocolVersion sets the "protocol_version" field if the given value is not nil.
func (_c *QuotaNetNodeCreate) SetNillableProtocolVersion(v *string) *QuotaNetNodeCreate {
	if v != nil {
		_c.SetProtocolVersion(*v)
	}
	return _c
}

// SetClientVersion sets the "client_version" field.
func (_c *QuotaNetNodeCreate) SetClientVersion(v string) *QuotaNetNodeCreate {
	_c.mutation.SetClientVersion(v)
	return _c
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (_c *QuotaNetNodeCreate) SetNillableClientVersion(v *string) *QuotaNetNodeCreate {
	if v != nil {
		_c.SetClientVersion(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *QuotaNetNodeCreate) SetLastSeenAt(v time.Time) *QuotaNetNodeCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *QuotaNetNodeCreate) SetNillableLastSeenAt(v *time.Time) *QuotaNetNodeCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// Mutation returns the QuotaNetNodeMutation object of the builder.
func (_c *QuotaNetNodeCreate) Mutation() *QuotaNetNodeMutation {
	return _c.mutation
}

// Save creates the QuotaNetNode in the database.
func (_c *QuotaNetNodeCreate) Save(ctx context.Context) (*QuotaNetNode, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuotaNetNodeCreate) SaveX(ctx context.Context) *QuotaNetNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuotaNetNodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuotaNetNodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuotaNetNodeCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if quotanetnode.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized quotanetnode.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := quotanetnode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if quotanetnode.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized quotanetnode.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := quotanetnode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := quotanetnode.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := quotanetnode.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuotaNetNodeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QuotaNetNode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "QuotaNetNode.updated_at"`)}
	}
	if _, ok := _c.mutation.NodeKey(); !ok {
		return &ValidationError{Name: "node_key", err: errors.New(`ent: missing required field "QuotaNetNode.node_key"`)}
	}
	if v, ok := _c.mutation.NodeKey(); ok {
		if err := quotanetnode.NodeKeyValidator(v); err != nil {
			return &ValidationError{Name: "node_key", err: fmt.Errorf(`ent: validator failed for field "QuotaNetNode.node_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "QuotaNetNode.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := quotanetnode.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "QuotaNetNode.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WalletAddress(); !ok {
		return &ValidationError{Name: "wallet_address", err: errors.New(`ent: missing required field "QuotaNetNode.wallet_address"`)}
	}
	if v, ok := _c.mutation.WalletAddress(); ok {
		if err := quotanetnode.WalletAddressValidator(v); err != nil {
			return &ValidationError{Name: "wallet_address", err: fmt.Errorf(`ent: validator failed for field "QuotaNetNode.wallet_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "QuotaNetNode.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := quotanetnode.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "QuotaNetNode.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "QuotaNetNode.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := quotanetnode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaNetNode.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProtocolVersion(); ok {
		if err := quotanetnode.ProtocolVersionValidator(v); err != nil {
			return &ValidationError{Name: "protocol_version", err: fmt.Errorf(`ent: validator failed for field "QuotaNetNode.protocol_version": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ClientVersion(); ok {
		if err := quotanetnode.ClientVersionValidator(v); err != nil {
			return &ValidationError{Name: "client_version", err: fmt.Errorf(`ent: validator failed for field "QuotaNetNode.client_version": %w`, err)}
		}
	}
	return nil
}

func (_c *QuotaNetNodeCreate) sqlSave(ctx context.Context) (*QuotaNetNode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuotaNetNodeCreate) createSpec() (*QuotaNetNode, *sqlgraph.CreateSpec) {
	var (
		_node = &QuotaNetNode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quotanetnode.Table, sqlgraph.NewFieldSpec(quotanetnode.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quotanetnode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(quotanetnode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(quotanetnode.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.NodeKey(); ok {
		_spec.SetField(quotanetnode.FieldNodeKey, field.TypeString, value)
		_node.NodeKey = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(quotanetnode.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(quotanetnode.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = &value
	}
	if value, ok := _c.mutation.WalletAddress(); ok {
		_spec.SetField(quotanetnode.FieldWalletAddress, field.TypeString, value)
		_node.WalletAddress = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(quotanetnode.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(quotanetnode.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProtocolVersion(); ok {
		_spec.SetField(quotanetnode.FieldProtocolVersion, field.TypeString, value)
		_node.ProtocolVersion = &value
	}
	if value, ok := _c.mutation.ClientVersion(); ok {
		_spec.SetField(quotanetnode.FieldClientVersion, field.TypeString, value)
		_node.ClientVersion = &value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(quotanetnode.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QuotaNetNode.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuotaNetNodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *QuotaNetNodeCreate) OnConflict(opts ...sql.ConflictOption) *QuotaNetNodeUpsertOne {
	_c.conflict = opts
	return &QuotaNetNodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QuotaNetNode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuotaNetNodeCreate) OnConflictColumns(columns ...string) *QuotaNetNodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuotaNetNodeUpsertOne{
		create: _c,
	}
}

type (
	// QuotaNetNodeUpsertOne is the builder for "upsert"-ing
	//  one QuotaNetNode node.
	QuotaNetNodeUpsertOne struct {
		create *QuotaNetNodeCreate
	}

	// QuotaNetNodeUpsert is the "OnConflict" setter.
	QuotaNetNodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *QuotaNetNodeUpsert) SetUpdatedAt(v time.Time) *QuotaNetNodeUpsert {
	u.Set(quotanetnode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuotaNetNodeUpsert) UpdateUpdatedAt() *QuotaNetNodeUpsert {
	u.SetExcluded(quotanetnode.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *QuotaNetNodeUpsert) SetDeletedAt(v time.Time) *QuotaNetNodeUpsert {
	u.Set(quotanetnode.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *QuotaNetNodeUpsert) UpdateDeletedAt() *QuotaNetNodeUpsert {
	u.SetExcluded(quotanetnode.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *QuotaNetNodeUpsert) ClearDeletedAt() *QuotaNetNodeUpsert {
	u.SetNull(quotanetnode.FieldDeletedAt)
	return u
}

// SetNodeKey sets the "node_key" field.
func (u *QuotaNetNodeUpsert) SetNodeKey(v string) *QuotaNetNodeUpsert {
	u.Set(quotanetnode.FieldNodeKey, v)
	return u
}

// UpdateNodeKey sets the "node_key" field to the value that was provided on create.
func (u *QuotaNetNodeUpsert) UpdateNodeKey() *QuotaNetNodeUpsert {
	u.SetExcluded(quotanetnode.FieldNodeKey)
	return u
}

// SetName sets the "name" field.
func (u *QuotaNetNodeUpsert) SetName(v string) *QuotaNetNodeUpsert {
	u.Set(quotanetnode.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *QuotaNetNodeUpsert) UpdateName() *QuotaNetNodeUpsert {
	u.SetExcluded(quotanetnode.FieldName)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *QuotaNetNodeUpsert) SetOwnerUserID(v int64) *QuotaNetNodeUpsert {
	u.Set(quotanetnode.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *QuotaNetNodeUpsert) UpdateOwnerUserID() *QuotaNetNodeUpsert {
	u.SetExcluded(quotanetnode.FieldOwnerUserID)
	return u
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *QuotaNetNodeUpsert) AddOwnerUserID(v int64) *QuotaNetNodeUpsert {
	u.Add(quotanetnode.FieldOwnerUserID, v)
	return u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (u *QuotaNetNodeUpsert) ClearOwnerUserID() *QuotaNetNodeUpsert {
	u.SetNull(quotanetnode.FieldOwnerUserID)
	return u
}

// SetWalletAddress sets the "wallet_address" field.
func (u *QuotaNetNodeUpsert) SetWalletAddress(v string) *QuotaNetNodeUpsert {
	u.Set(quotanetnode.FieldWalletAddress, v)
	return u
}

// UpdateWalletAddress sets the "wallet_address" field to the value that was provided on create.
func (u *QuotaNetNodeUpsert) UpdateWalletAddress() *QuotaNetNodeUpsert {
	u.SetExcluded(quotanetnode.FieldWalletAddress)
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *QuotaNetNodeUpsert) SetTokenHash(v string) *QuotaNetNodeUpsert {
	u.Set(quotanetnode.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *QuotaNetNodeUpsert) UpdateTokenHash() *QuotaNetNodeUpsert {
	u.SetExcluded(quotanetnode.FieldTokenHash)
	return u
}

// SetStatus sets the "status" field.
func (u *QuotaNetNodeUpsert) SetStatus(v string) *QuotaNetNodeUpsert {
	u.Set(quotanetnode.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QuotaNetNodeUpsert) UpdateStatus() *QuotaNetNodeUpsert {
	u.SetExcluded(quotanetnode.FieldStatus)
	return u
}

// SetProtocolVersion sets the "protocol_version" field.
func (u *QuotaNetNodeUpsert) SetProtocolVersion(v string) *QuotaNetNodeUpsert {
	u.Set(quotanetnode.FieldProtocolVersion, v)
	return u
}

// UpdateProtocolVersion sets the "protocol_version" field to the value that was provided on create.
func (u *QuotaNetNodeUpsert) UpdateProtocolVersion() *QuotaNetNodeUpsert {
	u.SetExcluded(quotanetnode.FieldProtocolVersion)
	return u
}

// ClearProtocolVersion clears the value of the "protocol_version" field.
func (u *QuotaNetNodeUpsert) ClearProtocolVersion() *QuotaNetNodeUpsert {
	u.SetNull(quotanetnode.FieldProtocolVersion)
	return u
}

// SetClientVersion sets the "client_version" field.
func (u *QuotaNetNodeUpsert) SetClientVersion(v string) *QuotaNetNodeUpsert {
	u.Set(quotanetnode.FieldClientVersion, v)
	return u
}

// UpdateClientVersion sets the "client_version" field to the value that was provided on create.
func (u *QuotaNetNodeUpsert) UpdateClientVersion() *QuotaNetNodeUpsert {
	u.SetExcluded(quotanetnode.FieldClientVersion)
	return u
}

// ClearClientVersion clears the value of the "client_version" field.
func (u *QuotaNetNodeUpsert) ClearClientVersion() *QuotaNetNodeUpsert {
	u.SetNull(quotanetnode.FieldClientVersion)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *QuotaNetNodeUpsert) SetLastSeenAt(v time.Time) *QuotaNetNodeUpsert {
	u.Set(quotanetnode.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *QuotaNetNodeUpsert) UpdateLastSeenAt() *QuotaNetNodeUpsert {
	u.SetExcluded(quotanetnode.FieldLastSeenAt)
	return u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *QuotaNetNodeUpsert) ClearLastSeenAt() *QuotaNetNodeUpsert {
	u.SetNull(quotanetnode.FieldLastSeenAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.QuotaNetNode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *QuotaNetNodeUpsertOne) UpdateNewValues() *QuotaNetNodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(quotanetnode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QuotaNetNode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *QuotaNetNodeUpsertOne) Ignore() *QuotaNetNodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuotaNetNodeUpsertOne) DoNothing() *QuotaNetNodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuotaNetNodeCreate.OnConflict
// documentation for more info.
func (u *QuotaNetNodeUpsertOne) Update(set func(*QuotaNetNodeUpsert)) *QuotaNetNodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuotaNetNodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuotaNetNodeUpsertOne) SetUpdatedAt(v time.Time) *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertOne) UpdateUpdatedAt() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *QuotaNetNodeUpsertOne) SetDeletedAt(v time.Time) *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertOne) UpdateDeletedAt() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *QuotaNetNodeUpsertOne) ClearDeletedAt() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.ClearDeletedAt()
	})
}

// SetNodeKey sets the "node_key" field.
func (u *QuotaNetNodeUpsertOne) SetNodeKey(v string) *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetNodeKey(v)
	})
}

// UpdateNodeKey sets the "node_key" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertOne) UpdateNodeKey() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateNodeKey()
	})
}

// SetName sets the "name" field.
func (u *QuotaNetNodeUpsertOne) SetName(v string) *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertOne) UpdateName() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateName()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *QuotaNetNodeUpsertOne) SetOwnerUserID(v int64) *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *QuotaNetNodeUpsertOne) AddOwnerUserID(v int64) *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertOne) UpdateOwnerUserID() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateOwnerUserID()
	})
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (u *QuotaNetNodeUpsertOne) ClearOwnerUserID() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.ClearOwnerUserID()
	})
}

// SetWalletAddress sets the "wallet_address" field.
func (u *QuotaNetNodeUpsertOne) SetWalletAddress(v string) *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetWalletAddress(v)
	})
}

// UpdateWalletAddress sets the "wallet_address" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertOne) UpdateWalletAddress() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateWalletAddress()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *QuotaNetNodeUpsertOne) SetTokenHash(v string) *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertOne) UpdateTokenHash() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateTokenHash()
	})
}

// SetStatus sets the "status" field.
func (u *QuotaNetNodeUpsertOne) SetStatus(v string) *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertOne) UpdateStatus() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateStatus()
	})
}

// SetProtocolVersion sets the "protocol_version" field.
func (u *QuotaNetNodeUpsertOne) SetProtocolVersion(v string) *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetProtocolVersion(v)
	})
}

// UpdateProtocolVersion sets the "protocol_version" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertOne) UpdateProtocolVersion() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateProtocolVersion()
	})
}

// ClearProtocolVersion clears the value of the "protocol_version" field.
func (u *QuotaNetNodeUpsertOne) ClearProtocolVersion() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.ClearProtocolVersion()
	})
}

// SetClientVersion sets the "client_version" field.
func (u *QuotaNetNodeUpsertOne) SetClientVersion(v string) *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetClientVersion(v)
	})
}

// UpdateClientVersion sets the "client_version" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertOne) UpdateClientVersion() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateClientVersion()
	})
}

// ClearClientVersion clears the value of the "client_version" field.
func (u *QuotaNetNodeUpsertOne) ClearClientVersion() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.ClearClientVersion()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *QuotaNetNodeUpsertOne) SetLastSeenAt(v time.Time) *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertOne) UpdateLastSeenAt() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *QuotaNetNodeUpsertOne) ClearLastSeenAt() *QuotaNetNodeUpsertOne {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.ClearLastSeenAt()
	})
}

// Exec executes the query.
func (u *QuotaNetNodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuotaNetNodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuotaNetNodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *QuotaNetNodeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *QuotaNetNodeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// QuotaNetNodeCreateBulk is the builder for creating many QuotaNetNode entities in bulk.
type QuotaNetNodeCreateBulk struct {
	config
	err      error
	builders []*QuotaNetNodeCreate
	conflict []sql.ConflictOption
}

// Save creates the QuotaNetNode entities in the database.
func (_c *QuotaNetNodeCreateBulk) Save(ctx context.Context) ([]*QuotaNetNode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*QuotaNetNode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuotaNetNodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuotaNetNodeCreateBulk) SaveX(ctx context.Context) []*QuotaNetNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuotaNetNodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuotaNetNodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QuotaNetNode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuotaNetNodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *QuotaNetNodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *QuotaNetNodeUpsertBulk {
	_c.conflict = opts
	return &QuotaNetNodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QuotaNetNode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuotaNetNodeCreateBulk) OnConflictColumns(columns ...string) *QuotaNetNodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuotaNetNodeUpsertBulk{
		create: _c,
	}
}

// QuotaNetNodeUpsertBulk is the builder for "upsert"-ing
// a bulk of QuotaNetNode nodes.
type QuotaNetNodeUpsertBulk struct {
	create *QuotaNetNodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.QuotaNetNode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *QuotaNetNodeUpsertBulk) UpdateNewValues() *QuotaNetNodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(quotanetnode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QuotaNetNode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *QuotaNetNodeUpsertBulk) Ignore() *QuotaNetNodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuotaNetNodeUpsertBulk) DoNothing() *QuotaNetNodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuotaNetNodeCreateBulk.OnConflict
// documentation for more info.
func (u *QuotaNetNodeUpsertBulk) Update(set func(*QuotaNetNodeUpsert)) *QuotaNetNodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuotaNetNodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuotaNetNodeUpsertBulk) SetUpdatedAt(v time.Time) *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertBulk) UpdateUpdatedAt() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *QuotaNetNodeUpsertBulk) SetDeletedAt(v time.Time) *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertBulk) UpdateDeletedAt() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *QuotaNetNodeUpsertBulk) ClearDeletedAt() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.ClearDeletedAt()
	})
}

// SetNodeKey sets the "node_key" field.
func (u *QuotaNetNodeUpsertBulk) SetNodeKey(v string) *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetNodeKey(v)
	})
}

// UpdateNodeKey sets the "node_key" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertBulk) UpdateNodeKey() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateNodeKey()
	})
}

// SetName sets the "name" field.
func (u *QuotaNetNodeUpsertBulk) SetName(v string) *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertBulk) UpdateName() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateName()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *QuotaNetNodeUpsertBulk) SetOwnerUserID(v int64) *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *QuotaNetNodeUpsertBulk) AddOwnerUserID(v int64) *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertBulk) UpdateOwnerUserID() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateOwnerUserID()
	})
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (u *QuotaNetNodeUpsertBulk) ClearOwnerUserID() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.ClearOwnerUserID()
	})
}

// SetWalletAddress sets the "wallet_address" field.
func (u *QuotaNetNodeUpsertBulk) SetWalletAddress(v string) *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetWalletAddress(v)
	})
}

// UpdateWalletAddress sets the "wallet_address" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertBulk) UpdateWalletAddress() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateWalletAddress()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *QuotaNetNodeUpsertBulk) SetTokenHash(v string) *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertBulk) UpdateTokenHash() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateTokenHash()
	})
}

// SetStatus sets the "status" field.
func (u *QuotaNetNodeUpsertBulk) SetStatus(v string) *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertBulk) UpdateStatus() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateStatus()
	})
}

// SetProtocolVersion sets the "protocol_version" field.
func (u *QuotaNetNodeUpsertBulk) SetProtocolVersion(v string) *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetProtocolVersion(v)
	})
}

// UpdateProtocolVersion sets the "protocol_version" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertBulk) UpdateProtocolVersion() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateProtocolVersion()
	})
}

// ClearProtocolVersion clears the value of the "protocol_version" field.
func (u *QuotaNetNodeUpsertBulk) ClearProtocolVersion() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.ClearProtocolVersion()
	})
}

// SetClientVersion sets the "client_version" field.
func (u *QuotaNetNodeUpsertBulk) SetClientVersion(v string) *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetClientVersion(v)
	})
}

// UpdateClientVersion sets the "client_version" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertBulk) UpdateClientVersion() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateClientVersion()
	})
}

// ClearClientVersion clears the value of the "client_version" field.
func (u *QuotaNetNodeUpsertBulk) ClearClientVersion() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.ClearClientVersion()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *QuotaNetNodeUpsertBulk) SetLastSeenAt(v time.Time) *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *QuotaNetNodeUpsertBulk) UpdateLastSeenAt() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *QuotaNetNodeUpsertBulk) ClearLastSeenAt() *QuotaNetNodeUpsertBulk {
	return u.Update(func(s *QuotaNetNodeUpsert) {
		s.ClearLastSeenAt()
	})
}

// Exec executes the query.
func (u *QuotaNetNodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the QuotaNetNodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuotaNetNodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuotaNetNodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
