// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/quotanetnode"
)

// QuotaNetNode is the model entity for the QuotaNetNode schema.
type QuotaNetNode struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// NodeKey holds the value of the "node_key" field.
	NodeKey string `json:"node_key,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID *int64 `json:"owner_user_id,omitempty"`
	// WalletAddress holds the value of the "wallet_address" field.
	WalletAddress string `json:"wallet_address,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"token_hash,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ProtocolVersion holds the value of the "protocol_version" field.
	ProtocolVersion *string `json:"protocol_version,omitempty"`
	// ClientVersion holds the value of the "client_version" field.
	ClientVersion *string `json:"client_version,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt   *time.Time `json:"last_seen_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QuotaNetNode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quotanetnode.FieldID, quotanetnode.FieldOwnerUserID:
			values[i] = new(sql.NullInt64)
		case quotanetnode.FieldNodeKey, quotanetnode.FieldName, quotanetnode.FieldWalletAddress, quotanetnode.FieldTokenHash, quotanetnode.FieldStatus, quotanetnode.FieldProtocolVersion, quotanetnode.FieldClientVersion:
			values[i] = new(sql.NullString)
		case quotanetnode.FieldCreatedAt, quotanetnode.FieldUpdatedAt, quotanetnode.FieldDeletedAt, quotanetnode.FieldLastSeenAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QuotaNetNode fields.
func (_m *QuotaNetNode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quotanetnode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case quotanetnode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case quotanetnode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case quotanetnode.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case quotanetnode.FieldNodeKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_key", values[i])
			} else if value.Valid {
				_m.NodeKey = value.String
			}
		case quotanetnode.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case quotanetnode.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = new(int64)
				*_m.OwnerUserID = value.Int64
			}
		case quotanetnode.FieldWalletAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_address", values[i])
			} else if value.Valid {
				_m.WalletAddress = value.String
			}
		case quotanetnode.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case quotanetnode.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case quotanetnode.FieldProtocolVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol_version", values[i])
			} else if value.Valid {
				_m.ProtocolVersion = new(string)
				*_m.ProtocolVersion = value.String
			}
		case quotanetnode.FieldClientVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_version", values[i])
			} else if value.Valid {
				_m.ClientVersion = new(string)
				*_m.ClientVersion = value.String
			}
		case quotanetnode.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = new(time.Time)
				*_m.LastSeenAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QuotaNetNode.
// This includes values selected through modifiers, order, etc.
func (_m *QuotaNetNode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this QuotaNetNode.
// Note that you need to call QuotaNetNode.Unwrap() before calling this method if this QuotaNetNode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *QuotaNetNode) Update() *QuotaNetNodeUpdateOne {
	return NewQuotaNetNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the QuotaNetNode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *QuotaNetNode) Unwrap() *QuotaNetNode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: QuotaNetNode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *QuotaNetNode) String() string {
	var builder strings.Builder
	builder.WriteString("QuotaNetNode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("node_key=")
	builder.WriteString(_m.NodeKey)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.OwnerUserID; v != nil {
		builder.WriteString("owner_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("wallet_address=")
	builder.WriteString(_m.WalletAddress)
	builder.WriteString(", ")
	builder.WriteString("token_hash=")
	builder.WriteString(_m.TokenHash)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ProtocolVersion; v != nil {
		builder.WriteString("protocol_version=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ClientVersion; v != nil {
		builder.WriteString("client_version=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastSeenAt; v != nil {
		builder.WriteString("last_seen_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// QuotaNetNodes is a parsable slice of QuotaNetNode.
type QuotaNetNodes []*QuotaNetNode
