// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/quotanetpayoutitem"
)

// QuotaNetPayoutItemCreate is the builder for creating a QuotaNetPayoutItem entity.
type QuotaNetPayoutItemCreate struct {
	config
	mutation *QuotaNetPayoutItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuotaNetPayoutItemCreate) SetCreatedAt(v time.Time) *QuotaNetPayoutItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuotaNetPayoutItemCreate) SetNillableCreatedAt(v *time.Time) *QuotaNetPayoutItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QuotaNetPayoutItemCreate) SetUpdatedAt(v time.Time) *QuotaNetPayoutItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QuotaNetPayoutItemCreate) SetNillableUpdatedAt(v *time.Time) *QuotaNetPayoutItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetItemKey sets the "item_key" field.
func (_c *QuotaNetPayoutItemCreate) SetItemKey(v string) *QuotaNetPayoutItemCreate {
	_c.mutation.SetItemKey(v)
	return _c
}

// SetBatchID sets the "batch_id" field.
func (_c *QuotaNetPayoutItemCreate) SetBatchID(v int64) *QuotaNetPayoutItemCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetNodeID sets the "node_id" field.
func (_c *QuotaNetPayoutItemCreate) SetNodeID(v int64) *QuotaNetPayoutItemCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_c *QuotaNetPayoutItemCreate) SetNillableNodeID(v *int64) *QuotaNetPayoutItemCreate {
	if v != nil {
		_c.SetNodeID(*v)
	}
	return _c
}

// SetWalletAddress sets the "wallet_address" field.
func (_c *QuotaNetPayoutItemCreate) SetWalletAddress(v string) *QuotaNetPayoutItemCreate {
	_c.mutation.SetWalletAddress(v)
	return _c
}

// SetTokenFlow sets the "token_flow" field.
func (_c *QuotaNetPayoutItemCreate) SetTokenFlow(v int64) *QuotaNetPayoutItemCreate {
	_c.mutation.SetTokenFlow(v)
	return _c
}

// SetNillableTokenFlow sets the "token_flow" field if the given value is not nil.
func (_c *QuotaNetPayoutItemCreate) SetNillableTokenFlow(v *int64) *QuotaNetPayoutItemCreate {
	if v != nil {
		_c.SetTokenFlow(*v)
	}
	return _c
}

// SetAmountCxs sets the "amount_cxs" field.
func (_c *QuotaNetPayoutItemCreate) SetAmountCxs(v float64) *QuotaNetPayoutItemCreate {
	_c.mutation.SetAmountCxs(v)
	return _c
}

// SetNillableAmountCxs sets the "amount_cxs" field if the given value is not nil.
func (_c *QuotaNetPayoutItemCreate) SetNillableAmountCxs(v *float64) *QuotaNetPayoutItemCreate {
	if v != nil {
		_c.SetAmountCxs(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *QuotaNetPayoutItemCreate) SetStatus(v string) *QuotaNetPayoutItemCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *QuotaNetPayoutItemCreate) SetNillableStatus(v *string) *QuotaNetPayoutItemCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTxHash sets the "tx_hash" field.
func (_c *QuotaNetPayoutItemCreate) SetTxHash(v string) *QuotaNetPayoutItemCreate {
	_c.mutation.SetTxHash(v)
	return _c
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_c *QuotaNetPayoutItemCreate) SetNillableTxHash(v *string) *QuotaNetPayoutItemCreate {
	if v != nil {
		_c.SetTxHash(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *QuotaNetPayoutItemCreate) SetErrorMessage(v string) *QuotaNetPayoutItemCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *QuotaNetPayoutItemCreate) SetNillableErrorMessage(v *string) *QuotaNetPayoutItemCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetFinalizedAt sets the "finalized_at" field.
func (_c *QuotaNetPayoutItemCreate) SetFinalizedAt(v time.Time) *QuotaNetPayoutItemCreate {
	_c.mutation.SetFinalizedAt(v)
	return _c
}

// SetNillableFinalizedAt sets the "finalized_at" field if the given value is not nil.
func (_c *QuotaNetPayoutItemCreate) SetNillableFinalizedAt(v *time.Time) *QuotaNetPayoutItemCreate {
	if v != nil {
		_c.SetFinalizedAt(*v)
	}
	return _c
}

// Mutation returns the QuotaNetPayoutItemMutation object of the builder.
func (_c *QuotaNetPayoutItemCreate) Mutation() *QuotaNetPayoutItemMutation {
	return _c.mutation
}

// Save creates the QuotaNetPayoutItem in the database.
func (_c *QuotaNetPayoutItemCreate) Save(ctx context.Context) (*QuotaNetPayoutItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuotaNetPayoutItemCreate) SaveX(ctx context.Context) *QuotaNetPayoutItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuotaNetPayoutItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuotaNetPayoutItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuotaNetPayoutItemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quotanetpayoutitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := quotanetpayoutitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TokenFlow(); !ok {
		v := quotanetpayoutitem.DefaultTokenFlow
		_c.mutation.SetTokenFlow(v)
	}
	if _, ok := _c.mutation.AmountCxs(); !ok {
		v := quotanetpayoutitem.DefaultAmountCxs
		_c.mutation.SetAmountCxs(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := quotanetpayoutitem.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuotaNetPayoutItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QuotaNetPayoutItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "QuotaNetPayoutItem.updated_at"`)}
	}
	if _, ok := _c.mutation.ItemKey(); !ok {
		return &ValidationError{Name: "item_key", err: errors.New(`ent: missing required field "QuotaNetPayoutItem.item_key"`)}
	}
	if v, ok := _c.mutation.ItemKey(); ok {
		if err := quotanetpayoutitem.ItemKeyValidator(v); err != nil {
			return &ValidationError{Name: "item_key", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutItem.item_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "QuotaNetPayoutItem.batch_id"`)}
	}
	if _, ok := _c.mutation.WalletAddress(); !ok {
		return &ValidationError{Name: "wallet_address", err: errors.New(`ent: missing required field "QuotaNetPayoutItem.wallet_address"`)}
	}
	if v, ok := _c.mutation.WalletAddress(); ok {
		if err := quotanetpayoutitem.WalletAddressValidator(v); err != nil {
			return &ValidationError{Name: "wallet_address", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutItem.wallet_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenFlow(); !ok {
		return &ValidationError{Name: "token_flow", err: errors.New(`ent: missing required field "QuotaNetPayoutItem.token_flow"`)}
	}
	if _, ok := _c.mutation.AmountCxs(); !ok {
		return &ValidationError{Name: "amount_cxs", err: errors.New(`ent: missing required field "QuotaNetPayoutItem.amount_cxs"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "QuotaNetPayoutItem.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := quotanetpayoutitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutItem.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TxHash(); ok {
		if err := quotanetpayoutitem.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "QuotaNetPayoutItem.tx_hash": %w`, err)}
		}
	}
	return nil
}

func (_c *QuotaNetPayoutItemCreate) sqlSave(ctx context.Context) (*QuotaNetPayoutItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuotaNetPayoutItemCreate) createSpec() (*QuotaNetPayoutItem, *sqlgraph.CreateSpec) {
	var (
		_node = &QuotaNetPayoutItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quotanetpayoutitem.Table, sqlgraph.NewFieldSpec(quotanetpayoutitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quotanetpayoutitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(quotanetpayoutitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ItemKey(); ok {
		_spec.SetField(quotanetpayoutitem.FieldItemKey, field.TypeString, value)
		_node.ItemKey = value
	}
	if value, ok := _c.mutation.BatchID(); ok {
		_spec.SetField(quotanetpayoutitem.FieldBatchID, field.TypeInt64, value)
		_node.BatchID = value
	}
	if value, ok := _c.mutation.NodeID(); ok {
		_spec.SetField(quotanetpayoutitem.FieldNodeID, field.TypeInt64, value)
		_node.NodeID = &value
	}
	if value, ok := _c.mutation.WalletAddress(); ok {
		_spec.SetField(quotanetpayoutitem.FieldWalletAddress, field.TypeString, value)
		_node.WalletAddress = value
	}
	if value, ok := _c.mutation.TokenFlow(); ok {
		_spec.SetField(quotanetpayoutitem.FieldTokenFlow, field.TypeInt64, value)
		_node.TokenFlow = value
	}
	if value, ok := _c.mutation.AmountCxs(); ok {
		_spec.SetField(quotanetpayoutitem.FieldAmountCxs, field.TypeFloat64, value)
		_node.AmountCxs = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(quotanetpayoutitem.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TxHash(); ok {
		_spec.SetField(quotanetpayoutitem.FieldTxHash, field.TypeString, value)
		_node.TxHash = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(quotanetpayoutitem.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.FinalizedAt(); ok {
		_spec.SetField(quotanetpayoutitem.FieldFinalizedAt, field.TypeTime, value)
		_node.FinalizedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QuotaNetPayoutItem.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuotaNetPayoutItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *QuotaNetPayoutItemCreate) OnConflict(opts ...sql.ConflictOption) *QuotaNetPayoutItemUpsertOne {
	_c.conflict = opts
	return &QuotaNetPayoutItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QuotaNetPayoutItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuotaNetPayoutItemCreate) OnConflictColumns(columns ...string) *QuotaNetPayoutItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuotaNetPayoutItemUpsertOne{
		create: _c,
	}
}

type (
	// QuotaNetPayoutItemUpsertOne is the builder for "upsert"-ing
	//  one QuotaNetPayoutItem node.
	QuotaNetPayoutItemUpsertOne struct {
		create *QuotaNetPayoutItemCreate
	}

	// QuotaNetPayoutItemUpsert is the "OnConflict" setter.
	QuotaNetPayoutItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *QuotaNetPayoutItemUpsert) SetUpdatedAt(v time.Time) *QuotaNetPayoutItemUpsert {
	u.Set(quotanetpayoutitem.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsert) UpdateUpdatedAt() *QuotaNetPayoutItemUpsert {
	u.SetExcluded(quotanetpayoutitem.FieldUpdatedAt)
	return u
}

// SetItemKey sets the "item_key" field.
func (u *QuotaNetPayoutItemUpsert) SetItemKey(v string) *QuotaNetPayoutItemUpsert {
	u.Set(quotanetpayoutitem.FieldItemKey, v)
	return u
}

// UpdateItemKey sets the "item_key" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsert) UpdateItemKey() *QuotaNetPayoutItemUpsert {
	u.SetExcluded(quotanetpayoutitem.FieldItemKey)
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *QuotaNetPayoutItemUpsert) SetBatchID(v int64) *QuotaNetPayoutItemUpsert {
	u.Set(quotanetpayoutitem.FieldBatchID, v)
	return u
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsert) UpdateBatchID() *QuotaNetPayoutItemUpsert {
	u.SetExcluded(quotanetpayoutitem.FieldBatchID)
	return u
}

// AddBatchID adds v to the "batch_id" field.
func (u *QuotaNetPayoutItemUpsert) AddBatchID(v int64) *QuotaNetPayoutItemUpsert {
	u.Add(quotanetpayoutitem.FieldBatchID, v)
	return u
}

// SetNodeID sets the "node_id" field.
func (u *QuotaNetPayoutItemUpsert) SetNodeID(v int64) *QuotaNetPayoutItemUpsert {
	u.Set(quotanetpayoutitem.FieldNodeID, v)
	return u
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsert) UpdateNodeID() *QuotaNetPayoutItemUpsert {
	u.SetExcluded(quotanetpayoutitem.FieldNodeID)
	return u
}

// AddNodeID adds v to the "node_id" field.
func (u *QuotaNetPayoutItemUpsert) AddNodeID(v int64) *QuotaNetPayoutItemUpsert {
	u.Add(quotanetpayoutitem.FieldNodeID, v)
	return u
}

// ClearNodeID clears the value of the "node_id" field.
func (u *QuotaNetPayoutItemUpsert) ClearNodeID() *QuotaNetPayoutItemUpsert {
	u.SetNull(quotanetpayoutitem.FieldNodeID)
	return u
}

// SetWalletAddress sets the "wallet_address" field.
func (u *QuotaNetPayoutItemUpsert) SetWalletAddress(v string) *QuotaNetPayoutItemUpsert {
	u.Set(quotanetpayoutitem.FieldWalletAddress, v)
	return u
}

// UpdateWalletAddress sets the "wallet_address" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsert) UpdateWalletAddress() *QuotaNetPayoutItemUpsert {
	u.SetExcluded(quotanetpayoutitem.FieldWalletAddress)
	return u
}

// SetTokenFlow sets the "token_flow" field.
func (u *QuotaNetPayoutItemUpsert) SetTokenFlow(v int64) *QuotaNetPayoutItemUpsert {
	u.Set(quotanetpayoutitem.FieldTokenFlow, v)
	return u
}

// UpdateTokenFlow sets the "token_flow" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsert) UpdateTokenFlow() *QuotaNetPayoutItemUpsert {
	u.SetExcluded(quotanetpayoutitem.FieldTokenFlow)
	return u
}

// AddTokenFlow adds v to the "token_flow" field.
func (u *QuotaNetPayoutItemUpsert) AddTokenFlow(v int64) *QuotaNetPayoutItemUpsert {
	u.Add(quotanetpayoutitem.FieldTokenFlow, v)
	return u
}

// SetAmountCxs sets the "amount_cxs" field.
func (u *QuotaNetPayoutItemUpsert) SetAmountCxs(v float64) *QuotaNetPayoutItemUpsert {
	u.Set(quotanetpayoutitem.FieldAmountCxs, v)
	return u
}

// UpdateAmountCxs sets the "amount_cxs" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsert) UpdateAmountCxs() *QuotaNetPayoutItemUpsert {
	u.SetExcluded(quotanetpayoutitem.FieldAmountCxs)
	return u
}

// AddAmountCxs adds v to the "amount_cxs" field.
func (u *QuotaNetPayoutItemUpsert) AddAmountCxs(v float64) *QuotaNetPayoutItemUpsert {
	u.Add(quotanetpayoutitem.FieldAmountCxs, v)
	return u
}

// SetStatus sets the "status" field.
func (u *QuotaNetPayoutItemUpsert) SetStatus(v string) *QuotaNetPayoutItemUpsert {
	u.Set(quotanetpayoutitem.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsert) UpdateStatus() *QuotaNetPayoutItemUpsert {
	u.SetExcluded(quotanetpayoutitem.FieldStatus)
	return u
}

// SetTxHash sets the "tx_hash" field.
func (u *QuotaNetPayoutItemUpsert) SetTxHash(v string) *QuotaNetPayoutItemUpsert {
	u.Set(quotanetpayoutitem.FieldTxHash, v)
	return u
}

// UpdateTxHash sets the "tx_hash" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsert) UpdateTxHash() *QuotaNetPayoutItemUpsert {
	u.SetExcluded(quotanetpayoutitem.FieldTxHash)
	return u
}

// ClearTxHash clears the value of the "tx_hash" field.
func (u *QuotaNetPayoutItemUpsert) ClearTxHash() *QuotaNetPayoutItemUpsert {
	u.SetNull(quotanetpayoutitem.FieldTxHash)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *QuotaNetPayoutItemUpsert) SetErrorMessage(v string) *QuotaNetPayoutItemUpsert {
	u.Set(quotanetpayoutitem.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsert) UpdateErrorMessage() *QuotaNetPayoutItemUpsert {
	u.SetExcluded(quotanetpayoutitem.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *QuotaNetPayoutItemUpsert) ClearErrorMessage() *QuotaNetPayoutItemUpsert {
	u.SetNull(quotanetpayoutitem.FieldErrorMessage)
	return u
}

// SetFinalizedAt sets the "finalized_at" field.
func (u *QuotaNetPayoutItemUpsert) SetFinalizedAt(v time.Time) *QuotaNetPayoutItemUpsert {
	u.Set(quotanetpayoutitem.FieldFinalizedAt, v)
	return u
}

// UpdateFinalizedAt sets the "finalized_at" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsert) UpdateFinalizedAt() *QuotaNetPayoutItemUpsert {
	u.SetExcluded(quotanetpayoutitem.FieldFinalizedAt)
	return u
}

// ClearFinalizedAt clears the value of the "finalized_at" field.
func (u *QuotaNetPayoutItemUpsert) ClearFinalizedAt() *QuotaNetPayoutItemUpsert {
	u.SetNull(quotanetpayoutitem.FieldFinalizedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.QuotaNetPayoutItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *QuotaNetPayoutItemUpsertOne) UpdateNewValues() *QuotaNetPayoutItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(quotanetpayoutitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QuotaNetPayoutItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *QuotaNetPayoutItemUpsertOne) Ignore() *QuotaNetPayoutItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuotaNetPayoutItemUpsertOne) DoNothing() *QuotaNetPayoutItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuotaNetPayoutItemCreate.OnConflict
// documentation for more info.
func (u *QuotaNetPayoutItemUpsertOne) Update(set func(*QuotaNetPayoutItemUpsert)) *QuotaNetPayoutItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuotaNetPayoutItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuotaNetPayoutItemUpsertOne) SetUpdatedAt(v time.Time) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertOne) UpdateUpdatedAt() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetItemKey sets the "item_key" field.
func (u *QuotaNetPayoutItemUpsertOne) SetItemKey(v string) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetItemKey(v)
	})
}

// UpdateItemKey sets the "item_key" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertOne) UpdateItemKey() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateItemKey()
	})
}

// SetBatchID sets the "batch_id" field.
func (u *QuotaNetPayoutItemUpsertOne) SetBatchID(v int64) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetBatchID(v)
	})
}

// AddBatchID adds v to the "batch_id" field.
func (u *QuotaNetPayoutItemUpsertOne) AddBatchID(v int64) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.AddBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertOne) UpdateBatchID() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateBatchID()
	})
}

// SetNodeID sets the "node_id" field.
func (u *QuotaNetPayoutItemUpsertOne) SetNodeID(v int64) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetNodeID(v)
	})
}

// AddNodeID adds v to the "node_id" field.
func (u *QuotaNetPayoutItemUpsertOne) AddNodeID(v int64) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.AddNodeID(v)
	})
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertOne) UpdateNodeID() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateNodeID()
	})
}

// ClearNodeID clears the value of the "node_id" field.
func (u *QuotaNetPayoutItemUpsertOne) ClearNodeID() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.ClearNodeID()
	})
}

// SetWalletAddress sets the "wallet_address" field.
func (u *QuotaNetPayoutItemUpsertOne) SetWalletAddress(v string) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetWalletAddress(v)
	})
}

// UpdateWalletAddress sets the "wallet_address" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertOne) UpdateWalletAddress() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateWalletAddress()
	})
}

// SetTokenFlow sets the "token_flow" field.
func (u *QuotaNetPayoutItemUpsertOne) SetTokenFlow(v int64) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetTokenFlow(v)
	})
}

// AddTokenFlow adds v to the "token_flow" field.
func (u *QuotaNetPayoutItemUpsertOne) AddTokenFlow(v int64) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.AddTokenFlow(v)
	})
}

// UpdateTokenFlow sets the "token_flow" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertOne) UpdateTokenFlow() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateTokenFlow()
	})
}

// SetAmountCxs sets the "amount_cxs" field.
func (u *QuotaNetPayoutItemUpsertOne) SetAmountCxs(v float64) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetAmountCxs(v)
	})
}

// AddAmountCxs adds v to the "amount_cxs" field.
func (u *QuotaNetPayoutItemUpsertOne) AddAmountCxs(v float64) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.AddAmountCxs(v)
	})
}

// UpdateAmountCxs sets the "amount_cxs" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertOne) UpdateAmountCxs() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateAmountCxs()
	})
}

// SetStatus sets the "status" field.
func (u *QuotaNetPayoutItemUpsertOne) SetStatus(v string) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertOne) UpdateStatus() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateStatus()
	})
}

// SetTxHash sets the "tx_hash" field.
func (u *QuotaNetPayoutItemUpsertOne) SetTxHash(v string) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetTxHash(v)
	})
}

// UpdateTxHash sets the "tx_hash" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertOne) UpdateTxHash() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateTxHash()
	})
}

// ClearTxHash clears the value of the "tx_hash" field.
func (u *QuotaNetPayoutItemUpsertOne) ClearTxHash() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.ClearTxHash()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *QuotaNetPayoutItemUpsertOne) SetErrorMessage(v string) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertOne) UpdateErrorMessage() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *QuotaNetPayoutItemUpsertOne) ClearErrorMessage() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.ClearErrorMessage()
	})
}

// SetFinalizedAt sets the "finalized_at" field.
func (u *QuotaNetPayoutItemUpsertOne) SetFinalizedAt(v time.Time) *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetFinalizedAt(v)
	})
}

// UpdateFinalizedAt sets the "finalized_at" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertOne) UpdateFinalizedAt() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateFinalizedAt()
	})
}

// ClearFinalizedAt clears the value of the "finalized_at" field.
func (u *QuotaNetPayoutItemUpsertOne) ClearFinalizedAt() *QuotaNetPayoutItemUpsertOne {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.ClearFinalizedAt()
	})
}

// Exec executes the query.
func (u *QuotaNetPayoutItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuotaNetPayoutItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuotaNetPayoutItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *QuotaNetPayoutItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *QuotaNetPayoutItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// QuotaNetPayoutItemCreateBulk is the builder for creating many QuotaNetPayoutItem entities in bulk.
type QuotaNetPayoutItemCreateBulk struct {
	config
	err      error
	builders []*QuotaNetPayoutItemCreate
	conflict []sql.ConflictOption
}

// Save creates the QuotaNetPayoutItem entities in the database.
func (_c *QuotaNetPayoutItemCreateBulk) Save(ctx context.Context) ([]*QuotaNetPayoutItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*QuotaNetPayoutItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuotaNetPayoutItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuotaNetPayoutItemCreateBulk) SaveX(ctx context.Context) []*QuotaNetPayoutItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuotaNetPayoutItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuotaNetPayoutItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QuotaNetPayoutItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuotaNetPayoutItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *QuotaNetPayoutItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *QuotaNetPayoutItemUpsertBulk {
	_c.conflict = opts
	return &QuotaNetPayoutItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QuotaNetPayoutItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuotaNetPayoutItemCreateBulk) OnConflictColumns(columns ...string) *QuotaNetPayoutItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuotaNetPayoutItemUpsertBulk{
		create: _c,
	}
}

// QuotaNetPayoutItemUpsertBulk is the builder for "upsert"-ing
// a bulk of QuotaNetPayoutItem nodes.
type QuotaNetPayoutItemUpsertBulk struct {
	create *QuotaNetPayoutItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.QuotaNetPayoutItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *QuotaNetPayoutItemUpsertBulk) UpdateNewValues() *QuotaNetPayoutItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(quotanetpayoutitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QuotaNetPayoutItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *QuotaNetPayoutItemUpsertBulk) Ignore() *QuotaNetPayoutItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuotaNetPayoutItemUpsertBulk) DoNothing() *QuotaNetPayoutItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuotaNetPayoutItemCreateBulk.OnConflict
// documentation for more info.
func (u *QuotaNetPayoutItemUpsertBulk) Update(set func(*QuotaNetPayoutItemUpsert)) *QuotaNetPayoutItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuotaNetPayoutItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuotaNetPayoutItemUpsertBulk) SetUpdatedAt(v time.Time) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertBulk) UpdateUpdatedAt() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetItemKey sets the "item_key" field.
func (u *QuotaNetPayoutItemUpsertBulk) SetItemKey(v string) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetItemKey(v)
	})
}

// UpdateItemKey sets the "item_key" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertBulk) UpdateItemKey() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateItemKey()
	})
}

// SetBatchID sets the "batch_id" field.
func (u *QuotaNetPayoutItemUpsertBulk) SetBatchID(v int64) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetBatchID(v)
	})
}

// AddBatchID adds v to the "batch_id" field.
func (u *QuotaNetPayoutItemUpsertBulk) AddBatchID(v int64) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.AddBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertBulk) UpdateBatchID() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateBatchID()
	})
}

// SetNodeID sets the "node_id" field.
func (u *QuotaNetPayoutItemUpsertBulk) SetNodeID(v int64) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetNodeID(v)
	})
}

// AddNodeID adds v to the "node_id" field.
func (u *QuotaNetPayoutItemUpsertBulk) AddNodeID(v int64) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.AddNodeID(v)
	})
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertBulk) UpdateNodeID() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateNodeID()
	})
}

// ClearNodeID clears the value of the "node_id" field.
func (u *QuotaNetPayoutItemUpsertBulk) ClearNodeID() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.ClearNodeID()
	})
}

// SetWalletAddress sets the "wallet_address" field.
func (u *QuotaNetPayoutItemUpsertBulk) SetWalletAddress(v string) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetWalletAddress(v)
	})
}

// UpdateWalletAddress sets the "wallet_address" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertBulk) UpdateWalletAddress() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateWalletAddress()
	})
}

// SetTokenFlow sets the "token_flow" field.
func (u *QuotaNetPayoutItemUpsertBulk) SetTokenFlow(v int64) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetTokenFlow(v)
	})
}

// AddTokenFlow adds v to the "token_flow" field.
func (u *QuotaNetPayoutItemUpsertBulk) AddTokenFlow(v int64) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.AddTokenFlow(v)
	})
}

// UpdateTokenFlow sets the "token_flow" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertBulk) UpdateTokenFlow() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateTokenFlow()
	})
}

// SetAmountCxs sets the "amount_cxs" field.
func (u *QuotaNetPayoutItemUpsertBulk) SetAmountCxs(v float64) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetAmountCxs(v)
	})
}

// AddAmountCxs adds v to the "amount_cxs" field.
func (u *QuotaNetPayoutItemUpsertBulk) AddAmountCxs(v float64) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.AddAmountCxs(v)
	})
}

// UpdateAmountCxs sets the "amount_cxs" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertBulk) UpdateAmountCxs() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateAmountCxs()
	})
}

// SetStatus sets the "status" field.
func (u *QuotaNetPayoutItemUpsertBulk) SetStatus(v string) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertBulk) UpdateStatus() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateStatus()
	})
}

// SetTxHash sets the "tx_hash" field.
func (u *QuotaNetPayoutItemUpsertBulk) SetTxHash(v string) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetTxHash(v)
	})
}

// UpdateTxHash sets the "tx_hash" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertBulk) UpdateTxHash() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateTxHash()
	})
}

// ClearTxHash clears the value of the "tx_hash" field.
func (u *QuotaNetPayoutItemUpsertBulk) ClearTxHash() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.ClearTxHash()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *QuotaNetPayoutItemUpsertBulk) SetErrorMessage(v string) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertBulk) UpdateErrorMessage() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *QuotaNetPayoutItemUpsertBulk) ClearErrorMessage() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.ClearErrorMessage()
	})
}

// SetFinalizedAt sets the "finalized_at" field.
func (u *QuotaNetPayoutItemUpsertBulk) SetFinalizedAt(v time.Time) *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.SetFinalizedAt(v)
	})
}

// UpdateFinalizedAt sets the "finalized_at" field to the value that was provided on create.
func (u *QuotaNetPayoutItemUpsertBulk) UpdateFinalizedAt() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.UpdateFinalizedAt()
	})
}

// ClearFinalizedAt clears the value of the "finalized_at" field.
func (u *QuotaNetPayoutItemUpsertBulk) ClearFinalizedAt() *QuotaNetPayoutItemUpsertBulk {
	return u.Update(func(s *QuotaNetPayoutItemUpsert) {
		s.ClearFinalizedAt()
	})
}

// Exec executes the query.
func (u *QuotaNetPayoutItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the QuotaNetPayoutItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuotaNetPayoutItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuotaNetPayoutItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
