// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/quotanetcontributionledger"
)

// QuotaNetContributionLedgerUpdate is the builder for updating QuotaNetContributionLedger entities.
type QuotaNetContributionLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *QuotaNetContributionLedgerMutation
}

// Where appends a list predicates to the QuotaNetContributionLedgerUpdate builder.
func (_u *QuotaNetContributionLedgerUpdate) Where(ps ...predicate.QuotaNetContributionLedger) *QuotaNetContributionLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaNetContributionLedgerUpdate) SetUpdatedAt(v time.Time) *QuotaNetContributionLedgerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *QuotaNetContributionLedgerUpdate) SetTaskID(v string) *QuotaNetContributionLedgerUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableTaskID(v *string) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *QuotaNetContributionLedgerUpdate) SetUsageLogID(v int64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableUsageLogID(v *int64) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *QuotaNetContributionLedgerUpdate) AddUsageLogID(v int64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *QuotaNetContributionLedgerUpdate) ClearUsageLogID() *QuotaNetContributionLedgerUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *QuotaNetContributionLedgerUpdate) SetNodeID(v int64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.ResetNodeID()
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableNodeID(v *int64) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// AddNodeID adds value to the "node_id" field.
func (_u *QuotaNetContributionLedgerUpdate) AddNodeID(v int64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.AddNodeID(v)
	return _u
}

// SetWalletAddress sets the "wallet_address" field.
func (_u *QuotaNetContributionLedgerUpdate) SetWalletAddress(v string) *QuotaNetContributionLedgerUpdate {
	_u.mutation.SetWalletAddress(v)
	return _u
}

// SetNillableWalletAddress sets the "wallet_address" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableWalletAddress(v *string) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetWalletAddress(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *QuotaNetContributionLedgerUpdate) SetAccountID(v int64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableAccountID(v *int64) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *QuotaNetContributionLedgerUpdate) AddAccountID(v int64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *QuotaNetContributionLedgerUpdate) ClearAccountID() *QuotaNetContributionLedgerUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *QuotaNetContributionLedgerUpdate) SetPlatform(v string) *QuotaNetContributionLedgerUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillablePlatform(v *string) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *QuotaNetContributionLedgerUpdate) SetModel(v string) *QuotaNetContributionLedgerUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableModel(v *string) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetTokenFlow sets the "token_flow" field.
func (_u *QuotaNetContributionLedgerUpdate) SetTokenFlow(v int64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.ResetTokenFlow()
	_u.mutation.SetTokenFlow(v)
	return _u
}

// SetNillableTokenFlow sets the "token_flow" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableTokenFlow(v *int64) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetTokenFlow(*v)
	}
	return _u
}

// AddTokenFlow adds value to the "token_flow" field.
func (_u *QuotaNetContributionLedgerUpdate) AddTokenFlow(v int64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.AddTokenFlow(v)
	return _u
}

// SetStandardCostUsd sets the "standard_cost_usd" field.
func (_u *QuotaNetContributionLedgerUpdate) SetStandardCostUsd(v float64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.ResetStandardCostUsd()
	_u.mutation.SetStandardCostUsd(v)
	return _u
}

// SetNillableStandardCostUsd sets the "standard_cost_usd" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableStandardCostUsd(v *float64) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetStandardCostUsd(*v)
	}
	return _u
}

// AddStandardCostUsd adds value to the "standard_cost_usd" field.
func (_u *QuotaNetContributionLedgerUpdate) AddStandardCostUsd(v float64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.AddStandardCostUsd(v)
	return _u
}

// SetActualCostUsd sets the "actual_cost_usd" field.
func (_u *QuotaNetContributionLedgerUpdate) SetActualCostUsd(v float64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.ResetActualCostUsd()
	_u.mutation.SetActualCostUsd(v)
	return _u
}

// SetNillableActualCostUsd sets the "actual_cost_usd" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableActualCostUsd(v *float64) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetActualCostUsd(*v)
	}
	return _u
}

// AddActualCostUsd adds value to the "actual_cost_usd" field.
func (_u *QuotaNetContributionLedgerUpdate) AddActualCostUsd(v float64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.AddActualCostUsd(v)
	return _u
}

// SetContributionUsd sets the "contribution_usd" field.
func (_u *QuotaNetContributionLedgerUpdate) SetContributionUsd(v float64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.ResetContributionUsd()
	_u.mutation.SetContributionUsd(v)
	return _u
}

// SetNillableContributionUsd sets the "contribution_usd" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableContributionUsd(v *float64) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetContributionUsd(*v)
	}
	return _u
}

// AddContributionUsd adds value to the "contribution_usd" field.
func (_u *QuotaNetContributionLedgerUpdate) AddContributionUsd(v float64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.AddContributionUsd(v)
	return _u
}

// SetAmountCxs sets the "amount_cxs" field.
func (_u *QuotaNetContributionLedgerUpdate) SetAmountCxs(v float64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.ResetAmountCxs()
	_u.mutation.SetAmountCxs(v)
	return _u
}

// SetNillableAmountCxs sets the "amount_cxs" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableAmountCxs(v *float64) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetAmountCxs(*v)
	}
	return _u
}

// AddAmountCxs adds value to the "amount_cxs" field.
func (_u *QuotaNetContributionLedgerUpdate) AddAmountCxs(v float64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.AddAmountCxs(v)
	return _u
}

// SetRate sets the "rate" field.
func (_u *QuotaNetContributionLedgerUpdate) SetRate(v float64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.ResetRate()
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableRate(v *float64) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// AddRate adds value to the "rate" field.
func (_u *QuotaNetContributionLedgerUpdate) AddRate(v float64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.AddRate(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaNetContributionLedgerUpdate) SetStatus(v string) *QuotaNetContributionLedgerUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableStatus(v *string) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPayoutBatchID sets the "payout_batch_id" field.
func (_u *QuotaNetContributionLedgerUpdate) SetPayoutBatchID(v int64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.ResetPayoutBatchID()
	_u.mutation.SetPayoutBatchID(v)
	return _u
}

// SetNillablePayoutBatchID sets the "payout_batch_id" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillablePayoutBatchID(v *int64) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetPayoutBatchID(*v)
	}
	return _u
}

// AddPayoutBatchID adds value to the "payout_batch_id" field.
func (_u *QuotaNetContributionLedgerUpdate) AddPayoutBatchID(v int64) *QuotaNetContributionLedgerUpdate {
	_u.mutation.AddPayoutBatchID(v)
	return _u
}

// ClearPayoutBatchID clears the value of the "payout_batch_id" field.
func (_u *QuotaNetContributionLedgerUpdate) ClearPayoutBatchID() *QuotaNetContributionLedgerUpdate {
	_u.mutation.ClearPayoutBatchID()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *QuotaNetContributionLedgerUpdate) SetSettledAt(v time.Time) *QuotaNetContributionLedgerUpdate {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdate) SetNillableSettledAt(v *time.Time) *QuotaNetContributionLedgerUpdate {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *QuotaNetContributionLedgerUpdate) ClearSettledAt() *QuotaNetContributionLedgerUpdate {
	_u.mutation.ClearSettledAt()
	return _u
}

// Mutation returns the QuotaNetContributionLedgerMutation object of the builder.
func (_u *QuotaNetContributionLedgerUpdate) Mutation() *QuotaNetContributionLedgerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuotaNetContributionLedgerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaNetContributionLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuotaNetContributionLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaNetContributionLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaNetContributionLedgerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotanetcontributionledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaNetContributionLedgerUpdate) check() error {
	if v, ok := _u.mutation.TaskID(); ok {
		if err := quotanetcontributionledger.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "QuotaNetContributionLedger.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WalletAddress(); ok {
		if err := quotanetcontributionledger.WalletAddressValidator(v); err != nil {
			return &ValidationError{Name: "wallet_address", err: fmt.Errorf(`ent: validator failed for field "QuotaNetContributionLedger.wallet_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := quotanetcontributionledger.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "QuotaNetContributionLedger.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := quotanetcontributionledger.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "QuotaNetContributionLedger.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotanetcontributionledger.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaNetContributionLedger.status": %w`, err)}
		}
	}
	return nil
}

func (_u *QuotaNetContributionLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotanetcontributionledger.Table, quotanetcontributionledger.Columns, sqlgraph.NewFieldSpec(quotanetcontributionledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotanetcontributionledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(quotanetcontributionledger.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(quotanetcontributionledger.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(quotanetcontributionledger.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(quotanetcontributionledger.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(quotanetcontributionledger.FieldNodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNodeID(); ok {
		_spec.AddField(quotanetcontributionledger.FieldNodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WalletAddress(); ok {
		_spec.SetField(quotanetcontributionledger.FieldWalletAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(quotanetcontributionledger.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(quotanetcontributionledger.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(quotanetcontributionledger.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(quotanetcontributionledger.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(quotanetcontributionledger.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenFlow(); ok {
		_spec.SetField(quotanetcontributionledger.FieldTokenFlow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokenFlow(); ok {
		_spec.AddField(quotanetcontributionledger.FieldTokenFlow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StandardCostUsd(); ok {
		_spec.SetField(quotanetcontributionledger.FieldStandardCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStandardCostUsd(); ok {
		_spec.AddField(quotanetcontributionledger.FieldStandardCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCostUsd(); ok {
		_spec.SetField(quotanetcontributionledger.FieldActualCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCostUsd(); ok {
		_spec.AddField(quotanetcontributionledger.FieldActualCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ContributionUsd(); ok {
		_spec.SetField(quotanetcontributionledger.FieldContributionUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedContributionUsd(); ok {
		_spec.AddField(quotanetcontributionledger.FieldContributionUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountCxs(); ok {
		_spec.SetField(quotanetcontributionledger.FieldAmountCxs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCxs(); ok {
		_spec.AddField(quotanetcontributionledger.FieldAmountCxs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(quotanetcontributionledger.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRate(); ok {
		_spec.AddField(quotanetcontributionledger.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotanetcontributionledger.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayoutBatchID(); ok {
		_spec.SetField(quotanetcontributionledger.FieldPayoutBatchID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPayoutBatchID(); ok {
		_spec.AddField(quotanetcontributionledger.FieldPayoutBatchID, field.TypeInt64, value)
	}
	if _u.mutation.PayoutBatchIDCleared() {
		_spec.ClearField(quotanetcontributionledger.FieldPayoutBatchID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(quotanetcontributionledger.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(quotanetcontributionledger.FieldSettledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotanetcontributionledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuotaNetContributionLedgerUpdateOne is the builder for updating a single QuotaNetContributionLedger entity.
type QuotaNetContributionLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuotaNetContributionLedgerMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetUpdatedAt(v time.Time) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetTaskID(v string) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableTaskID(v *string) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetUsageLogID(v int64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableUsageLogID(v *int64) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *QuotaNetContributionLedgerUpdateOne) AddUsageLogID(v int64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *QuotaNetContributionLedgerUpdateOne) ClearUsageLogID() *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNodeID(v int64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ResetNodeID()
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableNodeID(v *int64) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// AddNodeID adds value to the "node_id" field.
func (_u *QuotaNetContributionLedgerUpdateOne) AddNodeID(v int64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.AddNodeID(v)
	return _u
}

// SetWalletAddress sets the "wallet_address" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetWalletAddress(v string) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.SetWalletAddress(v)
	return _u
}

// SetNillableWalletAddress sets the "wallet_address" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableWalletAddress(v *string) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetWalletAddress(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetAccountID(v int64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableAccountID(v *int64) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *QuotaNetContributionLedgerUpdateOne) AddAccountID(v int64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *QuotaNetContributionLedgerUpdateOne) ClearAccountID() *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetPlatform(v string) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillablePlatform(v *string) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetModel(v string) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableModel(v *string) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetTokenFlow sets the "token_flow" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetTokenFlow(v int64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ResetTokenFlow()
	_u.mutation.SetTokenFlow(v)
	return _u
}

// SetNillableTokenFlow sets the "token_flow" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableTokenFlow(v *int64) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetTokenFlow(*v)
	}
	return _u
}

// AddTokenFlow adds value to the "token_flow" field.
func (_u *QuotaNetContributionLedgerUpdateOne) AddTokenFlow(v int64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.AddTokenFlow(v)
	return _u
}

// SetStandardCostUsd sets the "standard_cost_usd" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetStandardCostUsd(v float64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ResetStandardCostUsd()
	_u.mutation.SetStandardCostUsd(v)
	return _u
}

// SetNillableStandardCostUsd sets the "standard_cost_usd" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableStandardCostUsd(v *float64) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetStandardCostUsd(*v)
	}
	return _u
}

// AddStandardCostUsd adds value to the "standard_cost_usd" field.
func (_u *QuotaNetContributionLedgerUpdateOne) AddStandardCostUsd(v float64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.AddStandardCostUsd(v)
	return _u
}

// SetActualCostUsd sets the "actual_cost_usd" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetActualCostUsd(v float64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ResetActualCostUsd()
	_u.mutation.SetActualCostUsd(v)
	return _u
}

// SetNillableActualCostUsd sets the "actual_cost_usd" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableActualCostUsd(v *float64) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetActualCostUsd(*v)
	}
	return _u
}

// AddActualCostUsd adds value to the "actual_cost_usd" field.
func (_u *QuotaNetContributionLedgerUpdateOne) AddActualCostUsd(v float64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.AddActualCostUsd(v)
	return _u
}

// SetContributionUsd sets the "contribution_usd" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetContributionUsd(v float64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ResetContributionUsd()
	_u.mutation.SetContributionUsd(v)
	return _u
}

// SetNillableContributionUsd sets the "contribution_usd" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableContributionUsd(v *float64) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetContributionUsd(*v)
	}
	return _u
}

// AddContributionUsd adds value to the "contribution_usd" field.
func (_u *QuotaNetContributionLedgerUpdateOne) AddContributionUsd(v float64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.AddContributionUsd(v)
	return _u
}

// SetAmountCxs sets the "amount_cxs" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetAmountCxs(v float64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ResetAmountCxs()
	_u.mutation.SetAmountCxs(v)
	return _u
}

// SetNillableAmountCxs sets the "amount_cxs" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableAmountCxs(v *float64) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetAmountCxs(*v)
	}
	return _u
}

// AddAmountCxs adds value to the "amount_cxs" field.
func (_u *QuotaNetContributionLedgerUpdateOne) AddAmountCxs(v float64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.AddAmountCxs(v)
	return _u
}

// SetRate sets the "rate" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetRate(v float64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ResetRate()
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableRate(v *float64) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// AddRate adds value to the "rate" field.
func (_u *QuotaNetContributionLedgerUpdateOne) AddRate(v float64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.AddRate(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetStatus(v string) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableStatus(v *string) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPayoutBatchID sets the "payout_batch_id" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetPayoutBatchID(v int64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ResetPayoutBatchID()
	_u.mutation.SetPayoutBatchID(v)
	return _u
}

// SetNillablePayoutBatchID sets the "payout_batch_id" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillablePayoutBatchID(v *int64) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetPayoutBatchID(*v)
	}
	return _u
}

// AddPayoutBatchID adds value to the "payout_batch_id" field.
func (_u *QuotaNetContributionLedgerUpdateOne) AddPayoutBatchID(v int64) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.AddPayoutBatchID(v)
	return _u
}

// ClearPayoutBatchID clears the value of the "payout_batch_id" field.
func (_u *QuotaNetContributionLedgerUpdateOne) ClearPayoutBatchID() *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ClearPayoutBatchID()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *QuotaNetContributionLedgerUpdateOne) SetSettledAt(v time.Time) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *QuotaNetContributionLedgerUpdateOne) SetNillableSettledAt(v *time.Time) *QuotaNetContributionLedgerUpdateOne {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *QuotaNetContributionLedgerUpdateOne) ClearSettledAt() *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.ClearSettledAt()
	return _u
}

// Mutation returns the QuotaNetContributionLedgerMutation object of the builder.
func (_u *QuotaNetContributionLedgerUpdateOne) Mutation() *QuotaNetContributionLedgerMutation {
	return _u.mutation
}

// Where appends a list predicates to the QuotaNetContributionLedgerUpdate builder.
func (_u *QuotaNetContributionLedgerUpdateOne) Where(ps ...predicate.QuotaNetContributionLedger) *QuotaNetContributionLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuotaNetContributionLedgerUpdateOne) Select(field string, fields ...string) *QuotaNetContributionLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuotaNetContributionLedger entity.
func (_u *QuotaNetContributionLedgerUpdateOne) Save(ctx context.Context) (*QuotaNetContributionLedger, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaNetContributionLedgerUpdateOne) SaveX(ctx context.Context) *QuotaNetContributionLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuotaNetContributionLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaNetContributionLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaNetContributionLedgerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotanetcontributionledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaNetContributionLedgerUpdateOne) check() error {
	if v, ok := _u.mutation.TaskID(); ok {
		if err := quotanetcontributionledger.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "QuotaNetContributionLedger.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WalletAddress(); ok {
		if err := quotanetcontributionledger.WalletAddressValidator(v); err != nil {
			return &ValidationError{Name: "wallet_address", err: fmt.Errorf(`ent: validator failed for field "QuotaNetContributionLedger.wallet_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := quotanetcontributionledger.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "QuotaNetContributionLedger.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := quotanetcontributionledger.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "QuotaNetContributionLedger.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotanetcontributionledger.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaNetContributionLedger.status": %w`, err)}
		}
	}
	return nil
}

func (_u *QuotaNetContributionLedgerUpdateOne) sqlSave(ctx context.Context) (_node *QuotaNetContributionLedger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotanetcontributionledger.Table, quotanetcontributionledger.Columns, sqlgraph.NewFieldSpec(quotanetcontributionledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuotaNetContributionLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quotanetcontributionledger.FieldID)
		for _, f := range fields {
			if !quotanetcontributionledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quotanetcontributionledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotanetcontributionledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(quotanetcontributionledger.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(quotanetcontributionledger.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(quotanetcontributionledger.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(quotanetcontributionledger.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(quotanetcontributionledger.FieldNodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNodeID(); ok {
		_spec.AddField(quotanetcontributionledger.FieldNodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WalletAddress(); ok {
		_spec.SetField(quotanetcontributionledger.FieldWalletAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(quotanetcontributionledger.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(quotanetcontributionledger.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(quotanetcontributionledger.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(quotanetcontributionledger.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(quotanetcontributionledger.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenFlow(); ok {
		_spec.SetField(quotanetcontributionledger.FieldTokenFlow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokenFlow(); ok {
		_spec.AddField(quotanetcontributionledger.FieldTokenFlow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StandardCostUsd(); ok {
		_spec.SetField(quotanetcontributionledger.FieldStandardCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStandardCostUsd(); ok {
		_spec.AddField(quotanetcontributionledger.FieldStandardCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCostUsd(); ok {
		_spec.SetField(quotanetcontributionledger.FieldActualCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCostUsd(); ok {
		_spec.AddField(quotanetcontributionledger.FieldActualCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ContributionUsd(); ok {
		_spec.SetField(quotanetcontributionledger.FieldContributionUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedContributionUsd(); ok {
		_spec.AddField(quotanetcontributionledger.FieldContributionUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountCxs(); ok {
		_spec.SetField(quotanetcontributionledger.FieldAmountCxs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCxs(); ok {
		_spec.AddField(quotanetcontributionledger.FieldAmountCxs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(quotanetcontributionledger.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRate(); ok {
		_spec.AddField(quotanetcontributionledger.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotanetcontributionledger.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayoutBatchID(); ok {
		_spec.SetField(quotanetcontributionledger.FieldPayoutBatchID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPayoutBatchID(); ok {
		_spec.AddField(quotanetcontributionledger.FieldPayoutBatchID, field.TypeInt64, value)
	}
	if _u.mutation.PayoutBatchIDCleared() {
		_spec.ClearField(quotanetcontributionledger.FieldPayoutBatchID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(quotanetcontributionledger.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(quotanetcontributionledger.FieldSettledAt, field.TypeTime)
	}
	_node = &QuotaNetContributionLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotanetcontributionledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
