// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/quotanetnodesession"
)

// QuotaNetNodeSession is the model entity for the QuotaNetNodeSession schema.
type QuotaNetNodeSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID int64 `json:"node_id,omitempty"`
	// InstanceID holds the value of the "instance_id" field.
	InstanceID string `json:"instance_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RemoteAddr holds the value of the "remote_addr" field.
	RemoteAddr *string `json:"remote_addr,omitempty"`
	// MaxConcurrency holds the value of the "max_concurrency" field.
	MaxConcurrency int `json:"max_concurrency,omitempty"`
	// CurrentConcurrency holds the value of the "current_concurrency" field.
	CurrentConcurrency int `json:"current_concurrency,omitempty"`
	// QueueSize holds the value of the "queue_size" field.
	QueueSize int `json:"queue_size,omitempty"`
	// MaxQueueSize holds the value of the "max_queue_size" field.
	MaxQueueSize int `json:"max_queue_size,omitempty"`
	// Capabilities holds the value of the "capabilities" field.
	Capabilities map[string]interface{} `json:"capabilities,omitempty"`
	// ConnectedAt holds the value of the "connected_at" field.
	ConnectedAt time.Time `json:"connected_at,omitempty"`
	// DisconnectedAt holds the value of the "disconnected_at" field.
	DisconnectedAt *time.Time `json:"disconnected_at,omitempty"`
	// LastHeartbeatAt holds the value of the "last_heartbeat_at" field.
	LastHeartbeatAt *time.Time `json:"last_heartbeat_at,omitempty"`
	// CloseReason holds the value of the "close_reason" field.
	CloseReason  *string `json:"close_reason,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QuotaNetNodeSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quotanetnodesession.FieldCapabilities:
			values[i] = new([]byte)
		case quotanetnodesession.FieldID, quotanetnodesession.FieldNodeID, quotanetnodesession.FieldMaxConcurrency, quotanetnodesession.FieldCurrentConcurrency, quotanetnodesession.FieldQueueSize, quotanetnodesession.FieldMaxQueueSize:
			values[i] = new(sql.NullInt64)
		case quotanetnodesession.FieldSessionID, quotanetnodesession.FieldInstanceID, quotanetnodesession.FieldStatus, quotanetnodesession.FieldRemoteAddr, quotanetnodesession.FieldCloseReason:
			values[i] = new(sql.NullString)
		case quotanetnodesession.FieldCreatedAt, quotanetnodesession.FieldUpdatedAt, quotanetnodesession.FieldConnectedAt, quotanetnodesession.FieldDisconnectedAt, quotanetnodesession.FieldLastHeartbeatAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QuotaNetNodeSession fields.
func (_m *QuotaNetNodeSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quotanetnodesession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case quotanetnodesession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case quotanetnodesession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case quotanetnodesession.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case quotanetnodesession.FieldNodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = value.Int64
			}
		case quotanetnodesession.FieldInstanceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field instance_id", values[i])
			} else if value.Valid {
				_m.InstanceID = value.String
			}
		case quotanetnodesession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case quotanetnodesession.FieldRemoteAddr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_addr", values[i])
			} else if value.Valid {
				_m.RemoteAddr = new(string)
				*_m.RemoteAddr = value.String
			}
		case quotanetnodesession.FieldMaxConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_concurrency", values[i])
			} else if value.Valid {
				_m.MaxConcurrency = int(value.Int64)
			}
		case quotanetnodesession.FieldCurrentConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_concurrency", values[i])
			} else if value.Valid {
				_m.CurrentConcurrency = int(value.Int64)
			}
		case quotanetnodesession.FieldQueueSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field queue_size", values[i])
			} else if value.Valid {
				_m.QueueSize = int(value.Int64)
			}
		case quotanetnodesession.FieldMaxQueueSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_queue_size", values[i])
			} else if value.Valid {
				_m.MaxQueueSize = int(value.Int64)
			}
		case quotanetnodesession.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		case quotanetnodesession.FieldConnectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field connected_at", values[i])
			} else if value.Valid {
				_m.ConnectedAt = value.Time
			}
		case quotanetnodesession.FieldDisconnectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field disconnected_at", values[i])
			} else if value.Valid {
				_m.DisconnectedAt = new(time.Time)
				*_m.DisconnectedAt = value.Time
			}
		case quotanetnodesession.FieldLastHeartbeatAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_heartbeat_at", values[i])
			} else if value.Valid {
				_m.LastHeartbeatAt = new(time.Time)
				*_m.LastHeartbeatAt = value.Time
			}
		case quotanetnodesession.FieldCloseReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field close_reason", values[i])
			} else if value.Valid {
				_m.CloseReason = new(string)
				*_m.CloseReason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QuotaNetNodeSession.
// This includes values selected through modifiers, order, etc.
func (_m *QuotaNetNodeSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this QuotaNetNodeSession.
// Note that you need to call QuotaNetNodeSession.Unwrap() before calling this method if this QuotaNetNodeSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *QuotaNetNodeSession) Update() *QuotaNetNodeSessionUpdateOne {
	return NewQuotaNetNodeSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the QuotaNetNodeSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *QuotaNetNodeSession) Unwrap() *QuotaNetNodeSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: QuotaNetNodeSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *QuotaNetNodeSession) String() string {
	var builder strings.Builder
	builder.WriteString("QuotaNetNodeSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("node_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeID))
	builder.WriteString(", ")
	builder.WriteString("instance_id=")
	builder.WriteString(_m.InstanceID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.RemoteAddr; v != nil {
		builder.WriteString("remote_addr=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("max_concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxConcurrency))
	builder.WriteString(", ")
	builder.WriteString("current_concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentConcurrency))
	builder.WriteString(", ")
	builder.WriteString("queue_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.QueueSize))
	builder.WriteString(", ")
	builder.WriteString("max_queue_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxQueueSize))
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteString(", ")
	builder.WriteString("connected_at=")
	builder.WriteString(_m.ConnectedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DisconnectedAt; v != nil {
		builder.WriteString("disconnected_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastHeartbeatAt; v != nil {
		builder.WriteString("last_heartbeat_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CloseReason; v != nil {
		builder.WriteString("close_reason=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// QuotaNetNodeSessions is a parsable slice of QuotaNetNodeSession.
type QuotaNetNodeSessions []*QuotaNetNodeSession
