// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/quotanettask"
)

// QuotaNetTaskUpdate is the builder for updating QuotaNetTask entities.
type QuotaNetTaskUpdate struct {
	config
	hooks    []Hook
	mutation *QuotaNetTaskMutation
}

// Where appends a list predicates to the QuotaNetTaskUpdate builder.
func (_u *QuotaNetTaskUpdate) Where(ps ...predicate.QuotaNetTask) *QuotaNetTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaNetTaskUpdate) SetUpdatedAt(v time.Time) *QuotaNetTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *QuotaNetTaskUpdate) SetTaskID(v string) *QuotaNetTaskUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableTaskID(v *string) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *QuotaNetTaskUpdate) SetRequestID(v string) *QuotaNetTaskUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableRequestID(v *string) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *QuotaNetTaskUpdate) SetUserID(v int64) *QuotaNetTaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableUserID(v *int64) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *QuotaNetTaskUpdate) AddUserID(v int64) *QuotaNetTaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *QuotaNetTaskUpdate) ClearUserID() *QuotaNetTaskUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *QuotaNetTaskUpdate) SetAPIKeyID(v int64) *QuotaNetTaskUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableAPIKeyID(v *int64) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *QuotaNetTaskUpdate) AddAPIKeyID(v int64) *QuotaNetTaskUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *QuotaNetTaskUpdate) ClearAPIKeyID() *QuotaNetTaskUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *QuotaNetTaskUpdate) SetGroupID(v int64) *QuotaNetTaskUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableGroupID(v *int64) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *QuotaNetTaskUpdate) AddGroupID(v int64) *QuotaNetTaskUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *QuotaNetTaskUpdate) ClearGroupID() *QuotaNetTaskUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *QuotaNetTaskUpdate) SetAccountID(v int64) *QuotaNetTaskUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableAccountID(v *int64) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *QuotaNetTaskUpdate) AddAccountID(v int64) *QuotaNetTaskUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *QuotaNetTaskUpdate) ClearAccountID() *QuotaNetTaskUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *QuotaNetTaskUpdate) SetNodeID(v int64) *QuotaNetTaskUpdate {
	_u.mutation.ResetNodeID()
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableNodeID(v *int64) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// AddNodeID adds value to the "node_id" field.
func (_u *QuotaNetTaskUpdate) AddNodeID(v int64) *QuotaNetTaskUpdate {
	_u.mutation.AddNodeID(v)
	return _u
}

// ClearNodeID clears the value of the "node_id" field.
func (_u *QuotaNetTaskUpdate) ClearNodeID() *QuotaNetTaskUpdate {
	_u.mutation.ClearNodeID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *QuotaNetTaskUpdate) SetSessionID(v string) *QuotaNetTaskUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableSessionID(v *string) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *QuotaNetTaskUpdate) ClearSessionID() *QuotaNetTaskUpdate {
	_u.mutation.ClearSessionID()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *QuotaNetTaskUpdate) SetPlatform(v string) *QuotaNetTaskUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillablePlatform(v *string) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *QuotaNetTaskUpdate) SetEndpoint(v string) *QuotaNetTaskUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableEndpoint(v *string) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *QuotaNetTaskUpdate) SetModel(v string) *QuotaNetTaskUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableModel(v *string) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetStream sets the "stream" field.
func (_u *QuotaNetTaskUpdate) SetStream(v bool) *QuotaNetTaskUpdate {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableStream(v *bool) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaNetTaskUpdate) SetStatus(v string) *QuotaNetTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableStatus(v *string) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *QuotaNetTaskUpdate) SetErrorCode(v string) *QuotaNetTaskUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableErrorCode(v *string) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *QuotaNetTaskUpdate) ClearErrorCode() *QuotaNetTaskUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *QuotaNetTaskUpdate) SetErrorMessage(v string) *QuotaNetTaskUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableErrorMessage(v *string) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *QuotaNetTaskUpdate) ClearErrorMessage() *QuotaNetTaskUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetPromptTokens sets the "prompt_tokens" field.
func (_u *QuotaNetTaskUpdate) SetPromptTokens(v int) *QuotaNetTaskUpdate {
	_u.mutation.ResetPromptTokens()
	_u.mutation.SetPromptTokens(v)
	return _u
}

// SetNillablePromptTokens sets the "prompt_tokens" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillablePromptTokens(v *int) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetPromptTokens(*v)
	}
	return _u
}

// AddPromptTokens adds value to the "prompt_tokens" field.
func (_u *QuotaNetTaskUpdate) AddPromptTokens(v int) *QuotaNetTaskUpdate {
	_u.mutation.AddPromptTokens(v)
	return _u
}

// SetCompletionTokens sets the "completion_tokens" field.
func (_u *QuotaNetTaskUpdate) SetCompletionTokens(v int) *QuotaNetTaskUpdate {
	_u.mutation.ResetCompletionTokens()
	_u.mutation.SetCompletionTokens(v)
	return _u
}

// SetNillableCompletionTokens sets the "completion_tokens" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableCompletionTokens(v *int) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetCompletionTokens(*v)
	}
	return _u
}

// AddCompletionTokens adds value to the "completion_tokens" field.
func (_u *QuotaNetTaskUpdate) AddCompletionTokens(v int) *QuotaNetTaskUpdate {
	_u.mutation.AddCompletionTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *QuotaNetTaskUpdate) SetTotalTokens(v int) *QuotaNetTaskUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableTotalTokens(v *int) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *QuotaNetTaskUpdate) AddTotalTokens(v int) *QuotaNetTaskUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (_u *QuotaNetTaskUpdate) SetFirstTokenMs(v int) *QuotaNetTaskUpdate {
	_u.mutation.ResetFirstTokenMs()
	_u.mutation.SetFirstTokenMs(v)
	return _u
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableFirstTokenMs(v *int) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetFirstTokenMs(*v)
	}
	return _u
}

// AddFirstTokenMs adds value to the "first_token_ms" field.
func (_u *QuotaNetTaskUpdate) AddFirstTokenMs(v int) *QuotaNetTaskUpdate {
	_u.mutation.AddFirstTokenMs(v)
	return _u
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (_u *QuotaNetTaskUpdate) ClearFirstTokenMs() *QuotaNetTaskUpdate {
	_u.mutation.ClearFirstTokenMs()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *QuotaNetTaskUpdate) SetDurationMs(v int) *QuotaNetTaskUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableDurationMs(v *int) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *QuotaNetTaskUpdate) AddDurationMs(v int) *QuotaNetTaskUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *QuotaNetTaskUpdate) ClearDurationMs() *QuotaNetTaskUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetDispatchedAt sets the "dispatched_at" field.
func (_u *QuotaNetTaskUpdate) SetDispatchedAt(v time.Time) *QuotaNetTaskUpdate {
	_u.mutation.SetDispatchedAt(v)
	return _u
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableDispatchedAt(v *time.Time) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetDispatchedAt(*v)
	}
	return _u
}

// ClearDispatchedAt clears the value of the "dispatched_at" field.
func (_u *QuotaNetTaskUpdate) ClearDispatchedAt() *QuotaNetTaskUpdate {
	_u.mutation.ClearDispatchedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *QuotaNetTaskUpdate) SetCompletedAt(v time.Time) *QuotaNetTaskUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *QuotaNetTaskUpdate) SetNillableCompletedAt(v *time.Time) *QuotaNetTaskUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *QuotaNetTaskUpdate) ClearCompletedAt() *QuotaNetTaskUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the QuotaNetTaskMutation object of the builder.
func (_u *QuotaNetTaskUpdate) Mutation() *QuotaNetTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuotaNetTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaNetTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuotaNetTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaNetTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaNetTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotanettask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaNetTaskUpdate) check() error {
	if v, ok := _u.mutation.TaskID(); ok {
		if err := quotanettask.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := quotanettask.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := quotanettask.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := quotanettask.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := quotanettask.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := quotanettask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotanettask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := quotanettask.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *QuotaNetTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotanettask.Table, quotanettask.Columns, sqlgraph.NewFieldSpec(quotanettask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotanettask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(quotanettask.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(quotanettask.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(quotanettask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(quotanettask.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(quotanettask.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(quotanettask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(quotanettask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(quotanettask.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(quotanettask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(quotanettask.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(quotanettask.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(quotanettask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(quotanettask.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(quotanettask.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(quotanettask.FieldNodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNodeID(); ok {
		_spec.AddField(quotanettask.FieldNodeID, field.TypeInt64, value)
	}
	if _u.mutation.NodeIDCleared() {
		_spec.ClearField(quotanettask.FieldNodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(quotanettask.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(quotanettask.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(quotanettask.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(quotanettask.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(quotanettask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(quotanettask.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotanettask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(quotanettask.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(quotanettask.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(quotanettask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(quotanettask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.PromptTokens(); ok {
		_spec.SetField(quotanettask.FieldPromptTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPromptTokens(); ok {
		_spec.AddField(quotanettask.FieldPromptTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletionTokens(); ok {
		_spec.SetField(quotanettask.FieldCompletionTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompletionTokens(); ok {
		_spec.AddField(quotanettask.FieldCompletionTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(quotanettask.FieldTotalTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(quotanettask.FieldTotalTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FirstTokenMs(); ok {
		_spec.SetField(quotanettask.FieldFirstTokenMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFirstTokenMs(); ok {
		_spec.AddField(quotanettask.FieldFirstTokenMs, field.TypeInt, value)
	}
	if _u.mutation.FirstTokenMsCleared() {
		_spec.ClearField(quotanettask.FieldFirstTokenMs, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(quotanettask.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(quotanettask.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(quotanettask.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.DispatchedAt(); ok {
		_spec.SetField(quotanettask.FieldDispatchedAt, field.TypeTime, value)
	}
	if _u.mutation.DispatchedAtCleared() {
		_spec.ClearField(quotanettask.FieldDispatchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(quotanettask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(quotanettask.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotanettask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuotaNetTaskUpdateOne is the builder for updating a single QuotaNetTask entity.
type QuotaNetTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuotaNetTaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaNetTaskUpdateOne) SetUpdatedAt(v time.Time) *QuotaNetTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *QuotaNetTaskUpdateOne) SetTaskID(v string) *QuotaNetTaskUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableTaskID(v *string) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *QuotaNetTaskUpdateOne) SetRequestID(v string) *QuotaNetTaskUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableRequestID(v *string) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *QuotaNetTaskUpdateOne) SetUserID(v int64) *QuotaNetTaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableUserID(v *int64) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *QuotaNetTaskUpdateOne) AddUserID(v int64) *QuotaNetTaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *QuotaNetTaskUpdateOne) ClearUserID() *QuotaNetTaskUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *QuotaNetTaskUpdateOne) SetAPIKeyID(v int64) *QuotaNetTaskUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableAPIKeyID(v *int64) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *QuotaNetTaskUpdateOne) AddAPIKeyID(v int64) *QuotaNetTaskUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *QuotaNetTaskUpdateOne) ClearAPIKeyID() *QuotaNetTaskUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *QuotaNetTaskUpdateOne) SetGroupID(v int64) *QuotaNetTaskUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableGroupID(v *int64) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *QuotaNetTaskUpdateOne) AddGroupID(v int64) *QuotaNetTaskUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *QuotaNetTaskUpdateOne) ClearGroupID() *QuotaNetTaskUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *QuotaNetTaskUpdateOne) SetAccountID(v int64) *QuotaNetTaskUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableAccountID(v *int64) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *QuotaNetTaskUpdateOne) AddAccountID(v int64) *QuotaNetTaskUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *QuotaNetTaskUpdateOne) ClearAccountID() *QuotaNetTaskUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *QuotaNetTaskUpdateOne) SetNodeID(v int64) *QuotaNetTaskUpdateOne {
	_u.mutation.ResetNodeID()
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableNodeID(v *int64) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// AddNodeID adds value to the "node_id" field.
func (_u *QuotaNetTaskUpdateOne) AddNodeID(v int64) *QuotaNetTaskUpdateOne {
	_u.mutation.AddNodeID(v)
	return _u
}

// ClearNodeID clears the value of the "node_id" field.
func (_u *QuotaNetTaskUpdateOne) ClearNodeID() *QuotaNetTaskUpdateOne {
	_u.mutation.ClearNodeID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *QuotaNetTaskUpdateOne) SetSessionID(v string) *QuotaNetTaskUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableSessionID(v *string) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *QuotaNetTaskUpdateOne) ClearSessionID() *QuotaNetTaskUpdateOne {
	_u.mutation.ClearSessionID()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *QuotaNetTaskUpdateOne) SetPlatform(v string) *QuotaNetTaskUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillablePlatform(v *string) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *QuotaNetTaskUpdateOne) SetEndpoint(v string) *QuotaNetTaskUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableEndpoint(v *string) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *QuotaNetTaskUpdateOne) SetModel(v string) *QuotaNetTaskUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableModel(v *string) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetStream sets the "stream" field.
func (_u *QuotaNetTaskUpdateOne) SetStream(v bool) *QuotaNetTaskUpdateOne {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableStream(v *bool) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaNetTaskUpdateOne) SetStatus(v string) *QuotaNetTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableStatus(v *string) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *QuotaNetTaskUpdateOne) SetErrorCode(v string) *QuotaNetTaskUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableErrorCode(v *string) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *QuotaNetTaskUpdateOne) ClearErrorCode() *QuotaNetTaskUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *QuotaNetTaskUpdateOne) SetErrorMessage(v string) *QuotaNetTaskUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableErrorMessage(v *string) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *QuotaNetTaskUpdateOne) ClearErrorMessage() *QuotaNetTaskUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetPromptTokens sets the "prompt_tokens" field.
func (_u *QuotaNetTaskUpdateOne) SetPromptTokens(v int) *QuotaNetTaskUpdateOne {
	_u.mutation.ResetPromptTokens()
	_u.mutation.SetPromptTokens(v)
	return _u
}

// SetNillablePromptTokens sets the "prompt_tokens" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillablePromptTokens(v *int) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetPromptTokens(*v)
	}
	return _u
}

// AddPromptTokens adds value to the "prompt_tokens" field.
func (_u *QuotaNetTaskUpdateOne) AddPromptTokens(v int) *QuotaNetTaskUpdateOne {
	_u.mutation.AddPromptTokens(v)
	return _u
}

// SetCompletionTokens sets the "completion_tokens" field.
func (_u *QuotaNetTaskUpdateOne) SetCompletionTokens(v int) *QuotaNetTaskUpdateOne {
	_u.mutation.ResetCompletionTokens()
	_u.mutation.SetCompletionTokens(v)
	return _u
}

// SetNillableCompletionTokens sets the "completion_tokens" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableCompletionTokens(v *int) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetCompletionTokens(*v)
	}
	return _u
}

// AddCompletionTokens adds value to the "completion_tokens" field.
func (_u *QuotaNetTaskUpdateOne) AddCompletionTokens(v int) *QuotaNetTaskUpdateOne {
	_u.mutation.AddCompletionTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *QuotaNetTaskUpdateOne) SetTotalTokens(v int) *QuotaNetTaskUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableTotalTokens(v *int) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *QuotaNetTaskUpdateOne) AddTotalTokens(v int) *QuotaNetTaskUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (_u *QuotaNetTaskUpdateOne) SetFirstTokenMs(v int) *QuotaNetTaskUpdateOne {
	_u.mutation.ResetFirstTokenMs()
	_u.mutation.SetFirstTokenMs(v)
	return _u
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableFirstTokenMs(v *int) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetFirstTokenMs(*v)
	}
	return _u
}

// AddFirstTokenMs adds value to the "first_token_ms" field.
func (_u *QuotaNetTaskUpdateOne) AddFirstTokenMs(v int) *QuotaNetTaskUpdateOne {
	_u.mutation.AddFirstTokenMs(v)
	return _u
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (_u *QuotaNetTaskUpdateOne) ClearFirstTokenMs() *QuotaNetTaskUpdateOne {
	_u.mutation.ClearFirstTokenMs()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *QuotaNetTaskUpdateOne) SetDurationMs(v int) *QuotaNetTaskUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableDurationMs(v *int) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *QuotaNetTaskUpdateOne) AddDurationMs(v int) *QuotaNetTaskUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *QuotaNetTaskUpdateOne) ClearDurationMs() *QuotaNetTaskUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetDispatchedAt sets the "dispatched_at" field.
func (_u *QuotaNetTaskUpdateOne) SetDispatchedAt(v time.Time) *QuotaNetTaskUpdateOne {
	_u.mutation.SetDispatchedAt(v)
	return _u
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableDispatchedAt(v *time.Time) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetDispatchedAt(*v)
	}
	return _u
}

// ClearDispatchedAt clears the value of the "dispatched_at" field.
func (_u *QuotaNetTaskUpdateOne) ClearDispatchedAt() *QuotaNetTaskUpdateOne {
	_u.mutation.ClearDispatchedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *QuotaNetTaskUpdateOne) SetCompletedAt(v time.Time) *QuotaNetTaskUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *QuotaNetTaskUpdateOne) SetNillableCompletedAt(v *time.Time) *QuotaNetTaskUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *QuotaNetTaskUpdateOne) ClearCompletedAt() *QuotaNetTaskUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the QuotaNetTaskMutation object of the builder.
func (_u *QuotaNetTaskUpdateOne) Mutation() *QuotaNetTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the QuotaNetTaskUpdate builder.
func (_u *QuotaNetTaskUpdateOne) Where(ps ...predicate.QuotaNetTask) *QuotaNetTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuotaNetTaskUpdateOne) Select(field string, fields ...string) *QuotaNetTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuotaNetTask entity.
func (_u *QuotaNetTaskUpdateOne) Save(ctx context.Context) (*QuotaNetTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaNetTaskUpdateOne) SaveX(ctx context.Context) *QuotaNetTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuotaNetTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaNetTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaNetTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotanettask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaNetTaskUpdateOne) check() error {
	if v, ok := _u.mutation.TaskID(); ok {
		if err := quotanettask.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := quotanettask.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := quotanettask.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := quotanettask.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := quotanettask.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := quotanettask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotanettask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := quotanettask.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "QuotaNetTask.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *QuotaNetTaskUpdateOne) sqlSave(ctx context.Context) (_node *QuotaNetTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotanettask.Table, quotanettask.Columns, sqlgraph.NewFieldSpec(quotanettask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuotaNetTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quotanettask.FieldID)
		for _, f := range fields {
			if !quotanettask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quotanettask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotanettask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(quotanettask.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(quotanettask.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(quotanettask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(quotanettask.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(quotanettask.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(quotanettask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(quotanettask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(quotanettask.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(quotanettask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(quotanettask.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(quotanettask.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(quotanettask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(quotanettask.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(quotanettask.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(quotanettask.FieldNodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNodeID(); ok {
		_spec.AddField(quotanettask.FieldNodeID, field.TypeInt64, value)
	}
	if _u.mutation.NodeIDCleared() {
		_spec.ClearField(quotanettask.FieldNodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(quotanettask.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(quotanettask.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(quotanettask.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(quotanettask.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(quotanettask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(quotanettask.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotanettask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(quotanettask.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(quotanettask.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(quotanettask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(quotanettask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.PromptTokens(); ok {
		_spec.SetField(quotanettask.FieldPromptTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPromptTokens(); ok {
		_spec.AddField(quotanettask.FieldPromptTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletionTokens(); ok {
		_spec.SetField(quotanettask.FieldCompletionTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompletionTokens(); ok {
		_spec.AddField(quotanettask.FieldCompletionTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(quotanettask.FieldTotalTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(quotanettask.FieldTotalTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FirstTokenMs(); ok {
		_spec.SetField(quotanettask.FieldFirstTokenMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFirstTokenMs(); ok {
		_spec.AddField(quotanettask.FieldFirstTokenMs, field.TypeInt, value)
	}
	if _u.mutation.FirstTokenMsCleared() {
		_spec.ClearField(quotanettask.FieldFirstTokenMs, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(quotanettask.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(quotanettask.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(quotanettask.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.DispatchedAt(); ok {
		_spec.SetField(quotanettask.FieldDispatchedAt, field.TypeTime, value)
	}
	if _u.mutation.DispatchedAtCleared() {
		_spec.ClearField(quotanettask.FieldDispatchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(quotanettask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(quotanettask.FieldCompletedAt, field.TypeTime)
	}
	_node = &QuotaNetTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotanettask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
