// Code generated by ent, DO NOT EDIT.

package quotanettaskevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldEQ(FieldTaskID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldEQ(FieldEventType, v))
}

// Sequence applies equality check predicate on the "sequence" field. It's identical to SequenceEQ.
func Sequence(v int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldEQ(FieldSequence, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDContains applies the Contains predicate on the "task_id" field.
func TaskIDContains(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldContains(FieldTaskID, v))
}

// TaskIDHasPrefix applies the HasPrefix predicate on the "task_id" field.
func TaskIDHasPrefix(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldHasPrefix(FieldTaskID, v))
}

// TaskIDHasSuffix applies the HasSuffix predicate on the "task_id" field.
func TaskIDHasSuffix(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldHasSuffix(FieldTaskID, v))
}

// TaskIDEqualFold applies the EqualFold predicate on the "task_id" field.
func TaskIDEqualFold(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldEqualFold(FieldTaskID, v))
}

// TaskIDContainsFold applies the ContainsFold predicate on the "task_id" field.
func TaskIDContainsFold(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldContainsFold(FieldTaskID, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldContainsFold(FieldEventType, v))
}

// SequenceEQ applies the EQ predicate on the "sequence" field.
func SequenceEQ(v int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldEQ(FieldSequence, v))
}

// SequenceNEQ applies the NEQ predicate on the "sequence" field.
func SequenceNEQ(v int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldNEQ(FieldSequence, v))
}

// SequenceIn applies the In predicate on the "sequence" field.
func SequenceIn(vs ...int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldIn(FieldSequence, vs...))
}

// SequenceNotIn applies the NotIn predicate on the "sequence" field.
func SequenceNotIn(vs ...int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldNotIn(FieldSequence, vs...))
}

// SequenceGT applies the GT predicate on the "sequence" field.
func SequenceGT(v int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldGT(FieldSequence, v))
}

// SequenceGTE applies the GTE predicate on the "sequence" field.
func SequenceGTE(v int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldGTE(FieldSequence, v))
}

// SequenceLT applies the LT predicate on the "sequence" field.
func SequenceLT(v int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldLT(FieldSequence, v))
}

// SequenceLTE applies the LTE predicate on the "sequence" field.
func SequenceLTE(v int64) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldLTE(FieldSequence, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuotaNetTaskEvent) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuotaNetTaskEvent) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuotaNetTaskEvent) predicate.QuotaNetTaskEvent {
	return predicate.QuotaNetTaskEvent(sql.NotPredicates(p))
}
