// Code generated by ent, DO NOT EDIT.

package quotanetpayoutbatch

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldUpdatedAt, v))
}

// BatchKey applies equality check predicate on the "batch_key" field. It's identical to BatchKeyEQ.
func BatchKey(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldBatchKey, v))
}

// WindowStart applies equality check predicate on the "window_start" field. It's identical to WindowStartEQ.
func WindowStart(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldWindowStart, v))
}

// WindowEnd applies equality check predicate on the "window_end" field. It's identical to WindowEndEQ.
func WindowEnd(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldWindowEnd, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldStatus, v))
}

// Network applies equality check predicate on the "network" field. It's identical to NetworkEQ.
func Network(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldNetwork, v))
}

// TotalTokenFlow applies equality check predicate on the "total_token_flow" field. It's identical to TotalTokenFlowEQ.
func TotalTokenFlow(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldTotalTokenFlow, v))
}

// TotalContributionUsd applies equality check predicate on the "total_contribution_usd" field. It's identical to TotalContributionUsdEQ.
func TotalContributionUsd(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldTotalContributionUsd, v))
}

// TotalAmountCxs applies equality check predicate on the "total_amount_cxs" field. It's identical to TotalAmountCxsEQ.
func TotalAmountCxs(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldTotalAmountCxs, v))
}

// ItemCount applies equality check predicate on the "item_count" field. It's identical to ItemCountEQ.
func ItemCount(v int) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldItemCount, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldCreatedBy, v))
}

// ApprovedBy applies equality check predicate on the "approved_by" field. It's identical to ApprovedByEQ.
func ApprovedBy(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldApprovedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldUpdatedAt, v))
}

// BatchKeyEQ applies the EQ predicate on the "batch_key" field.
func BatchKeyEQ(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldBatchKey, v))
}

// BatchKeyNEQ applies the NEQ predicate on the "batch_key" field.
func BatchKeyNEQ(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldBatchKey, v))
}

// BatchKeyIn applies the In predicate on the "batch_key" field.
func BatchKeyIn(vs ...string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldBatchKey, vs...))
}

// BatchKeyNotIn applies the NotIn predicate on the "batch_key" field.
func BatchKeyNotIn(vs ...string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldBatchKey, vs...))
}

// BatchKeyGT applies the GT predicate on the "batch_key" field.
func BatchKeyGT(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldBatchKey, v))
}

// BatchKeyGTE applies the GTE predicate on the "batch_key" field.
func BatchKeyGTE(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldBatchKey, v))
}

// BatchKeyLT applies the LT predicate on the "batch_key" field.
func BatchKeyLT(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldBatchKey, v))
}

// BatchKeyLTE applies the LTE predicate on the "batch_key" field.
func BatchKeyLTE(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldBatchKey, v))
}

// BatchKeyContains applies the Contains predicate on the "batch_key" field.
func BatchKeyContains(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldContains(FieldBatchKey, v))
}

// BatchKeyHasPrefix applies the HasPrefix predicate on the "batch_key" field.
func BatchKeyHasPrefix(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldHasPrefix(FieldBatchKey, v))
}

// BatchKeyHasSuffix applies the HasSuffix predicate on the "batch_key" field.
func BatchKeyHasSuffix(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldHasSuffix(FieldBatchKey, v))
}

// BatchKeyEqualFold applies the EqualFold predicate on the "batch_key" field.
func BatchKeyEqualFold(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEqualFold(FieldBatchKey, v))
}

// BatchKeyContainsFold applies the ContainsFold predicate on the "batch_key" field.
func BatchKeyContainsFold(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldContainsFold(FieldBatchKey, v))
}

// WindowStartEQ applies the EQ predicate on the "window_start" field.
func WindowStartEQ(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldWindowStart, v))
}

// WindowStartNEQ applies the NEQ predicate on the "window_start" field.
func WindowStartNEQ(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldWindowStart, v))
}

// WindowStartIn applies the In predicate on the "window_start" field.
func WindowStartIn(vs ...time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldWindowStart, vs...))
}

// WindowStartNotIn applies the NotIn predicate on the "window_start" field.
func WindowStartNotIn(vs ...time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldWindowStart, vs...))
}

// WindowStartGT applies the GT predicate on the "window_start" field.
func WindowStartGT(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldWindowStart, v))
}

// WindowStartGTE applies the GTE predicate on the "window_start" field.
func WindowStartGTE(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldWindowStart, v))
}

// WindowStartLT applies the LT predicate on the "window_start" field.
func WindowStartLT(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldWindowStart, v))
}

// WindowStartLTE applies the LTE predicate on the "window_start" field.
func WindowStartLTE(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldWindowStart, v))
}

// WindowEndEQ applies the EQ predicate on the "window_end" field.
func WindowEndEQ(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldWindowEnd, v))
}

// WindowEndNEQ applies the NEQ predicate on the "window_end" field.
func WindowEndNEQ(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldWindowEnd, v))
}

// WindowEndIn applies the In predicate on the "window_end" field.
func WindowEndIn(vs ...time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldWindowEnd, vs...))
}

// WindowEndNotIn applies the NotIn predicate on the "window_end" field.
func WindowEndNotIn(vs ...time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldWindowEnd, vs...))
}

// WindowEndGT applies the GT predicate on the "window_end" field.
func WindowEndGT(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldWindowEnd, v))
}

// WindowEndGTE applies the GTE predicate on the "window_end" field.
func WindowEndGTE(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldWindowEnd, v))
}

// WindowEndLT applies the LT predicate on the "window_end" field.
func WindowEndLT(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldWindowEnd, v))
}

// WindowEndLTE applies the LTE predicate on the "window_end" field.
func WindowEndLTE(v time.Time) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldWindowEnd, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldContainsFold(FieldStatus, v))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldNetwork, vs...))
}

// NetworkGT applies the GT predicate on the "network" field.
func NetworkGT(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldNetwork, v))
}

// NetworkGTE applies the GTE predicate on the "network" field.
func NetworkGTE(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldNetwork, v))
}

// NetworkLT applies the LT predicate on the "network" field.
func NetworkLT(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldNetwork, v))
}

// NetworkLTE applies the LTE predicate on the "network" field.
func NetworkLTE(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldNetwork, v))
}

// NetworkContains applies the Contains predicate on the "network" field.
func NetworkContains(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldContains(FieldNetwork, v))
}

// NetworkHasPrefix applies the HasPrefix predicate on the "network" field.
func NetworkHasPrefix(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldHasPrefix(FieldNetwork, v))
}

// NetworkHasSuffix applies the HasSuffix predicate on the "network" field.
func NetworkHasSuffix(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldHasSuffix(FieldNetwork, v))
}

// NetworkEqualFold applies the EqualFold predicate on the "network" field.
func NetworkEqualFold(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEqualFold(FieldNetwork, v))
}

// NetworkContainsFold applies the ContainsFold predicate on the "network" field.
func NetworkContainsFold(v string) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldContainsFold(FieldNetwork, v))
}

// TotalTokenFlowEQ applies the EQ predicate on the "total_token_flow" field.
func TotalTokenFlowEQ(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldTotalTokenFlow, v))
}

// TotalTokenFlowNEQ applies the NEQ predicate on the "total_token_flow" field.
func TotalTokenFlowNEQ(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldTotalTokenFlow, v))
}

// TotalTokenFlowIn applies the In predicate on the "total_token_flow" field.
func TotalTokenFlowIn(vs ...int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldTotalTokenFlow, vs...))
}

// TotalTokenFlowNotIn applies the NotIn predicate on the "total_token_flow" field.
func TotalTokenFlowNotIn(vs ...int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldTotalTokenFlow, vs...))
}

// TotalTokenFlowGT applies the GT predicate on the "total_token_flow" field.
func TotalTokenFlowGT(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldTotalTokenFlow, v))
}

// TotalTokenFlowGTE applies the GTE predicate on the "total_token_flow" field.
func TotalTokenFlowGTE(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldTotalTokenFlow, v))
}

// TotalTokenFlowLT applies the LT predicate on the "total_token_flow" field.
func TotalTokenFlowLT(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldTotalTokenFlow, v))
}

// TotalTokenFlowLTE applies the LTE predicate on the "total_token_flow" field.
func TotalTokenFlowLTE(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldTotalTokenFlow, v))
}

// TotalContributionUsdEQ applies the EQ predicate on the "total_contribution_usd" field.
func TotalContributionUsdEQ(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldTotalContributionUsd, v))
}

// TotalContributionUsdNEQ applies the NEQ predicate on the "total_contribution_usd" field.
func TotalContributionUsdNEQ(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldTotalContributionUsd, v))
}

// TotalContributionUsdIn applies the In predicate on the "total_contribution_usd" field.
func TotalContributionUsdIn(vs ...float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldTotalContributionUsd, vs...))
}

// TotalContributionUsdNotIn applies the NotIn predicate on the "total_contribution_usd" field.
func TotalContributionUsdNotIn(vs ...float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldTotalContributionUsd, vs...))
}

// TotalContributionUsdGT applies the GT predicate on the "total_contribution_usd" field.
func TotalContributionUsdGT(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldTotalContributionUsd, v))
}

// TotalContributionUsdGTE applies the GTE predicate on the "total_contribution_usd" field.
func TotalContributionUsdGTE(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldTotalContributionUsd, v))
}

// TotalContributionUsdLT applies the LT predicate on the "total_contribution_usd" field.
func TotalContributionUsdLT(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldTotalContributionUsd, v))
}

// TotalContributionUsdLTE applies the LTE predicate on the "total_contribution_usd" field.
func TotalContributionUsdLTE(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldTotalContributionUsd, v))
}

// TotalAmountCxsEQ applies the EQ predicate on the "total_amount_cxs" field.
func TotalAmountCxsEQ(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldTotalAmountCxs, v))
}

// TotalAmountCxsNEQ applies the NEQ predicate on the "total_amount_cxs" field.
func TotalAmountCxsNEQ(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldTotalAmountCxs, v))
}

// TotalAmountCxsIn applies the In predicate on the "total_amount_cxs" field.
func TotalAmountCxsIn(vs ...float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldTotalAmountCxs, vs...))
}

// TotalAmountCxsNotIn applies the NotIn predicate on the "total_amount_cxs" field.
func TotalAmountCxsNotIn(vs ...float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldTotalAmountCxs, vs...))
}

// TotalAmountCxsGT applies the GT predicate on the "total_amount_cxs" field.
func TotalAmountCxsGT(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldTotalAmountCxs, v))
}

// TotalAmountCxsGTE applies the GTE predicate on the "total_amount_cxs" field.
func TotalAmountCxsGTE(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldTotalAmountCxs, v))
}

// TotalAmountCxsLT applies the LT predicate on the "total_amount_cxs" field.
func TotalAmountCxsLT(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldTotalAmountCxs, v))
}

// TotalAmountCxsLTE applies the LTE predicate on the "total_amount_cxs" field.
func TotalAmountCxsLTE(v float64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldTotalAmountCxs, v))
}

// ItemCountEQ applies the EQ predicate on the "item_count" field.
func ItemCountEQ(v int) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldItemCount, v))
}

// ItemCountNEQ applies the NEQ predicate on the "item_count" field.
func ItemCountNEQ(v int) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldItemCount, v))
}

// ItemCountIn applies the In predicate on the "item_count" field.
func ItemCountIn(vs ...int) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldItemCount, vs...))
}

// ItemCountNotIn applies the NotIn predicate on the "item_count" field.
func ItemCountNotIn(vs ...int) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldItemCount, vs...))
}

// ItemCountGT applies the GT predicate on the "item_count" field.
func ItemCountGT(v int) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldItemCount, v))
}

// ItemCountGTE applies the GTE predicate on the "item_count" field.
func ItemCountGTE(v int) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldItemCount, v))
}

// ItemCountLT applies the LT predicate on the "item_count" field.
func ItemCountLT(v int) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldItemCount, v))
}

// ItemCountLTE applies the LTE predicate on the "item_count" field.
func ItemCountLTE(v int) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldItemCount, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotNull(FieldCreatedBy))
}

// ApprovedByEQ applies the EQ predicate on the "approved_by" field.
func ApprovedByEQ(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldEQ(FieldApprovedBy, v))
}

// ApprovedByNEQ applies the NEQ predicate on the "approved_by" field.
func ApprovedByNEQ(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNEQ(FieldApprovedBy, v))
}

// ApprovedByIn applies the In predicate on the "approved_by" field.
func ApprovedByIn(vs ...int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIn(FieldApprovedBy, vs...))
}

// ApprovedByNotIn applies the NotIn predicate on the "approved_by" field.
func ApprovedByNotIn(vs ...int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotIn(FieldApprovedBy, vs...))
}

// ApprovedByGT applies the GT predicate on the "approved_by" field.
func ApprovedByGT(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGT(FieldApprovedBy, v))
}

// ApprovedByGTE applies the GTE predicate on the "approved_by" field.
func ApprovedByGTE(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldGTE(FieldApprovedBy, v))
}

// ApprovedByLT applies the LT predicate on the "approved_by" field.
func ApprovedByLT(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLT(FieldApprovedBy, v))
}

// ApprovedByLTE applies the LTE predicate on the "approved_by" field.
func ApprovedByLTE(v int64) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldLTE(FieldApprovedBy, v))
}

// ApprovedByIsNil applies the IsNil predicate on the "approved_by" field.
func ApprovedByIsNil() predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldIsNull(FieldApprovedBy))
}

// ApprovedByNotNil applies the NotNil predicate on the "approved_by" field.
func ApprovedByNotNil() predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.FieldNotNull(FieldApprovedBy))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuotaNetPayoutBatch) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuotaNetPayoutBatch) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuotaNetPayoutBatch) predicate.QuotaNetPayoutBatch {
	return predicate.QuotaNetPayoutBatch(sql.NotPredicates(p))
}
